# Generated by Django 6.0.5 on 2026-07-19 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0009_plano_assinatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo_profissional', models.CharField(blank=True, max_length=180)),
                ('resumo', models.TextField(blank=True)),
                ('telefone_publico', models.CharField(blank=True, max_length=30)),
                ('email_publico', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('linkedin', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('publico', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculo', to=settings.AUTH_USER_MODEL)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_curriculo_tb',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=180)),
                ('instituicao', models.CharField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_curso_tb',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=180)),
                ('instituicao', models.CharField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=180)),
                ('atual', models.BooleanField(default=False)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_experiencia_tb',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=180)),
                ('instituicao', models.CharField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=80)),
                ('concluido', models.BooleanField(default=False)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_formacao_tb',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(blank=True)),
                ('responsabilidades', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('tipo_contrato', models.CharField(max_length=40)),
                ('modalidade', models.CharField(max_length=30)),
                ('jornada', models.CharField(blank=True, max_length=60)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('aceita_pcd', models.BooleanField(default=False)),
                ('experiencia', models.CharField(blank=True, max_length=120)),
                ('escolaridade', models.CharField(blank=True, max_length=120)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('encerramento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('PUBLICADA', 'Publicada'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='organizations.empresa')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_vaga_tb',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('RETIRADA', 'Retirada')], default='ENVIADA', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='recruitment.curriculo')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='recruitment.vaga')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_candidatura_tb',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120)),
                ('nivel', models.CharField(blank=True, max_length=40)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_habilidade_tb',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('curriculo', 'nome'), name='recruit_habilidade_ativa_uk')],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=80)),
                ('nivel', models.CharField(max_length=40)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_idioma_tb',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('curriculo', 'nome'), name='recruit_idioma_ativo_uk')],
            },
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['empresa', 'status', 'ativo'], name='recruit_vaga_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['slug'], name='recruit_vaga_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['vaga', 'status'], name='recruit_cand_vaga_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatura',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('vaga', 'usuario'), name='recruit_candidatura_ativa_uk'),
        ),
    ]
