# Generated by Django 6.0.5 on 2026-07-20 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrar_visibilidade_e_privacidade(apps, schema_editor):
    Curriculo = apps.get_model('recruitment', 'Curriculo')
    Privacidade = apps.get_model('recruitment', 'CurriculoPrivacidade')
    for curriculo in Curriculo.objects.all().iterator():
        curriculo.visibilidade = 'PUBLICO' if curriculo.publico else 'PRIVADO'
        curriculo.save(update_fields=['visibilidade'])
        Privacidade.objects.get_or_create(curriculo=curriculo)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculoInformacaoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('possui_cnh', models.BooleanField(default=False)),
                ('categorias_cnh', models.CharField(blank=True, max_length=20)),
                ('veiculo_proprio', models.BooleanField(default=False)),
                ('disponibilidade_horario', models.TextField(blank=True)),
                ('trabalho_voluntario', models.TextField(blank=True)),
                ('premiacoes', models.TextField(blank=True)),
                ('interesses_profissionais', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_adicionais', to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_curriculo_info_adicional_tb',
            },
        ),
        migrations.CreateModel(
            name='CurriculoPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('mostrar_telefone', models.BooleanField(default=False)),
                ('mostrar_email', models.BooleanField(default=False)),
                ('mostrar_cidade', models.BooleanField(default=True)),
                ('mostrar_estado', models.BooleanField(default=True)),
                ('mostrar_linkedin', models.BooleanField(default=True)),
                ('mostrar_portfolio', models.BooleanField(default=True)),
                ('mostrar_pretensao_salarial', models.BooleanField(default=False)),
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacidade', to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_curriculo_privacidade_tb',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('url', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='curriculos/projetos/%Y/%m/')),
                ('tecnologias', models.TextField(blank=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='recruitment.curriculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recruitment_projeto_tb',
                'ordering': ['-destaque', '-data', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='consentimento_compartilhamento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='curriculo_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='snapshot_versao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='area_profissional',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='disponibilidade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='disponivel_mudanca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='disponivel_viagens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='modalidade_preferida',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='nivel_profissional',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='objetivo_profissional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='pretensao_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='site_profissional',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PREENCHIMENTO', 'Em preenchimento'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='tipo_contratacao_desejada',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='visibilidade',
            field=models.CharField(choices=[('PRIVADO', 'Privado'), ('CANDIDATURAS', 'Visível apenas em candidaturas'), ('PUBLICO', 'Público')], default='PRIVADO', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo_credencial',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('CURSO', 'Curso'), ('CERTIFICACAO', 'Certificação')], default='CURSO', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='url_credencial',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='resultados_responsabilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='tecnologias_habilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='tipo_contratacao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='formacao',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formacao',
            name='situacao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='anos_experiencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idioma',
            name='conversacao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idioma',
            name='escrita',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='idioma',
            name='leitura',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['visibilidade', 'status', 'ativo'], name='recruit_curr_vis_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['curriculo', 'ativo'], name='recruit_proj_curr_ativo_idx'),
        ),
        migrations.RunPython(migrar_visibilidade_e_privacidade, migrations.RunPython.noop),
    ]
