# Generated by Django 6.0.5 on 2026-07-20 18:27

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_curriculo_expansao_compativel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculo',
            constraint=models.CheckConstraint(condition=models.Q(('etapa_atual__gte', 1), ('etapa_atual__lte', 10)), name='recruit_curriculo_etapa_ck'),
        ),
        migrations.AddConstraint(
            model_name='curriculo',
            constraint=models.CheckConstraint(condition=models.Q(('pretensao_salarial__isnull', True), ('pretensao_salarial__gte', 0), _connector='OR'), name='recruit_curriculo_salario_ck'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('inicio__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='recruit_curso_datas_ck'),
        ),
        migrations.AddConstraint(
            model_name='experiencia',
            constraint=models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('inicio__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='recruit_exp_datas_ck'),
        ),
        migrations.AddConstraint(
            model_name='experiencia',
            constraint=models.CheckConstraint(condition=models.Q(('atual', False), ('fim__isnull', True), _connector='OR'), name='recruit_exp_atual_fim_ck'),
        ),
        migrations.AddConstraint(
            model_name='formacao',
            constraint=models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('inicio__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='recruit_form_datas_ck'),
        ),
        migrations.AddConstraint(
            model_name='habilidade',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('curriculo'), condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), name='recruit_habilidade_nome_ci_uk'),
        ),
        migrations.AddConstraint(
            model_name='idioma',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('curriculo'), condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), name='recruit_idioma_nome_ci_uk'),
        ),
    ]
