# Generated by Django 6.0.5 on 2026-08-16 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('nome_exibicao', models.CharField(blank=True, max_length=120)),
                ('biografia', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='social/avatars/%Y/%m/')),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('RESTRITO', 'Restrito'), ('PRIVADO', 'Privado')], db_index=True, default='PUBLICO', max_length=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_profile_tb',
                'ordering': ['nome_exibicao', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SocialFollow',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores_relacoes', to='social.socialprofile')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo_relacoes', to='social.socialprofile')),
            ],
            options={
                'db_table': 'social_follow_tb',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSeguidor',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores_sociais', to='organizations.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_seguidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_empresa_seguidor_tb',
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='social_user_company_date_idx'), models.Index(fields=['empresa', 'criado_em'], name='social_company_follow_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='social_company_follow_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='socialprofile',
            index=models.Index(fields=['slug'], name='social_profile_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='socialfollow',
            index=models.Index(fields=['seguidor', 'criado_em'], name='social_following_date_idx'),
        ),
        migrations.AddIndex(
            model_name='socialfollow',
            index=models.Index(fields=['seguido', 'criado_em'], name='social_followers_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialfollow',
            constraint=models.UniqueConstraint(fields=('seguidor', 'seguido'), name='social_follow_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialfollow',
            constraint=models.CheckConstraint(condition=models.Q(('seguidor', models.F('seguido')), _negated=True), name='social_follow_not_self'),
        ),
    ]
