# Generated by Django 6.0.5 on 2026-08-16 16:58

import apps.core.domain
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'social_conversation_tb',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_participantes', to='social.socialconversation')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_conversas_sociais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_conversation_participant_tb',
            },
        ),
        migrations.AddField(
            model_name='socialconversation',
            name='participantes',
            field=models.ManyToManyField(related_name='conversas_sociais', through='social.SocialConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SocialFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], db_index=True, default='PENDENTE', max_length=10)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to='social.socialprofile')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='social.socialprofile')),
            ],
            options={
                'db_table': 'social_follow_request_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imagem', models.ImageField(blank=True, upload_to='social/posts/%Y/%m/', validators=[apps.core.domain.validar_imagem_publica])),
                ('legenda', models.TextField(blank=True, max_length=2200, validators=[apps.core.domain.texto_sem_html])),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('SEGUIDORES', 'Seguidores'), ('SOMENTE_EU', 'Somente eu')], db_index=True, default='PUBLICO', max_length=12)),
                ('publicado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('feed_ate', models.DateTimeField(blank=True, db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('conteudo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.socialprofile')),
                ('conteudo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'social_post_tb',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('texto', models.TextField(blank=True, max_length=2000, validators=[apps.core.domain.texto_sem_html])),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='social.socialconversation')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_sociais', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='social.socialpost')),
            ],
            options={
                'db_table': 'social_message_tb',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('texto', models.TextField(max_length=1000, validators=[apps.core.domain.texto_sem_html])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='social.socialprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='social.socialpost')),
            ],
            options={
                'db_table': 'social_post_comment_tb',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='social.socialpost')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_sociais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_like_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialPostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvamentos', to='social.socialpost')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_sociais_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_save_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imagem', models.ImageField(upload_to='social/stories/%Y/%m/', validators=[apps.core.domain.validar_imagem_publica])),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('SEGUIDORES', 'Seguidores'), ('SOMENTE_EU', 'Somente eu')], db_index=True, default='PUBLICO', max_length=12)),
                ('publicado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='social.socialprofile')),
            ],
            options={
                'db_table': 'social_story_tb',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to='social.socialprofile')),
                ('bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_feitos', to='social.socialprofile')),
            ],
            options={
                'db_table': 'social_block_tb',
                'constraints': [models.UniqueConstraint(fields=('bloqueador', 'bloqueado'), name='social_block_unique'), models.CheckConstraint(condition=models.Q(('bloqueador', models.F('bloqueado')), _negated=True), name='social_block_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialconversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversa', 'usuario'), name='social_conversation_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialfollowrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('solicitante', 'destinatario'), name='social_follow_request_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialfollowrequest',
            constraint=models.CheckConstraint(condition=models.Q(('solicitante', models.F('destinatario')), _negated=True), name='social_follow_request_not_self'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['ativo', 'feed_ate', 'publicado_em'], name='social_post_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.CheckConstraint(condition=models.Q(('imagem__gt', ''), models.Q(('conteudo_tipo__isnull', False), ('conteudo_id__isnull', False)), _connector='OR'), name='social_post_has_content'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.CheckConstraint(condition=models.Q(('texto__gt', ''), ('post__isnull', False), _connector='OR'), name='social_message_has_content'),
        ),
        migrations.AddConstraint(
            model_name='socialpostlike',
            constraint=models.UniqueConstraint(fields=('post', 'usuario'), name='social_post_like_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialpostsave',
            constraint=models.UniqueConstraint(fields=('post', 'usuario'), name='social_post_save_unique'),
        ),
        migrations.AddIndex(
            model_name='socialstory',
            index=models.Index(fields=['ativo', 'expira_em'], name='social_story_active_idx'),
        ),
    ]
