# Generated by Django 6.0.5 on 2026-08-17 12:32

import apps.core.domain
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialconversation_socialconversationparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConversationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mensagem_inicial', models.TextField(blank=True, max_length=2000, validators=[apps.core.domain.texto_sem_html])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], db_index=True, default='PENDENTE', max_length=8)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_conversation_request_tb',
            },
        ),
        migrations.RemoveConstraint(
            model_name='socialmessage',
            name='social_message_has_content',
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='social.socialstory'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.CheckConstraint(condition=models.Q(('texto__gt', ''), ('post__isnull', False), ('story__isnull', False), _connector='OR'), name='social_message_has_content'),
        ),
        migrations.AddField(
            model_name='socialconversationrequest',
            name='conversa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='social.socialconversation'),
        ),
        migrations.AddField(
            model_name='socialconversationrequest',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_conversa_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialconversationrequest',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_conversa', to='social.socialpost'),
        ),
        migrations.AddField(
            model_name='socialconversationrequest',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_conversa_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialconversationrequest',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_conversa', to='social.socialstory'),
        ),
        migrations.AddIndex(
            model_name='socialconversationrequest',
            index=models.Index(fields=['destinatario', 'status', 'criado_em'], name='social_conv_req_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialconversationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('solicitante', 'destinatario'), name='social_conv_request_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='socialconversationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('solicitante', models.F('destinatario')), _negated=True), name='social_conv_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='socialconversationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('mensagem_inicial__gt', ''), ('post__isnull', False), ('story__isnull', False), _connector='OR'), name='social_conv_request_has_content'),
        ),
    ]
