# Generated by Django 6.0.5 on 2026-08-18 14:08

import apps.core.domain
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0003_socialconversationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('STORY_LIKE', 'Curtida em Story'), ('STORY_REACTION', 'Reação em Story'), ('STORY_REPLY', 'Resposta a Story'), ('MESSAGE_REQUEST', 'Solicitação de mensagem'), ('MESSAGE_REQUEST_ACCEPTED', 'Solicitação aceita'), ('NEW_MESSAGE', 'Nova mensagem'), ('NEW_FOLLOWER', 'Novo seguidor'), ('FOLLOW_REQUEST', 'Solicitação para seguir'), ('FOLLOW_REQUEST_ACCEPTED', 'Solicitação para seguir aceita'), ('POST_LIKE', 'Curtida em post'), ('POST_COMMENT', 'Comentário em post'), ('SYSTEM', 'Sistema')], db_index=True, max_length=32)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lida_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('chave_dedupe', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'db_table': 'social_notification_tb',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SocialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('alvo_id', models.PositiveBigIntegerField()),
                ('motivo', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, max_length=1000, validators=[apps.core.domain.texto_sem_html])),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('ENCERRADA', 'Encerrada')], db_index=True, default='ABERTA', max_length=12)),
            ],
            options={
                'db_table': 'social_report_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialStoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_story_like_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialStoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('LOVE', 'Amei'), ('HAHA', 'Engraçado'), ('HEART_EYES', 'Apaixonado'), ('WOW', 'Surpreso'), ('SAD', 'Triste'), ('CLAP', 'Aplausos'), ('FIRE', 'Incrível')], max_length=12)),
            ],
            options={
                'db_table': 'social_story_reaction_tb',
            },
        ),
        migrations.CreateModel(
            name='SocialStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_visualizacao_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_story_view_tb',
            },
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='contexto_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='contexto_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('STORY_REPLY', 'Resposta a Story'), ('STORY_REACTION', 'Reação a Story'), ('SYSTEM', 'Sistema')], db_index=True, default='TEXT', max_length=16),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='confirmacao_leitura',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='permitir_reacoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='quem_pode_responder_story',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('SEGUIDORES', 'Seguidores'), ('SEGUINDO', 'Pessoas que sigo'), ('NINGUEM', 'Ninguém')], default='TODOS', max_length=12),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='quem_pode_solicitar_mensagem',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('SEGUIDORES', 'Seguidores'), ('SEGUINDO', 'Pessoas que sigo'), ('NINGUEM', 'Ninguém')], default='TODOS', max_length=12),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversa', 'criado_em'], name='social_message_conv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversa', 'lida_em'], name='social_message_unread_idx'),
        ),
        migrations.AddField(
            model_name='socialnotification',
            name='ator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_sociais_geradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialnotification',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_sociais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialnotification',
            name='objeto_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='socialreport',
            name='alvo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='socialreport',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_sociais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialstorylike',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='social.socialstory'),
        ),
        migrations.AddField(
            model_name='socialstorylike',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialstoryreaction',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='social.socialstory'),
        ),
        migrations.AddField(
            model_name='socialstoryreaction',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialstoryview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='social.socialstory'),
        ),
        migrations.AddField(
            model_name='socialstoryview',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_visualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='socialnotification',
            index=models.Index(fields=['destinatario', 'lida_em', 'criado_em'], name='social_notification_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_dedupe', ''), _negated=True), fields=('destinatario', 'chave_dedupe'), name='social_notification_dedupe_unique'),
        ),
        migrations.AddIndex(
            model_name='socialreport',
            index=models.Index(fields=['status', 'criado_em'], name='social_report_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTA')), fields=('denunciante', 'alvo_tipo', 'alvo_id'), name='social_report_open_unique'),
        ),
        migrations.AddIndex(
            model_name='socialstorylike',
            index=models.Index(fields=['story', 'criado_em'], name='social_story_like_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialstorylike',
            constraint=models.UniqueConstraint(fields=('story', 'usuario'), name='social_story_like_unique'),
        ),
        migrations.AddIndex(
            model_name='socialstoryreaction',
            index=models.Index(fields=['story', 'tipo'], name='social_story_reaction_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialstoryreaction',
            constraint=models.UniqueConstraint(fields=('story', 'usuario'), name='social_story_reaction_unique'),
        ),
        migrations.AddIndex(
            model_name='socialstoryview',
            index=models.Index(fields=['story', 'criado_em'], name='social_story_view_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialstoryview',
            constraint=models.UniqueConstraint(fields=('story', 'usuario'), name='social_story_view_unique'),
        ),
    ]
