# Generated by Django 6.0.5 on 2026-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_social_2_interactions_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialstoryview',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
