# Generated by Django 6.0.5 on 2026-08-18 17:01

import uuid

import apps.core.domain
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


def migrar_mensagens_iniciais(apps, schema_editor):
    Pedido = apps.get_model(
        "social",
        "SocialConversationRequest",
    )

    Mensagem = apps.get_model(
        "social",
        "SocialConversationRequestMessage",
    )

    for pedido in Pedido.objects.all().iterator():
        texto = (pedido.mensagem_inicial or "").strip()

        if not texto and not pedido.post_id and not pedido.story_id:
            continue

        mensagem = Mensagem.objects.create(
            solicitacao_id=pedido.pk,
            remetente_id=pedido.solicitante_id,
            texto=texto,
            post_id=pedido.post_id,
            story_id=pedido.story_id,
            ativo=True,
        )

        if pedido.criado_em:
            Mensagem.objects.filter(
                pk=mensagem.pk,
            ).update(
                criado_em=pedido.criado_em,
                atualizado_em=pedido.criado_em,
            )


def reverter_mensagens_iniciais(apps, schema_editor):
    Mensagem = apps.get_model(
        "social",
        "SocialConversationRequestMessage",
    )

    Mensagem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_story_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialConversationRequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "texto",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        validators=[apps.core.domain.texto_sem_html],
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens_solicitacao_conversa",
                        to="social.socialpost",
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens_solicitacao_conversa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="social.socialconversationrequest",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens_solicitacao_conversa",
                        to="social.socialstory",
                    ),
                ),
            ],
            options={
                "db_table": "social_conversation_request_message_tb",
                "ordering": ["criado_em"],
                "indexes": [
                    models.Index(
                        fields=["solicitacao", "criado_em"],
                        name="social_conv_req_msg_date_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("texto__gt", ""),
                            ("post__isnull", False),
                            ("story__isnull", False),
                            _connector="OR",
                        ),
                        name="social_conv_req_msg_content",
                    ),
                ],
            },
        ),

        migrations.RunPython(
            migrar_mensagens_iniciais,
            reverter_mensagens_iniciais,
        ),
    ]