# Generated by Django 6.0.5 on 2026-08-15 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('visitors', models.PositiveBigIntegerField(default=0)),
                ('search_views', models.PositiveBigIntegerField(default=0)),
                ('service_views', models.PositiveBigIntegerField(default=0)),
                ('product_views', models.PositiveBigIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveBigIntegerField(default=0)),
                ('phone_clicks', models.PositiveBigIntegerField(default=0)),
                ('website_clicks', models.PositiveBigIntegerField(default=0)),
                ('directions_clicks', models.PositiveBigIntegerField(default=0)),
                ('leads', models.PositiveBigIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='organizations.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'date'], name='analytics_daily_company_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'empresa'), name='analytics_daily_company_uk')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDailyCompanyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('term', models.CharField(max_length=120)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('selections', models.PositiveBigIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_terms', to='organizations.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'date', 'term'], name='analytics_company_term_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'empresa', 'term'), name='analytics_daily_term_uk')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=48)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=64)),
                ('medium', models.CharField(blank=True, max_length=64)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('content', models.CharField(blank=True, max_length=120)),
                ('first_source', models.CharField(blank=True, max_length=64)),
                ('first_medium', models.CharField(blank=True, max_length=64)),
                ('first_campaign', models.CharField(blank=True, max_length=120)),
                ('gclid', models.CharField(blank=True, max_length=180)),
                ('gbraid', models.CharField(blank=True, max_length=180)),
                ('wbraid', models.CharField(blank=True, max_length=180)),
                ('referrer_host', models.CharField(blank=True, max_length=180)),
                ('landing_path', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(max_length=300)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='organizations.empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'created_at', 'event_name'], name='analytics_co_date_event_idx'), models.Index(fields=['object_type', 'object_id', 'created_at'], name='analytics_object_date_idx'), models.Index(fields=['source', 'created_at'], name='analytics_source_date_idx')],
            },
        ),
    ]
