# Generated by Django 6.0.5 on 2026-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdailycompany',
            name='email_clicks',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
