# Generated by Django 6.0.5 on 2026-07-19 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('government', '0001_initial'),
        ('media', '0001_initial'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS news;', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(db_column='news_categoria_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_categoria_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='news_categoria_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='news_categoria_slug', max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='news_categoria_descricao')),
                ('ordem', models.PositiveIntegerField(db_column='news_categoria_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_categoria_ativo', default=True)),
                ('categoria_pai', models.ForeignKey(blank=True, db_column='news_categoria_fk_pai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='news.categorianoticia')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_categoria_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_categoria_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_categoria_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_categoria_tb"',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(db_column='news_artigo_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_artigo_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='news_artigo_titulo', max_length=220)),
                ('subtitulo', models.CharField(blank=True, db_column='news_artigo_subtitulo', max_length=250)),
                ('slug', models.SlugField(blank=True, db_column='news_artigo_slug', max_length=250, unique=True)),
                ('resumo', models.TextField(blank=True, db_column='news_artigo_resumo')),
                ('conteudo', models.TextField(db_column='news_artigo_conteudo')),
                ('imagem_capa', models.ImageField(blank=True, db_column='news_artigo_imagem', upload_to='news/artigos/')),
                ('credito_imagem', models.CharField(blank=True, db_column='news_artigo_credito', max_length=180)),
                ('fonte', models.CharField(blank=True, db_column='news_artigo_fonte', max_length=180)),
                ('url_fonte', models.URLField(blank=True, db_column='news_artigo_url_fonte', max_length=500)),
                ('data_fato', models.DateTimeField(blank=True, db_column='news_artigo_data_fato', null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado'), ('PAUSADO', 'Pausado'), ('REJEITADO', 'Rejeitado')], db_column='news_artigo_status', default='RASCUNHO', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, db_column='news_artigo_motivo_rejeicao')),
                ('destaque', models.BooleanField(db_column='news_artigo_destaque', default=False)),
                ('urgente', models.BooleanField(db_column='news_artigo_urgente', default=False)),
                ('titulo_seo', models.CharField(blank=True, db_column='news_artigo_titulo_seo', max_length=70)),
                ('descricao_seo', models.CharField(blank=True, db_column='news_artigo_descricao_seo', max_length=160)),
                ('imagem_social', models.ImageField(blank=True, db_column='news_artigo_imagem_social', upload_to='news/social/')),
                ('publicado_em', models.DateTimeField(blank=True, db_column='news_artigo_publicado_em', null=True)),
                ('revisado_em', models.DateTimeField(blank=True, db_column='news_artigo_revisado_em', null=True)),
                ('ativo', models.BooleanField(db_column='news_artigo_ativo', default=True)),
                ('categoria', models.ForeignKey(db_column='news_artigo_fk_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='news.categorianoticia')),
                ('acao_publica', models.ForeignKey(blank=True, db_column='news_artigo_fk_acao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='government.acaopublica')),
                ('autor', models.ForeignKey(db_column='news_artigo_fk_autor', on_delete=django.db.models.deletion.PROTECT, related_name='artigos_news', to=settings.AUTH_USER_MODEL)),
                ('campeonato', models.ForeignKey(blank=True, db_column='news_artigo_fk_campeonato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='sports.campeonato')),
                ('episodio', models.ForeignKey(blank=True, db_column='news_artigo_fk_episodio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='media.episodio')),
                ('publicador', models.ForeignKey(blank=True, db_column='news_artigo_fk_publicador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_publicados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, db_column='news_artigo_fk_revisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_revisados', to=settings.AUTH_USER_MODEL)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_artigo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_artigo_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_artigo_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_artigo_tb"',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoBloco',
            fields=[
                ('id', models.BigAutoField(db_column='news_bloco_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_bloco_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('VIDEO_YOUTUBE', 'Vídeo YouTube'), ('CITACAO', 'Citação'), ('GALERIA', 'Galeria'), ('LINK', 'Link'), ('SUBTITULO', 'Subtítulo')], db_column='news_bloco_tipo', max_length=20)),
                ('titulo', models.CharField(blank=True, db_column='news_bloco_titulo', max_length=220)),
                ('conteudo', models.TextField(blank=True, db_column='news_bloco_conteudo')),
                ('url', models.URLField(blank=True, db_column='news_bloco_url', max_length=500)),
                ('identificador_externo', models.CharField(blank=True, db_column='news_bloco_identificador', max_length=120)),
                ('ordem', models.PositiveIntegerField(db_column='news_bloco_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_bloco_ativo', default=True)),
                ('artigo', models.ForeignKey(db_column='news_bloco_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='news.artigo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_bloco_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_bloco_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_bloco_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_artigo_bloco_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoFonte',
            fields=[
                ('id', models.BigAutoField(db_column='news_fonte_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_fonte_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='news_fonte_titulo', max_length=180)),
                ('url', models.URLField(db_column='news_fonte_url', max_length=500)),
                ('veiculo', models.CharField(blank=True, db_column='news_fonte_veiculo', max_length=160)),
                ('data_acesso', models.DateField(db_column='news_fonte_data_acesso')),
                ('ordem', models.PositiveIntegerField(db_column='news_fonte_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_fonte_ativo', default=True)),
                ('artigo', models.ForeignKey(db_column='news_fonte_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='news.artigo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_fonte_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_fonte_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_fonte_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_artigo_fonte_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['status', 'publicado_em'], name='news_artigo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['categoria', 'status'], name='news_artigo_categoria_idx'),
        ),
    ]

