# Generated by Django 6.0.5 on 2026-07-27 13:00

import apps.news.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


AREAS = [
    'Cidade', 'Agro', 'Universidade', 'Ciência e Tecnologia',
    'Saúde e Bem-estar', 'Economia e Negócios', 'Política e Poder Público',
    'Mobilidade e Trânsito', 'Cultura', 'Esportes', 'Turismo',
    'Meio Ambiente', 'Empregos e Oportunidades', 'Educação',
    'Colunistas', 'Comunidade',
]

PERMISSOES = [
    'news.acessar_painel', 'news.criar', 'news.editar_propria',
    'news.editar_qualquer', 'news.enviar_revisao', 'news.revisar',
    'news.solicitar_correcao', 'news.aprovar', 'news.agendar',
    'news.publicar', 'news.despublicar', 'news.arquivar', 'news.excluir',
    'news.restaurar', 'news.gerenciar_autores', 'news.gerenciar_colunistas',
    'news.gerenciar_colunas', 'news.gerenciar_categorias',
    'news.gerenciar_temas', 'news.gerenciar_tags',
    'news.gerenciar_especialidades', 'news.gerenciar_series',
    'news.gerenciar_fontes', 'news.gerenciar_imagens',
    'news.gerenciar_destaques',
]


def preparar_base_editorial(apps, schema_editor):
    Artigo = apps.get_model('news', 'Artigo')
    Autor = apps.get_model('news', 'Autor')
    Categoria = apps.get_model('news', 'CategoriaNoticia')
    Permissao = apps.get_model('core', 'Permissao')

    autores = {}
    for artigo in Artigo.objects.select_related('autor').all():
        usuario = artigo.autor
        autor = autores.get(usuario.pk)
        if autor is None:
            nome = (
                getattr(usuario, 'nome_exibicao', '')
                or usuario.get_full_name()
                or usuario.username
            )
            base_slug = slugify(nome) or f'autor-{usuario.pk}'
            slug = base_slug
            contador = 2
            while Autor.objects.filter(slug=slug).exclude(usuario_id=usuario.pk).exists():
                slug = f'{base_slug}-{contador}'
                contador += 1
            autor, _ = Autor.objects.update_or_create(
                usuario_id=usuario.pk,
                defaults={
                    'nome': nome,
                    'slug': slug,
                    'mini_bio': getattr(usuario, 'biografia', '')[:280],
                    'biografia': getattr(usuario, 'biografia', ''),
                    'ativo': True,
                    'excluido_em': None,
                },
            )
            autores[usuario.pk] = autor
        artigo.autor_editorial_id = autor.pk
        artigo.save(update_fields=['autor_editorial'])

    existentes = {
        slugify(categoria.nome)
        for categoria in Categoria.objects.all()
    } | set(Categoria.objects.values_list('slug', flat=True))
    proxima_ordem = Categoria.objects.order_by('-ordem').values_list('ordem', flat=True).first() or 0
    for nome in AREAS:
        slug = slugify(nome)
        if slug in existentes:
            continue
        proxima_ordem += 1
        Categoria.objects.create(
            nome=nome, slug=slug, ordem=proxima_ordem, ativo=True,
        )
        existentes.add(slug)

    for codigo in PERMISSOES:
        Permissao.objects.update_or_create(
            codigo=codigo,
            defaults={'nome': codigo, 'descricao': codigo, 'ativo': True},
        )


def reverter_base_editorial(apps, schema_editor):
    Artigo = apps.get_model('news', 'Artigo')
    Artigo.objects.update(autor_editorial=None)


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
        ('media', '0010_preparar_dados_fase3_yubotuka'),
        ('news', '0001_initial'),
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('sports', '0002_alter_atleta_foto_alter_campeonato_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeAutor',
            fields=[
                ('id', models.BigAutoField(db_column='news_especialidade_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_especialidade_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='news_especialidade_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='news_especialidade_slug', max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='news_especialidade_descricao')),
                ('ativo', models.BooleanField(db_column='news_especialidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_especialidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_especialidade_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_especialidade_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_especialidade_autor_tb"',
                'ordering': ['nome'],
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SerieEditorial',
            fields=[
                ('id', models.BigAutoField(db_column='news_serie_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_serie_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='news_serie_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='news_serie_slug', max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='news_serie_descricao')),
                ('imagem', models.ImageField(blank=True, upload_to='news/series/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(db_column='news_serie_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_serie_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_serie_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_serie_excluido_em', null=True)),
            ],
            options={
                'db_table': '"news"."news_serie_editorial_tb"',
                'ordering': ['ordem', 'nome'],
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='news_tag_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"news"."news_tag_tb"',
                'ordering': ['nome'],
                'abstract': False,
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='news_tema_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"news"."news_tema_tb"',
                'ordering': ['nome'],
                'abstract': False,
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='artigo',
            name='agendado_para',
            field=models.DateTimeField(blank=True, db_column='news_artigo_agendado_para', null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tipo_editorial',
            field=models.CharField(choices=[('NOTICIA', 'Notícia'), ('REPORTAGEM', 'Reportagem'), ('ARTIGO', 'Artigo'), ('COLUNA', 'Coluna'), ('OPINIAO', 'Opinião'), ('EDITORIAL', 'Editorial'), ('ENTREVISTA', 'Entrevista'), ('NOTA', 'Nota')], db_column='news_artigo_tipo_editorial', default='NOTICIA', max_length=20),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='autor_externo',
            field=models.CharField(blank=True, db_column='news_fonte_autor_externo', max_length=180),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='data_original',
            field=models.DateField(blank=True, db_column='news_fonte_data_original', null=True),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='exibir_publicamente',
            field=models.BooleanField(db_column='news_fonte_exibir_publicamente', default=True),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='nome_fonte',
            field=models.CharField(blank=True, db_column='news_fonte_nome', max_length=180),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='observacao',
            field=models.TextField(blank=True, db_column='news_fonte_observacao'),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='organizacao',
            field=models.ForeignKey(blank=True, db_column='news_fonte_fk_organizacao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_news', to='organizations.empresa'),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='principal',
            field=models.BooleanField(db_column='news_fonte_principal', default=False),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='tipo',
            field=models.CharField(choices=[('SITE_OFICIAL', 'Site oficial'), ('ORGAO_PUBLICO', 'Órgão público'), ('UNIVERSIDADE', 'Universidade'), ('ARTIGO_CIENTIFICO', 'Artigo científico'), ('EMPRESA', 'Empresa'), ('ENTREVISTA', 'Entrevista'), ('REDE_SOCIAL_OFICIAL', 'Rede social oficial'), ('DOCUMENTO_PUBLICO', 'Documento público'), ('ASSESSORIA', 'Assessoria'), ('OUTRO', 'Outro')], db_column='news_fonte_tipo', default='OUTRO', max_length=30),
        ),
        migrations.AddField(
            model_name='artigofonte',
            name='verificada',
            field=models.BooleanField(db_column='news_fonte_verificada', default=False),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO_REVISAO', 'Enviado para revisão'), ('EM_REVISAO', 'Em revisão'), ('CORRECAO_SOLICITADA', 'Correção solicitada'), ('APROVADO', 'Aprovado'), ('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado'), ('REJEITADO', 'Rejeitado'), ('DESPUBLICADO', 'Despublicado'), ('ARQUIVADO', 'Arquivado')], db_column='news_artigo_status', default='RASCUNHO', max_length=24),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(db_column='news_autor_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_autor_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='news_autor_nome', max_length=160)),
                ('slug', models.SlugField(blank=True, db_column='news_autor_slug', max_length=180, unique=True)),
                ('foto', models.ImageField(blank=True, db_column='news_autor_foto', upload_to='news/autores/')),
                ('mini_bio', models.CharField(blank=True, db_column='news_autor_mini_bio', max_length=280)),
                ('biografia', models.TextField(blank=True, db_column='news_autor_biografia')),
                ('site', models.URLField(blank=True, db_column='news_autor_site', max_length=500)),
                ('instagram', models.URLField(blank=True, db_column='news_autor_instagram', max_length=500)),
                ('facebook', models.URLField(blank=True, db_column='news_autor_facebook', max_length=500)),
                ('linkedin', models.URLField(blank=True, db_column='news_autor_linkedin', max_length=500)),
                ('x', models.URLField(blank=True, db_column='news_autor_x', max_length=500)),
                ('tiktok', models.URLField(blank=True, db_column='news_autor_tiktok', max_length=500)),
                ('youtube', models.URLField(blank=True, db_column='news_autor_youtube', max_length=500)),
                ('ativo', models.BooleanField(db_column='news_autor_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_autor_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_autor_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_autor_excluido_em', null=True)),
                ('usuario', models.OneToOneField(blank=True, db_column='news_autor_fk_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_news', to=settings.AUTH_USER_MODEL)),
                ('especialidades', models.ManyToManyField(blank=True, db_table='"news"."news_autor_especialidade_tb"', related_name='autores', to='news.especialidadeautor')),
            ],
            options={
                'db_table': '"news"."news_autor_tb"',
                'ordering': ['nome'],
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor_editorial',
            field=models.ForeignKey(blank=True, db_column='news_artigo_fk_autor_editorial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='news.autor'),
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(db_column='news_coluna_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_coluna_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='news_coluna_nome', max_length=160)),
                ('slug', models.SlugField(blank=True, db_column='news_coluna_slug', max_length=180, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='news_coluna_descricao')),
                ('imagem', models.ImageField(blank=True, db_column='news_coluna_imagem', upload_to='news/colunas/')),
                ('ordem', models.PositiveIntegerField(db_column='news_coluna_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_coluna_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_coluna_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_coluna_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_coluna_excluido_em', null=True)),
                ('autor', models.ForeignKey(db_column='news_coluna_fk_autor', on_delete=django.db.models.deletion.PROTECT, related_name='colunas', to='news.autor')),
            ],
            options={
                'db_table': '"news"."news_coluna_tb"',
                'ordering': ['ordem', 'nome'],
            },
            bases=(apps.news.models.SlugModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='artigo',
            name='coluna',
            field=models.ForeignKey(blank=True, db_column='news_artigo_fk_coluna', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='news.coluna'),
        ),
        migrations.CreateModel(
            name='Colunista',
            fields=[
                ('id', models.BigAutoField(db_column='news_colunista_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_colunista_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(blank=True, db_column='news_colunista_titulo', max_length=140)),
                ('ordem', models.PositiveIntegerField(db_column='news_colunista_ordem', default=0)),
                ('destaque', models.BooleanField(db_column='news_colunista_destaque', default=False)),
                ('ativo', models.BooleanField(db_column='news_colunista_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_colunista_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_colunista_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_colunista_excluido_em', null=True)),
                ('autor', models.OneToOneField(db_column='news_colunista_fk_autor', on_delete=django.db.models.deletion.PROTECT, related_name='perfil_colunista', to='news.autor')),
            ],
            options={
                'db_table': '"news"."news_colunista_tb"',
                'ordering': ['ordem', 'autor__nome'],
            },
        ),
        migrations.CreateModel(
            name='DestaqueEditorial',
            fields=[
                ('id', models.BigAutoField(db_column='news_destaque_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_destaque_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('posicao', models.CharField(choices=[('HOME_PRINCIPAL', 'Home principal'), ('HOME_NOTICIAS', 'Home de notícias'), ('CATEGORIA', 'Categoria')], db_column='news_destaque_posicao', max_length=24)),
                ('ordem', models.PositiveIntegerField(db_column='news_destaque_ordem', default=0)),
                ('inicio', models.DateTimeField(blank=True, db_column='news_destaque_inicio', null=True)),
                ('fim', models.DateTimeField(blank=True, db_column='news_destaque_fim', null=True)),
                ('ativo', models.BooleanField(db_column='news_destaque_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_destaque_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_destaque_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_destaque_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_destaque_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_destaque', to='news.artigo')),
                ('categoria', models.ForeignKey(blank=True, db_column='news_destaque_fk_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destaques', to='news.categorianoticia')),
            ],
            options={
                'db_table': '"news"."news_destaque_editorial_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEditorial',
            fields=[
                ('id', models.BigAutoField(db_column='news_historico_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_historico_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('status_anterior', models.CharField(blank=True, db_column='news_historico_status_anterior', max_length=24)),
                ('status_novo', models.CharField(blank=True, db_column='news_historico_status_novo', max_length=24)),
                ('acao', models.CharField(db_column='news_historico_acao', max_length=40)),
                ('observacao', models.TextField(blank=True, db_column='news_historico_observacao')),
                ('ativo', models.BooleanField(db_column='news_historico_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_historico_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_historico_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_historico_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_historico_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='historico_editorial', to='news.artigo')),
                ('usuario', models.ForeignKey(blank=True, db_column='news_historico_fk_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"news"."news_historico_editorial_tb"',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPublicacao',
            fields=[
                ('id', models.BigAutoField(db_column='news_imagem_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_imagem_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.ImageField(blank=True, db_column='news_imagem_arquivo', upload_to='news/publicacoes/')),
                ('url_externa', models.URLField(blank=True, db_column='news_imagem_url_externa', max_length=500)),
                ('tipo', models.CharField(choices=[('CAPA', 'Capa'), ('GALERIA', 'Galeria'), ('INFOGRAFICO', 'Infográfico'), ('DOCUMENTO', 'Documento'), ('ILUSTRACAO', 'Ilustração'), ('IMAGEM_EXTERNA', 'Imagem externa')], db_column='news_imagem_tipo', default='GALERIA', max_length=20)),
                ('titulo', models.CharField(blank=True, db_column='news_imagem_titulo', max_length=180)),
                ('legenda', models.TextField(blank=True, db_column='news_imagem_legenda')),
                ('texto_alternativo', models.CharField(db_column='news_imagem_texto_alternativo', max_length=250)),
                ('credito', models.CharField(db_column='news_imagem_credito', max_length=180)),
                ('autor_imagem', models.CharField(blank=True, db_column='news_imagem_autor', max_length=180)),
                ('fonte', models.CharField(blank=True, db_column='news_imagem_fonte', max_length=180)),
                ('url_fonte', models.URLField(blank=True, db_column='news_imagem_url_fonte', max_length=500)),
                ('licenca', models.CharField(choices=[('PROPRIA', 'Própria'), ('CEDIDA_AUTOR', 'Cedida pelo autor'), ('ASSESSORIA', 'Assessoria'), ('DOMINIO_PUBLICO', 'Domínio público'), ('CREATIVE_COMMONS', 'Creative Commons'), ('BANCO_LICENCIADO', 'Banco licenciado'), ('USO_AUTORIZADO', 'Uso autorizado'), ('FONTE_EXTERNA', 'Fonte externa'), ('DESCONHECIDA', 'Desconhecida')], db_column='news_imagem_licenca', max_length=24)),
                ('url_licenca', models.URLField(blank=True, db_column='news_imagem_url_licenca', max_length=500)),
                ('ordem', models.PositiveIntegerField(db_column='news_imagem_ordem', default=0)),
                ('capa', models.BooleanField(db_column='news_imagem_capa', default=False)),
                ('direitos_confirmados', models.BooleanField(db_column='news_imagem_direitos_confirmados', default=False)),
                ('ativo', models.BooleanField(db_column='news_imagem_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_imagem_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_imagem_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_imagem_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_imagem_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='news.artigo')),
            ],
            options={
                'db_table': '"news"."news_imagem_publicacao_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LinkRelacionado',
            fields=[
                ('id', models.BigAutoField(db_column='news_link_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_link_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('SITE', 'Site'), ('REDE_SOCIAL', 'Rede social'), ('YOUTUBE', 'YouTube'), ('DOCUMENTO', 'Documento'), ('REFERENCIA', 'Referência'), ('FONTE', 'Fonte'), ('LINK_OFICIAL', 'Link oficial')], db_column='news_link_tipo', max_length=20)),
                ('rede', models.CharField(choices=[('SITE', 'Site'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TIKTOK', 'TikTok'), ('X', 'X'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('YOUTUBE', 'YouTube'), ('OUTRO', 'Outro')], db_column='news_link_rede', default='SITE', max_length=20)),
                ('titulo', models.CharField(db_column='news_link_titulo', max_length=180)),
                ('url', models.URLField(db_column='news_link_url', max_length=500)),
                ('identificador_externo', models.CharField(blank=True, db_column='news_link_identificador', max_length=120)),
                ('nofollow', models.BooleanField(db_column='news_link_nofollow', default=True)),
                ('ordem', models.PositiveIntegerField(db_column='news_link_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_link_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_link_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_link_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_link_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_link_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='links_relacionados', to='news.artigo')),
            ],
            options={
                'db_table': '"news"."news_link_relacionado_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MidiaIncorporada',
            fields=[
                ('id', models.BigAutoField(db_column='news_midia_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_midia_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('YUBOTUKA', 'YuBotuka')], db_column='news_midia_tipo', default='YOUTUBE', max_length=20)),
                ('titulo', models.CharField(blank=True, db_column='news_midia_titulo', max_length=180)),
                ('url', models.URLField(blank=True, db_column='news_midia_url', max_length=500)),
                ('identificador_externo', models.CharField(blank=True, db_column='news_midia_identificador', max_length=120)),
                ('ordem', models.PositiveIntegerField(db_column='news_midia_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='news_midia_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_midia_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_midia_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_midia_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_midia_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='news.artigo')),
                ('episodio', models.ForeignKey(blank=True, db_column='news_midia_fk_episodio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_news', to='media.episodio')),
            ],
            options={
                'db_table': '"news"."news_midia_incorporada_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='serie',
            field=models.ForeignKey(blank=True, db_column='news_artigo_fk_serie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='news.serieeditorial'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='"news"."news_artigo_tag_tb"', related_name='artigos', to='news.tag'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='temas',
            field=models.ManyToManyField(blank=True, db_table='"news"."news_artigo_tema_tb"', related_name='artigos', to='news.tema'),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['status', 'agendado_para'], name='news_artigo_agenda_idx'),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['autor_editorial', 'status'], name='news_artigo_autor_ed_idx'),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['destaque', 'publicado_em'], name='news_artigo_destaque_idx'),
        ),
        migrations.AddIndex(
            model_name='destaqueeditorial',
            index=models.Index(fields=['posicao', 'inicio', 'fim'], name='news_destaque_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagempublicacao',
            constraint=models.CheckConstraint(condition=models.Q(('arquivo__gt', ''), ('url_externa__gt', ''), _connector='OR'), name='news_imagem_origem_ck'),
        ),
        migrations.RunPython(preparar_base_editorial, reverter_base_editorial),
    ]
