# Generated by Django 6.0.5 on 2026-07-27 13:08

from django.db import migrations


def migrar_status(apps, schema_editor):
    Artigo = apps.get_model("news", "Artigo")
    Artigo.objects.filter(status="PAUSADO").update(status="DESPUBLICADO")


def reverter_status(apps, schema_editor):
    Artigo = apps.get_model("news", "Artigo")
    Artigo.objects.filter(status="DESPUBLICADO").update(status="PAUSADO")


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_editorial_foundation'),
    ]

    operations = [migrations.RunPython(migrar_status, reverter_status)]
