# Generated by Django 6.0.5 on 2026-07-27 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_migrate_paused_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='temas',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='especialidades',
        ),
        migrations.CreateModel(
            name='ArtigoTag',
            fields=[
                ('id', models.BigAutoField(db_column='news_artigo_tag_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_artigo_tag_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(db_column='news_artigo_tag_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_artigo_tag_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_artigo_tag_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_artigo_tag_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_artigo_tag_fk_artigo', on_delete=django.db.models.deletion.CASCADE, to='news.artigo')),
                ('tag', models.ForeignKey(db_column='news_artigo_tag_fk_tag', on_delete=django.db.models.deletion.PROTECT, to='news.tag')),
            ],
            options={
                'db_table': '"news"."news_artigo_tag_rel_tb"',
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artigos', through='news.ArtigoTag', to='news.tag'),
        ),
        migrations.CreateModel(
            name='ArtigoTema',
            fields=[
                ('id', models.BigAutoField(db_column='news_artigo_tema_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_artigo_tema_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(db_column='news_artigo_tema_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_artigo_tema_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_artigo_tema_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_artigo_tema_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_artigo_tema_fk_artigo', on_delete=django.db.models.deletion.CASCADE, to='news.artigo')),
                ('tema', models.ForeignKey(db_column='news_artigo_tema_fk_tema', on_delete=django.db.models.deletion.PROTECT, to='news.tema')),
            ],
            options={
                'db_table': '"news"."news_artigo_tema_rel_tb"',
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='temas',
            field=models.ManyToManyField(blank=True, related_name='artigos', through='news.ArtigoTema', to='news.tema'),
        ),
        migrations.CreateModel(
            name='AutorEspecialidade',
            fields=[
                ('id', models.BigAutoField(db_column='news_autor_especialidade_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_autor_especialidade_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(db_column='news_autor_especialidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_autor_especialidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_autor_especialidade_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_autor_especialidade_excluido_em', null=True)),
                ('autor', models.ForeignKey(db_column='news_autor_especialidade_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='news.autor')),
                ('especialidade', models.ForeignKey(db_column='news_autor_especialidade_fk_especialidade', on_delete=django.db.models.deletion.PROTECT, to='news.especialidadeautor')),
            ],
            options={
                'db_table': '"news"."news_autor_especialidade_rel_tb"',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='autores', through='news.AutorEspecialidade', to='news.especialidadeautor'),
        ),
        migrations.AddConstraint(
            model_name='artigotag',
            constraint=models.UniqueConstraint(fields=('artigo', 'tag'), name='news_artigo_tag_uk'),
        ),
        migrations.AddConstraint(
            model_name='artigotema',
            constraint=models.UniqueConstraint(fields=('artigo', 'tema'), name='news_artigo_tema_uk'),
        ),
        migrations.AddConstraint(
            model_name='autorespecialidade',
            constraint=models.UniqueConstraint(fields=('autor', 'especialidade'), name='news_autor_especialidade_uk'),
        ),
    ]
