# Generated by Django 6.0.5 on 2026-07-28 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_explicit_editorial_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='comentarios_encerrados',
            field=models.BooleanField(db_column='news_artigo_comentarios_encerrados', default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='comentarios_moderados',
            field=models.BooleanField(db_column='news_artigo_comentarios_moderados', default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='comentarios_permitidos',
            field=models.BooleanField(db_column='news_artigo_comentarios_permitidos', default=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='fonte_imagem',
            field=models.CharField(blank=True, db_column='news_artigo_fonte_imagem', max_length=180),
        ),
        migrations.AddField(
            model_name='artigo',
            name='legenda_imagem',
            field=models.CharField(blank=True, db_column='news_artigo_legenda_imagem', max_length=280),
        ),
        migrations.AddField(
            model_name='artigo',
            name='texto_alternativo_imagem',
            field=models.CharField(blank=True, db_column='news_artigo_alt_imagem', max_length=220),
        ),
        migrations.CreateModel(
            name='ComentarioArtigo',
            fields=[
                ('id', models.BigAutoField(db_column='news_comentario_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='news_comentario_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('texto', models.TextField(db_column='news_comentario_texto', max_length=1000)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PUBLICADO', 'Publicado'), ('OCULTO', 'Oculto'), ('REJEITADO', 'Rejeitado')], db_column='news_comentario_status', default='PUBLICADO', max_length=12)),
                ('moderado_em', models.DateTimeField(blank=True, db_column='news_comentario_moderado_em', null=True)),
                ('motivo_moderacao', models.CharField(blank=True, db_column='news_comentario_motivo', max_length=500)),
                ('editado_em', models.DateTimeField(blank=True, db_column='news_comentario_editado_em', null=True)),
                ('ativo', models.BooleanField(db_column='news_comentario_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_comentario_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='news_comentario_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='news_comentario_excluido_em', null=True)),
                ('artigo', models.ForeignKey(db_column='news_comentario_fk_artigo', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='news.artigo')),
                ('comentario_raiz', models.ForeignKey(blank=True, db_column='news_comentario_fk_raiz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='news.comentarioartigo')),
                ('moderado_por', models.ForeignKey(blank=True, db_column='news_comentario_fk_moderador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_news_moderados', to=settings.AUTH_USER_MODEL)),
                ('respondendo_a', models.ForeignKey(blank=True, db_column='news_comentario_fk_respondido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_diretas', to='news.comentarioartigo')),
                ('usuario', models.ForeignKey(db_column='news_comentario_fk_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_news', to=settings.AUTH_USER_MODEL)),
                ('usuario_mencionado', models.ForeignKey(blank=True, db_column='news_comentario_fk_mencionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mencoes_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"news"."news_comentario_artigo_tb"',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CurtidaComentario',
            fields=[
                ('id', models.BigAutoField(db_column='news_curtida_comentario_id', primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_curtida_criado_em')),
                ('comentario', models.ForeignKey(db_column='news_curtida_fk_comentario', on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='news.comentarioartigo')),
                ('usuario', models.ForeignKey(db_column='news_curtida_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_comentarios_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"news"."news_curtida_comentario_tb"',
            },
        ),
        migrations.CreateModel(
            name='DenunciaComentario',
            fields=[
                ('id', models.BigAutoField(db_column='news_denuncia_comentario_id', primary_key=True, serialize=False)),
                ('motivo', models.CharField(db_column='news_denuncia_motivo', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='news_denuncia_criado_em')),
                ('comentario', models.ForeignKey(db_column='news_denuncia_fk_comentario', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='news.comentarioartigo')),
                ('usuario', models.ForeignKey(db_column='news_denuncia_fk_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_comentarios_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"news"."news_denuncia_comentario_tb"',
            },
        ),
        migrations.AddIndex(
            model_name='comentarioartigo',
            index=models.Index(fields=['artigo', 'status', 'criado_em'], name='news_coment_art_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='curtidacomentario',
            constraint=models.UniqueConstraint(fields=('comentario', 'usuario'), name='news_curtida_comentario_uk'),
        ),
        migrations.AddConstraint(
            model_name='denunciacomentario',
            constraint=models.UniqueConstraint(fields=('comentario', 'usuario'), name='news_denuncia_comentario_uk'),
        ),
    ]
