# Generated by Django 6.0.6 on 2026-07-10 13:16

import apps.accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(db_column='platform_usuario_id', primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/%Y/%m/', verbose_name='foto')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': '"platform"."platform_usuario_tb"',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', apps.accounts.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(db_column='platform_usuario_grupo_id', primary_key=True, serialize=False)),
                ('grupo', models.ForeignKey(db_column='platform_grupo_fk', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('usuario', models.ForeignKey(db_column='platform_usuario_fk', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo do usuário',
                'verbose_name_plural': 'grupos dos usuários',
                'db_table': '"platform"."platform_usuario_grupo_tb"',
                'ordering': ['usuario__username', 'grupo__name'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', through='accounts.UsuarioGrupo', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='UsuarioPermissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(db_column='platform_usuario_permissao_id', primary_key=True, serialize=False)),
                ('permissao', models.ForeignKey(db_column='platform_permissao_fk', on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('usuario', models.ForeignKey(db_column='platform_usuario_fk', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permissão do usuário',
                'verbose_name_plural': 'permissões dos usuários',
                'db_table': '"platform"."platform_usuario_permissao_tb"',
                'ordering': ['usuario__username', 'permissao__codename'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', through='accounts.UsuarioPermissao', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='usuariogrupo',
            index=models.Index(fields=['usuario', 'grupo'], name='platform_user_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariogrupo',
            constraint=models.UniqueConstraint(fields=('usuario', 'grupo'), name='platform_usuario_grupo_uk'),
        ),
        migrations.AddIndex(
            model_name='usuariopermissao',
            index=models.Index(fields=['usuario', 'permissao'], name='platform_user_perm_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariopermissao',
            constraint=models.UniqueConstraint(fields=('usuario', 'permissao'), name='platform_usuario_permissao_uk'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['uuid'], name='platform_usuario_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='platform_usuario_email_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['ativo'], name='platform_usuario_ativo_idx'),
        ),
    ]
