# Generated by Django 6.0.6 on 2026-07-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='platform_usuario_ativo_idx',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='platform_usuario_perfil_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.perfil', verbose_name='perfil'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='platform_usuario_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['perfil'], name='platform_usuario_perfil_idx'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
    ]
