# Generated by Django 6.0.6 on 2026-07-10 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_platform_usuario_ativo_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_contatoinstitucional'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, verbose_name='biografia curta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, db_column='platform_usuario_cidade_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='locations.cidade', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='platform_usuario_estado_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='locations.estado', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome de exibição'),
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(db_column='platform_usuario_perfil_adicional_id', primary_key=True, serialize=False)),
                ('perfil', models.ForeignKey(db_column='platform_perfil_fk', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfis_adicionais', to='core.perfil')),
                ('usuario', models.ForeignKey(db_column='platform_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfis_adicionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil adicional do usuário',
                'verbose_name_plural': 'perfis adicionais dos usuários',
                'db_table': '"platform"."platform_usuario_perfil_adicional_tb"',
                'ordering': ['usuario__username', 'perfil__nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfis_adicionais',
            field=models.ManyToManyField(blank=True, related_name='usuarios_adicionais', through='accounts.UsuarioPerfil', to='core.perfil', verbose_name='perfis adicionais'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cpf'], name='platform_usuario_cpf_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cidade'], name='platform_usuario_cidade_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioperfil',
            index=models.Index(fields=['usuario', 'perfil'], name='platform_user_perfil_adic_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuarioperfil',
            constraint=models.UniqueConstraint(fields=('usuario', 'perfil'), name='platform_usuario_perfil_adic_uk'),
        ),
    ]
