# Generated by Django 6.0.5 on 2026-07-26 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_dados_contratante'),
        ('core', '0005_permissao_criticidade_permissao_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaPermissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('CONCEDER', 'Conceder'), ('REVOGAR', 'Revogar')], max_length=12)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('justificativa', models.TextField()),
                ('estado_anterior', models.JSONField(default=dict)),
                ('estado_posterior', models.JSONField(default=dict)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_permissao_executadas', to=settings.AUTH_USER_MODEL)),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.permissao')),
                ('usuario_beneficiado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_permissao_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConcessaoPermissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('concedida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessoes_usuarios', to='core.permissao')),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_revogadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessoes_permissao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', 'permissao__codigo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revogada_em__isnull', True)), fields=('usuario', 'permissao'), name='accounts_concessao_ativa_uk')],
            },
        ),
    ]
