# Generated by Django 6.0.6 on 2026-07-10 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_categoria_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, max_length=80, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': '"platform"."platform_categoria_tb"',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['slug'], name='platform_categoria_slug_idx'), models.Index(fields=['nome'], name='platform_categoria_nome_idx'), models.Index(fields=['ordem'], name='platform_categoria_ordem_idx'), models.Index(fields=['ativo'], name='platform_categoria_ativo_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_subcategoria_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('categoria', models.ForeignKey(db_column='platform_categoria_fk', on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='taxonomy.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
                'db_table': '"platform"."platform_subcategoria_tb"',
                'ordering': ['categoria__nome', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['categoria', 'slug'], name='platform_subcat_slug_idx'), models.Index(fields=['categoria', 'nome'], name='platform_subcat_nome_idx'), models.Index(fields=['ordem'], name='platform_subcat_ordem_idx'), models.Index(fields=['ativo'], name='platform_subcat_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'nome'), name='platform_subcategoria_nome_uk')],
            },
        ),
    ]
