import uuid
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from apps.core.domain import SoftDeleteMixin, EditorialStatus, texto_sem_html, validar_documento_publico, validar_imagem_publica
from apps.core.utils import gerar_slug_unico

class OrgaoPublico(SoftDeleteMixin):
    class Tipo(models.TextChoices): PREFEITURA='PREFEITURA','Prefeitura'; SECRETARIA='SECRETARIA','Secretaria'; AUTARQUIA='AUTARQUIA','Autarquia'; CONSELHO='CONSELHO','Conselho'; OUTRO='OUTRO','Outro'
    id=models.BigAutoField(primary_key=True,db_column='government_orgao_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_orgao_uuid'); tipo=models.CharField(max_length=20,choices=Tipo.choices,db_column='government_orgao_tipo'); nome=models.CharField(max_length=180,db_column='government_orgao_nome'); sigla=models.CharField(max_length=30,blank=True,db_column='government_orgao_sigla'); slug=models.SlugField(max_length=210,unique=True,blank=True,db_column='government_orgao_slug'); descricao=models.TextField(blank=True,db_column='government_orgao_descricao'); logotipo=models.ImageField(upload_to='government/orgaos/',blank=True,db_column='government_orgao_logotipo'); site_oficial=models.URLField(blank=True,db_column='government_orgao_site'); telefone=models.CharField(max_length=30,blank=True,db_column='government_orgao_telefone'); email=models.EmailField(blank=True,db_column='government_orgao_email'); verificado=models.BooleanField(default=False,db_column='government_orgao_verificado'); ativo=models.BooleanField(default=True,db_column='government_orgao_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_orgao_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_orgao_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_orgao_excluido_em')
    class Meta: db_table='"government"."government_orgao_tb"'; ordering=['nome']
    def clean(self): validar_imagem_publica(self.logotipo)
    def save(self,*a,**kw):
        if not self.slug:self.slug=gerar_slug_unico(self,self.nome)
        self.full_clean();super().save(*a,**kw)
    def __str__(self):return self.nome

class OrgaoUsuario(SoftDeleteMixin):
    class Funcao(models.TextChoices): GESTOR='GESTOR','Gestor'; EDITOR='EDITOR','Editor'; REVISOR='REVISOR','Revisor'
    id=models.BigAutoField(primary_key=True,db_column='government_orgao_usuario_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_orgao_usuario_uuid'); orgao=models.ForeignKey(OrgaoPublico,on_delete=models.CASCADE,related_name='usuarios_vinculados',db_column='government_orgao_usuario_fk_orgao'); usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='orgaos_publicos',db_column='government_orgao_usuario_fk_usuario'); funcao=models.CharField(max_length=20,choices=Funcao.choices,db_column='government_orgao_usuario_funcao'); gestor=models.BooleanField(default=False,db_column='government_orgao_usuario_gestor'); editor=models.BooleanField(default=False,db_column='government_orgao_usuario_editor'); revisor=models.BooleanField(default=False,db_column='government_orgao_usuario_revisor'); pode_publicar=models.BooleanField(default=False,db_column='government_orgao_usuario_publicar'); ativo=models.BooleanField(default=True,db_column='government_orgao_usuario_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_orgao_usuario_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_orgao_usuario_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_orgao_usuario_excluido_em')
    class Meta: db_table='"government"."government_orgao_usuario_tb"'; constraints=[models.UniqueConstraint(fields=['orgao','usuario'],condition=models.Q(ativo=True,excluido_em__isnull=True),name='government_orgao_usuario_uk')]

class AcaoPublica(SoftDeleteMixin):
    class Tipo(models.TextChoices): OBRA='OBRA','Obra'; PROJETO='PROJETO','Projeto'; PROGRAMA='PROGRAMA','Programa'; CAMPANHA='CAMPANHA','Campanha'; AUDIENCIA='AUDIENCIA_PUBLICA','Audiência pública'; EVENTO='EVENTO','Evento'; SERVICO='SERVICO','Serviço'; COMUNICADO='COMUNICADO','Comunicado'; CONSULTA='CONSULTA_PUBLICA','Consulta pública'
    class Situacao(models.TextChoices): PLANEJADA='PLANEJADA','Planejada'; LICITACAO='LICITACAO','Licitação'; AGENDADA='AGENDADA','Agendada'; EM_ANDAMENTO='EM_ANDAMENTO','Em andamento'; CONCLUIDA='CONCLUIDA','Concluída'; ADIADA='ADIADA','Adiada'; CANCELADA='CANCELADA','Cancelada'
    id=models.BigAutoField(primary_key=True,db_column='government_acao_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_acao_uuid'); orgao=models.ForeignKey(OrgaoPublico,on_delete=models.PROTECT,related_name='acoes',db_column='government_acao_fk_orgao'); autor=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='acoes_publicas',db_column='government_acao_fk_autor'); revisor=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='acoes_revisadas',db_column='government_acao_fk_revisor'); publicador=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='acoes_publicadas',db_column='government_acao_fk_publicador'); tipo=models.CharField(max_length=30,choices=Tipo.choices,db_column='government_acao_tipo'); titulo=models.CharField(max_length=220,db_column='government_acao_titulo'); slug=models.SlugField(max_length=250,unique=True,blank=True,db_column='government_acao_slug'); resumo=models.TextField(blank=True,db_column='government_acao_resumo'); descricao=models.TextField(db_column='government_acao_descricao'); objetivo=models.TextField(blank=True,db_column='government_acao_objetivo'); publico_alvo=models.CharField(max_length=220,blank=True,db_column='government_acao_publico_alvo'); local=models.CharField(max_length=220,blank=True,db_column='government_acao_local'); bairro=models.CharField(max_length=120,blank=True,db_column='government_acao_bairro'); cidade=models.CharField(max_length=120,db_column='government_acao_cidade'); inicio_previsto=models.DateField(null=True,blank=True,db_column='government_acao_inicio_previsto'); conclusao_prevista=models.DateField(null=True,blank=True,db_column='government_acao_conclusao_prevista'); situacao=models.CharField(max_length=20,choices=Situacao.choices,default=Situacao.PLANEJADA,db_column='government_acao_situacao'); status=models.CharField(max_length=20,choices=EditorialStatus.choices,default=EditorialStatus.RASCUNHO,db_column='government_acao_status'); motivo_rejeicao=models.TextField(blank=True,db_column='government_acao_motivo_rejeicao'); imagem=models.ImageField(upload_to='government/acoes/',blank=True,db_column='government_acao_imagem'); destaque=models.BooleanField(default=False,db_column='government_acao_destaque'); revisado_em=models.DateTimeField(null=True,blank=True,db_column='government_acao_revisado_em'); publicado_em=models.DateTimeField(null=True,blank=True,db_column='government_acao_publicado_em'); ativo=models.BooleanField(default=True,db_column='government_acao_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_acao_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_acao_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_acao_excluido_em')
    class Meta: db_table='"government"."government_acao_tb"'; indexes=[models.Index(fields=['status','publicado_em'],name='government_acao_status_idx')]
    def clean(self):
        self.descricao=texto_sem_html(self.descricao)
        validar_imagem_publica(self.imagem)
        if self.inicio_previsto and self.conclusao_prevista and self.conclusao_prevista<self.inicio_previsto:raise ValidationError({'conclusao_prevista':'A conclusão deve ser posterior ao início.'})
        if self.status==EditorialStatus.PUBLICADO and not self.orgao.verificado:raise ValidationError({'status':'Somente órgãos verificados podem publicar.'})
    def save(self,*a,**kw):
        if not self.slug:self.slug=gerar_slug_unico(self,self.titulo)
        if self.status==EditorialStatus.PUBLICADO and not self.publicado_em:self.publicado_em=timezone.now()
        self.full_clean();super().save(*a,**kw)
    def __str__(self):return self.titulo

class AcaoAtualizacao(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='government_atualizacao_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_atualizacao_uuid'); acao=models.ForeignKey(AcaoPublica,on_delete=models.CASCADE,related_name='atualizacoes',db_column='government_atualizacao_fk_acao'); titulo=models.CharField(max_length=180,db_column='government_atualizacao_titulo'); descricao=models.TextField(db_column='government_atualizacao_descricao'); percentual=models.PositiveSmallIntegerField(null=True,blank=True,db_column='government_atualizacao_percentual'); data=models.DateField(db_column='government_atualizacao_data'); imagem=models.ImageField(upload_to='government/atualizacoes/',blank=True,db_column='government_atualizacao_imagem'); autor=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='atualizacoes_publicas',db_column='government_atualizacao_fk_autor'); ordem=models.PositiveIntegerField(default=0,db_column='government_atualizacao_ordem'); ativo=models.BooleanField(default=True,db_column='government_atualizacao_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_atualizacao_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_atualizacao_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_atualizacao_excluido_em')
    class Meta: db_table='"government"."government_acao_atualizacao_tb"'; ordering=['data','ordem']
    def clean(self):
        if self.percentual is not None and self.percentual>100:raise ValidationError({'percentual':'Use um percentual entre 0 e 100.'})
        validar_imagem_publica(self.imagem)
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)

class AcaoDocumento(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='government_documento_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_documento_uuid'); acao=models.ForeignKey(AcaoPublica,on_delete=models.CASCADE,related_name='documentos',db_column='government_documento_fk_acao'); titulo=models.CharField(max_length=180,db_column='government_documento_titulo'); tipo=models.CharField(max_length=30,db_column='government_documento_tipo'); arquivo=models.FileField(upload_to='government/documentos/%Y/%m/',db_column='government_documento_arquivo'); ordem=models.PositiveIntegerField(default=0,db_column='government_documento_ordem'); ativo=models.BooleanField(default=True,db_column='government_documento_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_documento_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_documento_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_documento_excluido_em')
    class Meta: db_table='"government"."government_acao_documento_tb"'
    def clean(self):
        validar_documento_publico(self.arquivo)
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)

class AcaoLink(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='government_link_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='government_link_uuid'); acao=models.ForeignKey(AcaoPublica,on_delete=models.CASCADE,related_name='links',db_column='government_link_fk_acao'); titulo=models.CharField(max_length=180,db_column='government_link_titulo'); url=models.URLField(max_length=500,db_column='government_link_url'); tipo=models.CharField(max_length=30,blank=True,db_column='government_link_tipo'); ordem=models.PositiveIntegerField(default=0,db_column='government_link_ordem'); ativo=models.BooleanField(default=True,db_column='government_link_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='government_link_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='government_link_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='government_link_excluido_em')
    class Meta: db_table='"government"."government_acao_link_tb"'
