import uuid
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from apps.core.domain import SoftDeleteMixin, validar_documento_publico, validar_imagem_publica
from apps.core.utils import gerar_slug_unico

class SlugSave:
    def save(self,*a,**kw):
        if not self.slug:self.slug=gerar_slug_unico(self,self.nome)
        self.full_clean(); super().save(*a,**kw)

class Modalidade(SlugSave,SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_modalidade_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_modalidade_uuid'); nome=models.CharField(max_length=120,db_column='sports_modalidade_nome'); slug=models.SlugField(max_length=150,unique=True,blank=True,db_column='sports_modalidade_slug'); descricao=models.TextField(blank=True,db_column='sports_modalidade_descricao'); icone=models.CharField(max_length=80,blank=True,db_column='sports_modalidade_icone'); imagem=models.ImageField(upload_to='sports/modalidades/',blank=True,validators=[validar_imagem_publica],db_column='sports_modalidade_imagem'); ordem=models.PositiveIntegerField(default=0,db_column='sports_modalidade_ordem'); ativo=models.BooleanField(default=True,db_column='sports_modalidade_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_modalidade_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_modalidade_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_modalidade_excluido_em')
    class Meta: db_table='"sports"."sports_modalidade_tb"'; ordering=['ordem','nome']
    def __str__(self):return self.nome

class Estilo(SlugSave,SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_estilo_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_estilo_uuid'); modalidade=models.ForeignKey(Modalidade,on_delete=models.PROTECT,related_name='estilos',db_column='sports_estilo_fk_modalidade'); nome=models.CharField(max_length=120,db_column='sports_estilo_nome'); slug=models.SlugField(max_length=160,unique=True,blank=True,db_column='sports_estilo_slug'); descricao=models.TextField(blank=True,db_column='sports_estilo_descricao'); ativo=models.BooleanField(default=True,db_column='sports_estilo_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_estilo_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_estilo_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_estilo_excluido_em')
    class Meta: db_table='"sports"."sports_estilo_tb"'; constraints=[models.UniqueConstraint(fields=['modalidade','nome'],condition=models.Q(ativo=True,excluido_em__isnull=True),name='sports_estilo_modal_nome_uk')]
    def __str__(self):return self.nome

class Categoria(SlugSave,SoftDeleteMixin):
    class Genero(models.TextChoices): FEMININO='FEMININO','Feminino'; MASCULINO='MASCULINO','Masculino'; MISTO='MISTO','Misto'; LIVRE='LIVRE','Livre'
    id=models.BigAutoField(primary_key=True,db_column='sports_categoria_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_categoria_uuid'); modalidade=models.ForeignKey(Modalidade,on_delete=models.PROTECT,null=True,blank=True,related_name='categorias',db_column='sports_categoria_fk_modalidade'); estilo=models.ForeignKey(Estilo,on_delete=models.PROTECT,null=True,blank=True,related_name='categorias',db_column='sports_categoria_fk_estilo'); categoria_pai=models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True,related_name='filhas',db_column='sports_categoria_fk_pai'); nome=models.CharField(max_length=100,db_column='sports_categoria_nome'); slug=models.SlugField(max_length=150,unique=True,blank=True,db_column='sports_categoria_slug'); idade_minima=models.PositiveSmallIntegerField(null=True,blank=True,db_column='sports_categoria_idade_min'); idade_maxima=models.PositiveSmallIntegerField(null=True,blank=True,db_column='sports_categoria_idade_max'); genero=models.CharField(max_length=15,choices=Genero.choices,default=Genero.LIVRE,db_column='sports_categoria_genero'); nivel=models.CharField(max_length=50,blank=True,db_column='sports_categoria_nivel'); ativo=models.BooleanField(default=True,db_column='sports_categoria_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_categoria_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_categoria_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_categoria_excluido_em')
    class Meta: db_table='"sports"."sports_categoria_tb"'
    def clean(self):
        if self.idade_minima is not None and self.idade_maxima is not None and self.idade_maxima<self.idade_minima: raise ValidationError({'idade_maxima':'A idade máxima deve ser maior ou igual à mínima.'})
        if self.estilo_id and self.modalidade_id and self.estilo.modalidade_id != self.modalidade_id: raise ValidationError({'estilo':'O estilo deve pertencer à modalidade informada.'})
        if self.categoria_pai_id and self.categoria_pai_id == self.pk: raise ValidationError({'categoria_pai':'A categoria não pode ser pai de si mesma.'})
        if self.categoria_pai_id:
            pai = self.categoria_pai
            if self.modalidade_id and pai.modalidade_id and pai.modalidade_id != self.modalidade_id: raise ValidationError({'categoria_pai':'A categoria pai deve pertencer à mesma modalidade.'})
            if self.estilo_id and pai.estilo_id and pai.estilo_id != self.estilo_id: raise ValidationError({'categoria_pai':'A categoria pai deve pertencer ao mesmo estilo.'})
            visitados = {self.pk} if self.pk else set()
            while pai:
                if pai.pk in visitados: raise ValidationError({'categoria_pai':'A hierarquia de categorias contém um ciclo.'})
                visitados.add(pai.pk)
                pai = pai.categoria_pai
    def __str__(self):return self.nome

class OrganizacaoEsportiva(SlugSave,SoftDeleteMixin):
    class Tipo(models.TextChoices): CLUBE='CLUBE','Clube'; ASSOCIACAO='ASSOCIACAO','Associação'; ACADEMIA='ACADEMIA','Academia'; PROJETO='PROJETO','Projeto social'; ESCOLA='ESCOLA','Escola esportiva'; LIGA='LIGA','Liga'; INDEPENDENTE='INDEPENDENTE','Independente'
    id=models.BigAutoField(primary_key=True,db_column='sports_organizacao_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_organizacao_uuid'); empresa=models.ForeignKey('organizations.Empresa',on_delete=models.SET_NULL,null=True,blank=True,related_name='organizacoes_esportivas',db_column='sports_organizacao_fk_empresa'); usuario_responsavel=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name='organizacoes_esportivas',db_column='sports_organizacao_fk_usuario'); tipo=models.CharField(max_length=20,choices=Tipo.choices,db_column='sports_organizacao_tipo'); nome=models.CharField(max_length=160,db_column='sports_organizacao_nome'); slug=models.SlugField(max_length=190,unique=True,blank=True,db_column='sports_organizacao_slug'); descricao=models.TextField(blank=True,db_column='sports_organizacao_descricao'); logotipo=models.ImageField(upload_to='sports/organizacoes/',blank=True,validators=[validar_imagem_publica],db_column='sports_organizacao_logotipo'); cidade=models.CharField(max_length=120,db_column='sports_organizacao_cidade'); bairro=models.CharField(max_length=120,blank=True,db_column='sports_organizacao_bairro'); endereco_publico=models.CharField(max_length=220,blank=True,db_column='sports_organizacao_endereco'); telefone=models.CharField(max_length=30,blank=True,db_column='sports_organizacao_telefone'); whatsapp=models.CharField(max_length=30,blank=True,db_column='sports_organizacao_whatsapp'); email_publico=models.EmailField(blank=True,db_column='sports_organizacao_email'); site=models.URLField(blank=True,db_column='sports_organizacao_site'); verificado=models.BooleanField(default=False,db_column='sports_organizacao_verificado'); ativo=models.BooleanField(default=True,db_column='sports_organizacao_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_organizacao_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_organizacao_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_organizacao_excluido_em')
    class Meta: db_table='"sports"."sports_organizacao_esportiva_tb"'
    def __str__(self):return self.nome

class Equipe(SlugSave,SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_equipe_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_equipe_uuid'); organizacao=models.ForeignKey(OrganizacaoEsportiva,on_delete=models.CASCADE,related_name='equipes',db_column='sports_equipe_fk_organizacao'); modalidade=models.ForeignKey(Modalidade,on_delete=models.PROTECT,related_name='equipes',db_column='sports_equipe_fk_modalidade'); estilo=models.ForeignKey(Estilo,on_delete=models.SET_NULL,null=True,blank=True,related_name='equipes',db_column='sports_equipe_fk_estilo'); categoria=models.ForeignKey(Categoria,on_delete=models.SET_NULL,null=True,blank=True,related_name='equipes',db_column='sports_equipe_fk_categoria'); nome=models.CharField(max_length=160,db_column='sports_equipe_nome'); slug=models.SlugField(max_length=190,unique=True,blank=True,db_column='sports_equipe_slug'); escudo=models.ImageField(upload_to='sports/equipes/',blank=True,validators=[validar_imagem_publica],db_column='sports_equipe_escudo'); treinador=models.CharField(max_length=150,blank=True,db_column='sports_equipe_treinador'); cidade=models.CharField(max_length=120,db_column='sports_equipe_cidade'); bairro=models.CharField(max_length=120,blank=True,db_column='sports_equipe_bairro'); ativo=models.BooleanField(default=True,db_column='sports_equipe_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_equipe_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_equipe_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_equipe_excluido_em')
    class Meta: db_table='"sports"."sports_equipe_tb"'; indexes=[models.Index(fields=['organizacao','ativo'],name='sports_equipe_org_ativo_idx')]
    def clean(self):
        if self.estilo_id and self.estilo.modalidade_id != self.modalidade_id: raise ValidationError({'estilo':'O estilo deve pertencer à modalidade da equipe.'})
        if self.categoria_id and self.categoria.modalidade_id and self.categoria.modalidade_id != self.modalidade_id: raise ValidationError({'categoria':'A categoria deve pertencer à modalidade da equipe.'})
        if self.categoria_id and self.categoria.estilo_id and self.categoria.estilo_id != self.estilo_id: raise ValidationError({'categoria':'A categoria deve pertencer ao estilo da equipe.'})
    def __str__(self):return self.nome

class Atleta(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_atleta_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_atleta_uuid'); usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name='perfis_atleta',db_column='sports_atleta_fk_usuario'); equipe=models.ForeignKey(Equipe,on_delete=models.SET_NULL,null=True,blank=True,related_name='atletas',db_column='sports_atleta_fk_equipe'); nome_publico=models.CharField(max_length=160,db_column='sports_atleta_nome'); apelido=models.CharField(max_length=80,blank=True,db_column='sports_atleta_apelido'); foto=models.ImageField(upload_to='sports/atletas/',blank=True,validators=[validar_imagem_publica],db_column='sports_atleta_foto'); modalidade=models.ForeignKey(Modalidade,on_delete=models.PROTECT,related_name='atletas',db_column='sports_atleta_fk_modalidade'); estilo=models.ForeignKey(Estilo,on_delete=models.SET_NULL,null=True,blank=True,related_name='atletas',db_column='sports_atleta_fk_estilo'); categoria=models.ForeignKey(Categoria,on_delete=models.SET_NULL,null=True,blank=True,related_name='atletas',db_column='sports_atleta_fk_categoria'); funcao=models.CharField(max_length=100,blank=True,db_column='sports_atleta_funcao'); numero=models.PositiveSmallIntegerField(null=True,blank=True,db_column='sports_atleta_numero'); biografia=models.TextField(blank=True,db_column='sports_atleta_biografia'); publico=models.BooleanField(default=False,db_column='sports_atleta_publico'); ativo=models.BooleanField(default=True,db_column='sports_atleta_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_atleta_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_atleta_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_atleta_excluido_em')
    class Meta: db_table='"sports"."sports_atleta_tb"'
    def clean(self):
        if self.equipe_id and self.equipe.modalidade_id != self.modalidade_id: raise ValidationError({'equipe':'A equipe deve pertencer à modalidade do atleta.'})
        if self.estilo_id and self.estilo.modalidade_id != self.modalidade_id: raise ValidationError({'estilo':'O estilo deve pertencer à modalidade do atleta.'})
        if self.categoria_id and self.categoria.modalidade_id and self.categoria.modalidade_id != self.modalidade_id: raise ValidationError({'categoria':'A categoria deve pertencer à modalidade do atleta.'})
        if self.categoria_id and self.categoria.estilo_id and self.categoria.estilo_id != self.estilo_id: raise ValidationError({'categoria':'A categoria deve pertencer ao estilo do atleta.'})
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)
    def __str__(self):return self.nome_publico

class Campeonato(SlugSave,SoftDeleteMixin):
    class Status(models.TextChoices): RASCUNHO='RASCUNHO','Rascunho'; INSCRICOES='INSCRICOES','Inscrições'; AGENDADO='AGENDADO','Agendado'; EM_ANDAMENTO='EM_ANDAMENTO','Em andamento'; FINALIZADO='FINALIZADO','Finalizado'; CANCELADO='CANCELADO','Cancelado'
    id=models.BigAutoField(primary_key=True,db_column='sports_campeonato_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_campeonato_uuid'); organizacao=models.ForeignKey(OrganizacaoEsportiva,on_delete=models.PROTECT,related_name='campeonatos',db_column='sports_campeonato_fk_organizacao'); modalidade=models.ForeignKey(Modalidade,on_delete=models.PROTECT,related_name='campeonatos',db_column='sports_campeonato_fk_modalidade'); estilo=models.ForeignKey(Estilo,on_delete=models.SET_NULL,null=True,blank=True,related_name='campeonatos',db_column='sports_campeonato_fk_estilo'); categoria=models.ForeignKey(Categoria,on_delete=models.SET_NULL,null=True,blank=True,related_name='campeonatos',db_column='sports_campeonato_fk_categoria'); nome=models.CharField(max_length=180,db_column='sports_campeonato_nome'); slug=models.SlugField(max_length=210,unique=True,blank=True,db_column='sports_campeonato_slug'); descricao=models.TextField(blank=True,db_column='sports_campeonato_descricao'); regulamento=models.FileField(upload_to='sports/regulamentos/',blank=True,validators=[validar_documento_publico],db_column='sports_campeonato_regulamento'); formato=models.CharField(max_length=80,db_column='sports_campeonato_formato'); data_inicial=models.DateField(db_column='sports_campeonato_data_inicial'); data_final=models.DateField(null=True,blank=True,db_column='sports_campeonato_data_final'); inscricoes_abertas=models.BooleanField(default=False,db_column='sports_campeonato_inscricoes'); inicio_inscricoes=models.DateTimeField(null=True,blank=True,db_column='sports_campeonato_inicio_inscricoes'); fim_inscricoes=models.DateTimeField(null=True,blank=True,db_column='sports_campeonato_fim_inscricoes'); status=models.CharField(max_length=20,choices=Status.choices,default=Status.RASCUNHO,db_column='sports_campeonato_status'); imagem=models.ImageField(upload_to='sports/campeonatos/',blank=True,validators=[validar_imagem_publica],db_column='sports_campeonato_imagem'); localidade=models.CharField(max_length=180,blank=True,db_column='sports_campeonato_localidade'); ativo=models.BooleanField(default=True,db_column='sports_campeonato_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_campeonato_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_campeonato_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_campeonato_excluido_em')
    class Meta: db_table='"sports"."sports_campeonato_tb"'; indexes=[models.Index(fields=['status','data_inicial'],name='sports_campeonato_status_idx')]
    def clean(self):
        if self.data_final and self.data_final<self.data_inicial:raise ValidationError({'data_final':'A data final deve ser posterior à inicial.'})
        if self.estilo_id and self.estilo.modalidade_id != self.modalidade_id: raise ValidationError({'estilo':'O estilo deve pertencer à modalidade do campeonato.'})
        if self.categoria_id and self.categoria.modalidade_id and self.categoria.modalidade_id != self.modalidade_id: raise ValidationError({'categoria':'A categoria deve pertencer à modalidade do campeonato.'})
        if self.categoria_id and self.categoria.estilo_id and self.categoria.estilo_id != self.estilo_id: raise ValidationError({'categoria':'A categoria deve pertencer ao estilo do campeonato.'})
    def __str__(self):return self.nome

class ParticipanteCampeonato(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_participante_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_participante_uuid'); campeonato=models.ForeignKey(Campeonato,on_delete=models.CASCADE,related_name='participantes',db_column='sports_participante_fk_campeonato'); equipe=models.ForeignKey(Equipe,on_delete=models.CASCADE,null=True,blank=True,related_name='participacoes',db_column='sports_participante_fk_equipe'); atleta=models.ForeignKey(Atleta,on_delete=models.CASCADE,null=True,blank=True,related_name='participacoes',db_column='sports_participante_fk_atleta'); ativo=models.BooleanField(default=True,db_column='sports_participante_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_participante_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_participante_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_participante_excluido_em')
    class Meta: db_table='"sports"."sports_campeonato_participante_tb"'; constraints=[models.CheckConstraint(condition=(models.Q(equipe__isnull=False,atleta__isnull=True)|models.Q(equipe__isnull=True,atleta__isnull=False)),name='sports_participante_tipo_ck'),models.UniqueConstraint(fields=['campeonato','equipe'],condition=models.Q(equipe__isnull=False,ativo=True,excluido_em__isnull=True),name='sports_participante_equipe_uk'),models.UniqueConstraint(fields=['campeonato','atleta'],condition=models.Q(atleta__isnull=False,ativo=True,excluido_em__isnull=True),name='sports_participante_atleta_uk')]
    def clean(self):
        if self.equipe_id and self.equipe.modalidade_id != self.campeonato.modalidade_id: raise ValidationError({'equipe':'A equipe deve pertencer à modalidade do campeonato.'})
        if self.atleta_id and self.atleta.modalidade_id != self.campeonato.modalidade_id: raise ValidationError({'atleta':'O atleta deve pertencer à modalidade do campeonato.'})
        if self.equipe_id and self.campeonato.estilo_id and self.equipe.estilo_id != self.campeonato.estilo_id: raise ValidationError({'equipe':'A equipe deve pertencer ao estilo do campeonato.'})
        if self.atleta_id and self.campeonato.estilo_id and self.atleta.estilo_id != self.campeonato.estilo_id: raise ValidationError({'atleta':'O atleta deve pertencer ao estilo do campeonato.'})
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)

class Disputa(SoftDeleteMixin):
    class Status(models.TextChoices): AGENDADA='AGENDADA','Agendada'; EM_ANDAMENTO='EM_ANDAMENTO','Em andamento'; ENCERRADA='ENCERRADA','Encerrada'; ADIADA='ADIADA','Adiada'; CANCELADA='CANCELADA','Cancelada'; WO='WO','W.O.'
    id=models.BigAutoField(primary_key=True,db_column='sports_disputa_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_disputa_uuid'); campeonato=models.ForeignKey(Campeonato,on_delete=models.CASCADE,related_name='disputas',db_column='sports_disputa_fk_campeonato'); fase=models.CharField(max_length=80,blank=True,db_column='sports_disputa_fase'); rodada=models.CharField(max_length=40,blank=True,db_column='sports_disputa_rodada'); tipo=models.CharField(max_length=40,db_column='sports_disputa_tipo'); participante_a=models.ForeignKey(ParticipanteCampeonato,on_delete=models.PROTECT,null=True,blank=True,related_name='disputas_a',db_column='sports_disputa_fk_participante_a'); participante_b=models.ForeignKey(ParticipanteCampeonato,on_delete=models.PROTECT,null=True,blank=True,related_name='disputas_b',db_column='sports_disputa_fk_participante_b'); data_hora=models.DateTimeField(db_column='sports_disputa_data_hora'); local=models.CharField(max_length=180,blank=True,db_column='sports_disputa_local'); status=models.CharField(max_length=20,choices=Status.choices,default=Status.AGENDADA,db_column='sports_disputa_status'); placar_a=models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True,db_column='sports_disputa_placar_a'); placar_b=models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True,db_column='sports_disputa_placar_b'); resultado_textual=models.CharField(max_length=220,blank=True,db_column='sports_disputa_resultado'); observacoes=models.TextField(blank=True,db_column='sports_disputa_observacoes'); ativo=models.BooleanField(default=True,db_column='sports_disputa_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_disputa_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_disputa_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_disputa_excluido_em')
    class Meta: db_table='"sports"."sports_disputa_tb"'; indexes=[models.Index(fields=['status','data_hora'],name='sports_disputa_status_idx')]
    def clean(self):
        for field in ('participante_a','participante_b'):
            participant=getattr(self,field,None)
            if participant and participant.campeonato_id != self.campeonato_id: raise ValidationError({field:'O participante deve pertencer ao campeonato da disputa.'})
        if self.participante_a_id and self.participante_a_id == self.participante_b_id: raise ValidationError({'participante_b':'Os participantes devem ser diferentes.'})
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)
    def __str__(self):return f'{self.campeonato} - {self.data_hora}'

class Classificacao(SoftDeleteMixin):
    id=models.BigAutoField(primary_key=True,db_column='sports_classificacao_id'); uuid=models.UUIDField(default=uuid.uuid4,unique=True,editable=False,db_column='sports_classificacao_uuid'); campeonato=models.ForeignKey(Campeonato,on_delete=models.CASCADE,related_name='classificacoes',db_column='sports_classificacao_fk_campeonato'); participante=models.ForeignKey(ParticipanteCampeonato,on_delete=models.CASCADE,related_name='classificacoes',db_column='sports_classificacao_fk_participante'); jogos=models.PositiveIntegerField(default=0,db_column='sports_classificacao_jogos'); vitorias=models.PositiveIntegerField(default=0,db_column='sports_classificacao_vitorias'); empates=models.PositiveIntegerField(default=0,db_column='sports_classificacao_empates'); derrotas=models.PositiveIntegerField(default=0,db_column='sports_classificacao_derrotas'); pontos=models.DecimalField(max_digits=10,decimal_places=2,default=0,db_column='sports_classificacao_pontos'); marcados=models.DecimalField(max_digits=12,decimal_places=2,default=0,db_column='sports_classificacao_marcados'); sofridos=models.DecimalField(max_digits=12,decimal_places=2,default=0,db_column='sports_classificacao_sofridos'); saldo=models.DecimalField(max_digits=12,decimal_places=2,default=0,db_column='sports_classificacao_saldo'); posicao=models.PositiveIntegerField(db_column='sports_classificacao_posicao'); criterios_adicionais=models.JSONField(default=dict,blank=True,db_column='sports_classificacao_criterios'); ativo=models.BooleanField(default=True,db_column='sports_classificacao_ativo'); criado_em=models.DateTimeField(auto_now_add=True,db_column='sports_classificacao_criado_em'); atualizado_em=models.DateTimeField(auto_now=True,db_column='sports_classificacao_atualizado_em'); excluido_em=models.DateTimeField(null=True,blank=True,db_column='sports_classificacao_excluido_em')
    class Meta: db_table='"sports"."sports_classificacao_tb"'; constraints=[models.UniqueConstraint(fields=['campeonato','participante'],condition=models.Q(ativo=True,excluido_em__isnull=True),name='sports_classificacao_part_uk'),models.UniqueConstraint(fields=['campeonato','posicao'],condition=models.Q(ativo=True,excluido_em__isnull=True),name='sports_classificacao_pos_uk')]
    def clean(self):
        if self.participante_id and self.participante.campeonato_id != self.campeonato_id: raise ValidationError({'participante':'O participante deve pertencer ao campeonato da classificação.'})
    def save(self,*a,**kw): self.full_clean(); super().save(*a,**kw)
