# Generated by Django 6.0.5 on 2026-09-12 22:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0023_subcategoriacnae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE SCHEMA IF NOT EXISTS payments;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada'), ('ESTORNADA', 'Estornada')], default='PENDENTE', max_length=16)),
                ('moeda', models.CharField(default='BRL', editable=False, max_length=3)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('vencimento', models.DateTimeField(blank=True, null=True)),
                ('paga_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('estornada_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='organizations.empresa')),
            ],
            options={
                'db_table': '"payments"."payments_cobranca_tb"',
            },
        ),
        migrations.CreateModel(
            name='ItemCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='payments.cobranca')),
            ],
            options={
                'db_table': '"payments"."payments_item_cobranca_tb"',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gateway', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('CRIADO', 'Criado'), ('PROCESSANDO', 'Processando'), ('CONFIRMADO', 'Confirmado'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='CRIADO', max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('referencia_gateway', models.CharField(blank=True, max_length=128)),
                ('confirmado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='payments.cobranca')),
            ],
            options={
                'db_table': '"payments"."payments_pagamento_tb"',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('AUTORIZACAO', 'Autorização'), ('CAPTURA', 'Captura'), ('CANCELAMENTO', 'Cancelamento'), ('ESTORNO', 'Estorno')], max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('referencia_gateway', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sucesso', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='payments.pagamento')),
            ],
            options={
                'db_table': '"payments"."payments_transacao_tb"',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('assinatura_valida', models.BooleanField(default=False)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"payments"."payments_webhook_tb"',
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='pay_webhook_event_uk')],
            },
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'status'], name='pay_cobranca_emp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='pay_cobranca_total_nn_ck'),
        ),
        migrations.AddConstraint(
            model_name='itemcobranca',
            constraint=models.UniqueConstraint(fields=('cobranca', 'codigo'), name='pay_item_cobranca_codigo_uk'),
        ),
        migrations.AddConstraint(
            model_name='itemcobranca',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='pay_item_quantidade_ck'),
        ),
        migrations.AddConstraint(
            model_name='itemcobranca',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='pay_item_valor_ck'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_gateway', ''), _negated=True), fields=('gateway', 'referencia_gateway'), name='pay_gateway_referencia_uk'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pay_pagamento_valor_ck'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pay_transacao_valor_ck'),
        ),
    ]
