# Generated by Django 6.0.5 on 2026-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveIdempotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=128, unique=True)),
                ('operacao', models.CharField(max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaves_idempotencia', to='payments.pagamento')),
            ],
            options={
                'db_table': '"payments"."payments_idempotencia_tb"',
            },
        ),
    ]
