# Generated by Django 6.0.5 on 2026-09-13 01:46

import apps.payments.models
from django.db import migrations, models


def backfill_references(apps, schema_editor):
    Cobranca = apps.get_model('payments', 'Cobranca')
    Pagamento = apps.get_model('payments', 'Pagamento')
    for cobranca in Cobranca.objects.only('pk', 'uuid').iterator():
        Cobranca.objects.filter(pk=cobranca.pk).update(
            external_reference=f'charge:{cobranca.uuid}',
        )
    for pagamento in Pagamento.objects.select_related('cobranca').only(
        'pk', 'uuid', 'cobranca__external_reference',
    ).iterator():
        Pagamento.objects.filter(pk=pagamento.pk).update(
            external_reference=pagamento.cobranca.external_reference,
            idempotency_key=f'legacy:{pagamento.uuid}',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_chaveidempotencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='external_reference',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='origem',
            field=models.CharField(choices=[('PUBLICIDADE', 'Publicidade'), ('MENSALIDADE', 'Mensalidade'), ('PLANO', 'Plano'), ('ASSINATURA', 'Assinatura'), ('COBRANCA_INSTITUCIONAL', 'Cobrança institucional'), ('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('PRESTACAO_SERVICO', 'Prestação de serviço')], default='COBRANCA_INSTITUCIONAL', max_length=32),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='external_reference',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='idempotency_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cobranca',
            name='external_reference',
            field=models.CharField(default=apps.payments.models.default_external_reference, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='external_reference',
            field=models.CharField(default=apps.payments.models.default_external_reference, max_length=128),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='idempotency_key',
            field=models.CharField(default=apps.payments.models.default_idempotency_key, max_length=128, unique=True),
        ),
    ]
