# Generated by Django 6.0.5 on 2026-08-24 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('services', '0008_alter_servico_tipo_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE SCHEMA IF NOT EXISTS agenda;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='AgendaProfissional',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_profissional_id', primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(db_column='agenda_profissional_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_profissional_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_profissional_atualizado_em')),
                ('empresa_usuario', models.OneToOneField(blank=True, db_column='agenda_profissional_fk_empresa_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_profissional', to='organizations.empresausuario')),
                ('usuario_autonomo', models.OneToOneField(blank=True, db_column='agenda_profissional_fk_usuario_autonomo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_profissional_autonomo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"agenda"."agenda_profissional_tb"',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgendaProfissionalServico',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_profissional_servico_id', primary_key=True, serialize=False)),
                ('duracao_minutos', models.PositiveIntegerField(db_column='agenda_profissional_servico_duracao_minutos')),
                ('ativo', models.BooleanField(db_column='agenda_profissional_servico_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_profissional_servico_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_profissional_servico_atualizado_em')),
                ('profissional', models.ForeignKey(db_column='agenda_profissional_servico_fk_profissional', on_delete=django.db.models.deletion.CASCADE, related_name='servicos_vinculados', to='agenda.agendaprofissional')),
                ('servico', models.ForeignKey(db_column='agenda_profissional_servico_fk_servico', on_delete=django.db.models.deletion.PROTECT, related_name='profissionais_agenda', to='services.servico')),
            ],
            options={
                'db_table': '"agenda"."agenda_profissional_servico_tb"',
                'ordering': ['profissional_id', 'servico_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agendaprofissional',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa_usuario__isnull', False), ('usuario_autonomo__isnull', True)), models.Q(('empresa_usuario__isnull', True), ('usuario_autonomo__isnull', False)), _connector='OR'), name='agenda_profissional_contexto_ck'),
        ),
        migrations.AddConstraint(
            model_name='agendaprofissionalservico',
            constraint=models.UniqueConstraint(fields=('profissional', 'servico'), name='agenda_profissional_servico_uk'),
        ),
        migrations.AddConstraint(
            model_name='agendaprofissionalservico',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_minutos__gt', 0)), name='agenda_prof_serv_duracao_ck'),
        ),
    ]
