# Generated by Django 6.0.5 on 2026-08-24 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDisponibilidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_disponibilidade_id', primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], db_column='agenda_disponibilidade_dia_semana')),
                ('hora_inicio', models.TimeField(db_column='agenda_disponibilidade_hora_inicio')),
                ('hora_fim', models.TimeField(db_column='agenda_disponibilidade_hora_fim')),
                ('ativo', models.BooleanField(db_column='agenda_disponibilidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_disponibilidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_disponibilidade_atualizado_em')),
                ('profissional', models.ForeignKey(db_column='agenda_disponibilidade_fk_profissional', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.agendaprofissional')),
            ],
            options={
                'db_table': '"agenda"."agenda_disponibilidade_tb"',
                'ordering': ['profissional_id', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('profissional', 'dia_semana', 'hora_inicio', 'hora_fim'), name='agenda_disponibilidade_uk'), models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='agenda_disponibilidade_horario_ck')],
            },
        ),
    ]
