# Generated by Django 6.0.5 on 2026-08-24 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendadisponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaBloqueio',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_bloqueio_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FOLGA', 'Folga'), ('FERIAS', 'Férias'), ('FERIADO', 'Feriado'), ('PESSOAL', 'Compromisso pessoal'), ('OUTRO', 'Outro')], db_column='agenda_bloqueio_tipo', default='OUTRO', max_length=20)),
                ('inicio', models.DateTimeField(db_column='agenda_bloqueio_inicio')),
                ('fim', models.DateTimeField(db_column='agenda_bloqueio_fim')),
                ('motivo', models.CharField(blank=True, db_column='agenda_bloqueio_motivo', max_length=220)),
                ('ativo', models.BooleanField(db_column='agenda_bloqueio_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_bloqueio_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_bloqueio_atualizado_em')),
                ('profissional', models.ForeignKey(db_column='agenda_bloqueio_fk_profissional', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='agenda.agendaprofissional')),
            ],
            options={
                'db_table': '"agenda"."agenda_bloqueio_tb"',
                'ordering': ['inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agenda_bloqueio_periodo_ck')],
            },
        ),
    ]
