# Generated by Django 6.0.5 on 2026-08-25 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendabloqueio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_agendamento_id', primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(db_column='agenda_agendamento_inicio')),
                ('fim', models.DateTimeField(db_column='agenda_agendamento_fim')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Cliente não compareceu')], db_column='agenda_agendamento_status', default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, db_column='agenda_agendamento_observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_agendamento_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_agendamento_atualizado_em')),
                ('cliente', models.ForeignKey(db_column='agenda_agendamento_fk_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_cliente', to=settings.AUTH_USER_MODEL)),
                ('profissional_servico', models.ForeignKey(db_column='agenda_agendamento_fk_profissional_servico', on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.agendaprofissionalservico')),
            ],
            options={
                'db_table': '"agenda"."agenda_agendamento_tb"',
                'ordering': ['inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agenda_agendamento_periodo_ck')],
            },
        ),
    ]
