# Generated by Django 6.0.5 on 2026-08-28 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_funcionamento(apps, schema_editor):
    Disponibilidade = apps.get_model('agenda', 'AgendaDisponibilidade')
    Funcionamento = apps.get_model('agenda', 'AgendaFuncionamentoEmpresa')
    linhas = Disponibilidade.objects.filter(
        ativo=True,
        profissional__ativo=True,
        profissional__empresa_usuario__ativo=True,
    ).values_list(
        'profissional__empresa_usuario__empresa_id',
        'dia_semana', 'hora_inicio', 'hora_fim',
    ).order_by(
        'profissional__empresa_usuario__empresa_id',
        'dia_semana', 'hora_inicio', 'hora_fim',
    )
    por_chave = {}
    for empresa_id, dia, inicio, fim in linhas:
        if empresa_id is not None:
            por_chave.setdefault((empresa_id, dia), []).append((inicio, fim))
    criados = []
    for (empresa_id, dia), intervalos in por_chave.items():
        consolidados = []
        for inicio, fim in intervalos:
            if consolidados and inicio <= consolidados[-1][1]:
                consolidados[-1] = (consolidados[-1][0], max(fim, consolidados[-1][1]))
            else:
                consolidados.append((inicio, fim))
        criados.extend(Funcionamento(
            empresa_id=empresa_id, dia_semana=dia,
            hora_inicio=inicio, hora_fim=fim, ativo=True,
        ) for inicio, fim in consolidados)
    Funcionamento.objects.bulk_create(criados)
    empresas_processadas = len({empresa_id for empresa_id, _dia in por_chave})
    print(
        f'Agenda funcionamento backfill: empresas_processadas={empresas_processadas}; '
        f'empresas_com_funcionamento={empresas_processadas}; intervalos_criados={len(criados)}'
    )


def reverter_backfill(apps, schema_editor):
    apps.get_model('agenda', 'AgendaFuncionamentoEmpresa').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento'),
        ('organizations', '0017_empresa_cadastro_etapa_e_localizacao_rascunho'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaprofissionalservico',
            name='buffer_antes_minutos',
            field=models.PositiveIntegerField(db_column='agenda_profissional_servico_buffer_antes_minutos', default=0),
        ),
        migrations.AddField(
            model_name='agendaprofissionalservico',
            name='buffer_depois_minutos',
            field=models.PositiveIntegerField(db_column='agenda_profissional_servico_buffer_depois_minutos', default=0),
        ),
        migrations.CreateModel(
            name='AgendaFuncionamentoEmpresa',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_funcionamento_empresa_id', primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], db_column='agenda_funcionamento_empresa_dia_semana')),
                ('hora_inicio', models.TimeField(db_column='agenda_funcionamento_empresa_hora_inicio')),
                ('hora_fim', models.TimeField(db_column='agenda_funcionamento_empresa_hora_fim')),
                ('ativo', models.BooleanField(db_column='agenda_funcionamento_empresa_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_funcionamento_empresa_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_funcionamento_empresa_atualizado_em')),
                ('empresa', models.ForeignKey(db_column='agenda_funcionamento_empresa_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='funcionamentos_agenda', to='organizations.empresa')),
            ],
            options={
                'verbose_name': 'funcionamento da empresa na Agenda',
                'verbose_name_plural': 'funcionamentos das empresas na Agenda',
                'db_table': '"agenda"."agenda_funcionamento_empresa_tb"',
                'ordering': ['empresa_id', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['empresa', 'dia_semana', 'ativo'], name='agenda_func_empresa_dia_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'dia_semana', 'hora_inicio', 'hora_fim'), name='agenda_func_empresa_periodo_uk'), models.CheckConstraint(condition=models.Q(('dia_semana__gte', 0), ('dia_semana__lte', 6)), name='agenda_func_empresa_dia_ck'), models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='agenda_func_empresa_horario_ck')],
            },
        ),
        migrations.RunPython(backfill_funcionamento, reverter_backfill),
    ]
