# Generated by Django 6.0.5 on 2026-08-28 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_funcionamento_empresa_buffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDisponibilidadeData',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_disponibilidade_data_id', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='agenda_disponibilidade_data_data')),
                ('hora_inicio', models.TimeField(db_column='agenda_disponibilidade_data_hora_inicio')),
                ('hora_fim', models.TimeField(db_column='agenda_disponibilidade_data_hora_fim')),
                ('ativo', models.BooleanField(db_column='agenda_disponibilidade_data_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_disponibilidade_data_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_disponibilidade_data_atualizado_em')),
                ('profissional', models.ForeignKey(db_column='agenda_disponibilidade_data_fk_profissional', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_data', to='agenda.agendaprofissional')),
            ],
            options={
                'db_table': '"agenda"."agenda_disponibilidade_data_tb"',
                'ordering': ['profissional_id', 'data', 'hora_inicio'],
                'indexes': [models.Index(fields=['profissional', 'data', 'ativo'], name='agenda_disp_data_prof_idx')],
                'constraints': [models.UniqueConstraint(fields=('profissional', 'data', 'hora_inicio', 'hora_fim'), name='agenda_disponibilidade_data_uk'), models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='agenda_disponibilidade_data_horario_ck')],
            },
        ),
    ]
