# Generated by Django 6.0.5 on 2026-09-03 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agendadisponibilidadedata'),
        ('organizations', '0018_auto_approve_service_capability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEmpresa',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_empresa_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE_CONFIGURACAO', 'Pendente de configuração'), ('FECHADA', 'Fechada'), ('ABERTA', 'Aberta')], db_column='agenda_empresa_status', default='PENDENTE_CONFIGURACAO', max_length=30)),
                ('aberto_em', models.DateTimeField(blank=True, db_column='agenda_empresa_aberto_em', null=True)),
                ('fechado_em', models.DateTimeField(blank=True, db_column='agenda_empresa_fechado_em', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_empresa_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='agenda_empresa_atualizado_em')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='agenda_empresa_fk_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_empresa_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(db_column='agenda_empresa_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='agenda_configuracao', to='organizations.empresa')),
            ],
            options={
                'db_table': '"agenda"."agenda_empresa_tb"',
                'ordering': ['empresa_id'],
            },
        ),
    ]
