# Generated by Django 6.0.5 on 2026-09-03 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agenda', '0007_agenda_empresa_estado_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoHistorico',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='agenda_historico_id', primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('STATUS', 'Status alterado'), ('REAGENDADO', 'Reagendado'), ('CANCELADO', 'Cancelado')], db_column='agenda_historico_acao', max_length=20)),
                ('status_anterior', models.CharField(blank=True, db_column='agenda_historico_status_anterior', max_length=20)),
                ('status_novo', models.CharField(blank=True, db_column='agenda_historico_status_novo', max_length=20)),
                ('inicio_anterior', models.DateTimeField(blank=True, db_column='agenda_historico_inicio_anterior', null=True)),
                ('inicio_novo', models.DateTimeField(blank=True, db_column='agenda_historico_inicio_novo', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='agenda_historico_criado_em')),
                ('agendamento', models.ForeignKey(db_column='agenda_historico_fk_agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='agenda.agendamento')),
                ('realizado_por', models.ForeignKey(blank=True, db_column='agenda_historico_fk_realizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_agendamento_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"agenda"."agenda_agendamento_historico_tb"',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['agendamento', 'criado_em'], name='agenda_hist_agend_data_idx')],
            },
        ),
    ]
