# Generated by Django 6.0.5 on 2026-09-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('agenda', '0008_agendamentohistorico')]

    operations = [
        migrations.AddField(
            model_name='agendaempresa', name='antecedencia_minima_minutos',
            field=models.PositiveIntegerField(db_column='agenda_empresa_antecedencia_minima_minutos', default=0),
        ),
        migrations.AddField(
            model_name='agendaempresa', name='cancelamento_antecedencia_minutos',
            field=models.PositiveIntegerField(db_column='agenda_empresa_cancelamento_antecedencia_minutos', default=0),
        ),
        migrations.AddField(
            model_name='agendaempresa', name='horizonte_maximo_dias',
            field=models.PositiveIntegerField(db_column='agenda_empresa_horizonte_maximo_dias', default=90),
        ),
        migrations.AddField(
            model_name='agendaempresa', name='intervalo_grade_minutos',
            field=models.PositiveIntegerField(db_column='agenda_empresa_intervalo_grade_minutos', default=0),
        ),
    ]
