# Generated by Django 6.0.5 on 2026-07-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismoplaylist',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='turismoplaylist',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='turismoplaylist',
            name='experiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='tourism.experienciaturistica'),
        ),
        migrations.AddField(
            model_name='turismoplaylist',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='tourism.roteiroturistico'),
        ),
    ]
