# Generated by Django 6.0.5 on 2026-07-26 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('tourism', '0003_turismoplaylist_categoria_turismoplaylist_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaturistica',
            name='acessibilidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='capacidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='contato',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='datas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='duracao',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='requisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='alimentacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='banheiros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='empresa_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_turisticos', to='organizations.empresa'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='regras_local',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='seguranca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='custo_estimado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='dificuldade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='guias',
            field=models.ManyToManyField(blank=True, related_name='roteiros', to='tourism.guiaturistico'),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='mapa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='publico_indicado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='turismovideo',
            name='experiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tourism.experienciaturistica'),
        ),
        migrations.AddField(
            model_name='turismovideo',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tourism.roteiroturistico'),
        ),
        migrations.CreateModel(
            name='EmpresaTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('moderado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('PUBLICADO', 'Publicado'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('tipo_atuacao', models.CharField(choices=[('AGENCIA', 'Agência'), ('OPERADORA', 'Operadora'), ('HOSPEDAGEM', 'Hospedagem'), ('GUIA_PJ', 'Guia PJ'), ('TRANSPORTE', 'Transporte turístico'), ('GASTRONOMIA', 'Gastronomia'), ('EVENTOS', 'Eventos'), ('RURAL', 'Turismo rural'), ('EXPERIENCIA', 'Experiência'), ('PASSEIO', 'Passeio'), ('LOCACAO', 'Locação'), ('APOIO', 'Apoio ao turista')], max_length=20)),
                ('apresentacao', models.TextField(blank=True)),
                ('regioes_atendidas', models.CharField(blank=True, max_length=300)),
                ('contato_publico', models.CharField(blank=True, max_length=180)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_turistico', to='organizations.empresa')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_moderados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_publicados', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empresa__nome_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='experienciaturistica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencias', to='tourism.empresaturistica'),
        ),
        migrations.AddField(
            model_name='turismoplaylist',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='tourism.empresaturistica'),
        ),
        migrations.AddField(
            model_name='turismovideo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tourism.empresaturistica'),
        ),
    ]
