# Generated by Django 6.0.5 on 2026-07-26 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def migrar_categorias(apps, schema_editor):
    Categoria = apps.get_model('tourism', 'CategoriaTurismo')
    Local = apps.get_model('tourism', 'LocalTuristico')
    arvore = {
        'Natureza': ('Parque', 'Trilha', 'Cachoeira', 'Mirante'),
        'Cultura e história': ('Museu', 'Igreja', 'Patrimônio histórico'),
        'Lazer': ('Praça', 'Parque urbano', 'Centro de visitação'),
    }
    for ordem, (nome, filhos) in enumerate(arvore.items(), 1):
        pai, _ = Categoria.objects.get_or_create(
            slug=slugify(nome),
            defaults={'nome': nome, 'ordem': ordem},
        )
        for subordem, filho in enumerate(filhos, 1):
            Categoria.objects.get_or_create(
                slug=f'{pai.slug}-{slugify(filho)}',
                defaults={'nome': filho, 'pai': pai, 'ordem': subordem},
            )
    for local in Local.objects.exclude(categoria_legada=''):
        slug = slugify(local.categoria_legada)[:120]
        categoria, _ = Categoria.objects.get_or_create(
            slug=slug, defaults={'nome': local.categoria_legada},
        )
        local.categoria_id = categoria.pk
        local.save(update_fields=['categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_complete_panel_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localturistico',
            name='aceita_animais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_necessario',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='localturistico',
            old_name='categoria',
            new_name='categoria_legada',
        ),
        migrations.AlterField(
            model_name='localturistico',
            name='categoria_legada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='dias_funcionamento',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='duracao_media_visita',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='guias_relacionados',
            field=models.ManyToManyField(blank=True, related_name='locais_relacionados', to='tourism.guiaturistico'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_credito',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_foco_horizontal',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_foco_vertical',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_legenda',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_principal',
            field=models.ImageField(blank=True, upload_to='turismo/locais/capas/'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_principal_webp',
            field=models.ImageField(blank=True, editable=False, upload_to='turismo/locais/capas/webp/'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_texto_alternativo',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='imagem_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='turismo/locais/capas/thumbs/'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='melhor_periodo',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='recomendacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='responsavel_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais_turisticos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='situacao_local',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='credito',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='texto_alternativo',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='turismovideo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CategoriaTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='tourism.categoriaturismo')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='localturistico',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais', to='tourism.categoriaturismo'),
        ),
        migrations.RunPython(migrar_categorias, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ContatoTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('moderado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('PUBLICADO', 'Publicado'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('SITE', 'Site'), ('OUTRO', 'Outro')], max_length=12)),
                ('valor', models.CharField(max_length=240)),
                ('nome_exibicao', models.CharField(blank=True, max_length=100)),
                ('publico', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='tourism.localturistico')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_moderados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_publicados', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocialTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('moderado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('PUBLICADO', 'Publicado'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('tipo', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('LINKEDIN', 'LinkedIn'), ('X', 'X / Twitter'), ('OUTRA', 'Outra rede')], max_length=12)),
                ('url', models.URLField()),
                ('nome_exibicao', models.CharField(blank=True, max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais_itens', to='tourism.localturistico')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_moderados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_publicados', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'tipo'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaturismo',
            constraint=models.UniqueConstraint(fields=('pai', 'nome'), name='tourism_categoria_pai_nome_uk'),
        ),
    ]
