# Generated by Django 6.0.5 on 2026-07-26 17:59

import django.core.validators
import uuid
from django.db import migrations, models
from django.utils.text import slugify


ESTRUTURAS = (
    'Banheiro', 'Banheiro acessível', 'Estacionamento',
    'Estacionamento para ônibus', 'Acessibilidade para cadeirante',
    'Rampa de acesso', 'Elevador', 'Bebedouro', 'Área de alimentação',
    'Restaurante', 'Lanchonete', 'Wi-Fi', 'Área infantil', 'Fraldário',
    'Área para descanso', 'Loja', 'Guia no local', 'Posto de informação',
    'Segurança', 'Iluminação', 'Aceita animais', 'Área pet', 'Ciclovia',
    'Bicicletário', 'Primeiros socorros',
)
SERVICOS = (
    'Visita guiada', 'Passeio de bicicleta', 'Passeio de barco',
    'Trilha guiada', 'Locação de equipamento', 'Fotografia',
    'Transporte interno', 'Venda de ingressos', 'Loja de lembranças',
    'Alimentação',
)


def seed_catalogos(apps, schema_editor):
    for model_name, values in (
        ('EstruturaTurismo', ESTRUTURAS), ('ServicoTurismo', SERVICOS),
    ):
        Model = apps.get_model('tourism', model_name)
        for ordem, nome in enumerate(values, 1):
            Model.objects.update_or_create(
                slug=slugify(nome), defaults={'nome': nome, 'ordem': ordem, 'ativo': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('tourism', '0006_localturistico_aceita_animais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RunPython(seed_catalogos, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contatoturismo',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_antecedencia_horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_instrucoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='agendamento_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='empresas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='locais_turisticos_relacionados', to='organizations.empresa'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='link_compra',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='valor_infantil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='valor_inteiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='valor_meia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='redesocialturismo',
            name='publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contatoturismo',
            name='tipo',
            field=models.CharField(choices=[('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('SITE', 'Site'), ('AGENDAMENTO', 'Link de agendamento'), ('OUTRO', 'Outro')], max_length=12),
        ),
        migrations.AlterField(
            model_name='localturistico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='localturistico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='redesocialturismo',
            name='tipo',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('LINKEDIN', 'LinkedIn'), ('X', 'X / Twitter'), ('PINTEREST', 'Pinterest'), ('OUTRA', 'Outra rede')], max_length=12),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='estruturas',
            field=models.ManyToManyField(blank=True, related_name='locais', to='tourism.estruturaturismo'),
        ),
        migrations.AddField(
            model_name='localturistico',
            name='servicos_disponiveis',
            field=models.ManyToManyField(blank=True, related_name='locais', to='tourism.servicoturismo'),
        ),
    ]
