# Generated by Django 6.0.5 on 2026-07-26 18:04

from django.db import migrations, models


def normalizar_opcoes(apps, schema_editor):
    Local = apps.get_model('tourism', 'LocalTuristico')
    Local.objects.exclude(
        situacao_local__in=['', 'ABERTO', 'TEMP_FECHADO', 'MANUTENCAO', 'SAZONAL'],
    ).update(situacao_local='')
    Local.objects.exclude(
        precisao__in=['', 'EXATA', 'ESTIMADA', 'APROXIMADA'],
    ).update(precisao='')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tourism', '0007_estruturaturismo_servicoturismo_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_opcoes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='localturistico',
            name='precisao',
            field=models.CharField(blank=True, choices=[('EXATA', 'Coordenada exata'), ('ESTIMADA', 'Coordenada estimada'), ('APROXIMADA', 'Somente região aproximada')], max_length=12),
        ),
        migrations.AlterField(
            model_name='localturistico',
            name='situacao_local',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto à visitação'), ('TEMP_FECHADO', 'Temporariamente fechado'), ('MANUTENCAO', 'Em manutenção'), ('SAZONAL', 'Funcionamento sazonal')], max_length=16),
        ),
    ]
