# Generated by Django 6.0.5 on 2026-07-30 02:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('nome', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=80)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(max_length=120)),
                ('subcategoria', models.CharField(blank=True, max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('condicao', models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('RECONDICIONADO', 'Recondicionado')], default='NOVO', max_length=20)),
                ('descricao_curta', models.CharField(max_length=300)),
                ('descricao_completa', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('preco_sob_consulta', models.BooleanField(default=False)),
                ('unidade_venda', models.CharField(default='unidade', max_length=80)),
                ('quantidade_minima', models.PositiveIntegerField(default=1)),
                ('estoque_informativo', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibilidade', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('SOB_ENCOMENDA', 'Sob encomenda'), ('ESGOTADO', 'Esgotado'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20)),
                ('aceita_encomenda', models.BooleanField(default=False)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('url_externa', models.URLField(blank=True, max_length=500)),
                ('dimensoes', models.CharField(blank=True, max_length=160)),
                ('peso', models.CharField(blank=True, max_length=80)),
                ('cor', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('tamanho', models.CharField(blank=True, max_length=80)),
                ('especificacoes', models.TextField(blank=True)),
                ('garantia', models.TextField(blank=True)),
                ('prazo_estimado', models.CharField(blank=True, max_length=120)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('fabricante', models.CharField(blank=True, max_length=160)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('imagem_social', models.ImageField(blank=True, upload_to='produtos/social/')),
                ('titulo_seo', models.CharField(blank=True, max_length=70)),
                ('descricao_seo', models.CharField(blank=True, max_length=160)),
                ('titular_tipo', models.CharField(choices=[('PF', 'Pessoa física'), ('EMPRESA', 'Empresa')], max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado'), ('PAUSADO', 'Pausado'), ('REJEITADO', 'Rejeitado'), ('ESGOTADO', 'Esgotado'), ('INDISPONIVEL', 'Indisponível'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criador_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa_proprietaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='organizations.empresa')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_proprios', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_publicados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('acao', models.CharField(max_length=60)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='products.produto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('imagem', models.ImageField(upload_to='produtos/imagens/%Y/%m/')),
                ('principal', models.BooleanField(default=False)),
                ('legenda', models.CharField(blank=True, max_length=180)),
                ('credito', models.CharField(blank=True, max_length=180)),
                ('texto_alternativo', models.CharField(max_length=220)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='products.produto')),
            ],
            options={
                'ordering': ['-principal', 'ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LimiteProdutoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('adicional', models.PositiveIntegerField(default=0)),
                ('limite_total', models.PositiveIntegerField(blank=True, null=True)),
                ('ilimitado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('concedido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limites_produtos_concedidos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limites_produtos', to='organizations.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limites_produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('usuario__isnull', False)), models.Q(('empresa__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='products_limit_one_owner_ck')],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['status', 'publico'], name='products_public_status_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['proprietario', 'status'], name='products_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa_proprietaria', 'status'], name='products_company_status_idx'),
        ),
    ]
