# Generated by Django 6.0.5 on 2026-07-30 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('products', '0002_seed_product_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('exige_segmento', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SegmentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SetorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AtributoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100)),
                ('chave', models.SlugField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Número inteiro'), ('DECIMAL', 'Número decimal'), ('BOOLEANO', 'Sim ou não'), ('ESCOLHA', 'Escolha')], default='TEXTO', max_length=12)),
                ('opcoes', models.JSONField(blank=True, default=list)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('filtravel', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria_taxonomia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='products.categoriaproduto')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_taxonomia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.categoriaproduto'),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ATIVA', max_length=12)),
                ('ultima_interacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('bloqueada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=255)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas_comprador', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversas_produtos', to='organizations.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to='products.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_interacao'],
            },
        ),
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias', to='products.categoriaproduto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.familiaproduto'),
        ),
        migrations.CreateModel(
            name='LogVerificacaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('permitido', models.BooleanField()),
                ('codigo', models.CharField(max_length=60)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes_comprador', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes_vendedor', to='products.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes_negociacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MensagemConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('conteudo', models.TextField(max_length=2000)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('SISTEMA', 'Sistema')], default='TEXTO', max_length=10)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('removida_em', models.DateTimeField(blank=True, null=True)),
                ('denunciada', models.BooleanField(default=False)),
                ('auditoria', models.JSONField(blank=True, default=dict)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='products.conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('motivo', models.CharField(max_length=120)),
                ('descricao', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('ENCERRADA', 'Encerrada')], db_index=True, default='ABERTA', max_length=12)),
                ('dados_auditoria', models.JSONField(blank=True, default=dict)),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='products.conversa')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_produtos_recebidas', to=settings.AUTH_USER_MODEL)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_produtos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='products.produto')),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='products.mensagemconversa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.segmentoproduto'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='products.setorproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.setorproduto'),
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('ativo', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='products.familiaproduto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.tipoproduto'),
        ),
        migrations.CreateModel(
            name='ValorAtributoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('valor', models.JSONField()),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='products.atributoproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueioNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to=settings.AUTH_USER_MODEL)),
                ('bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bloqueador', 'bloqueado'), name='products_negotiation_block_uk'), models.CheckConstraint(condition=models.Q(('bloqueador', models.F('bloqueado')), _negated=True), name='products_negotiation_block_self_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='atributoproduto',
            constraint=models.UniqueConstraint(fields=('categoria_taxonomia', 'chave'), name='products_attribute_category_key_uk'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('removido_em__isnull', True), ('status', 'ATIVA')), fields=('produto', 'comprador', 'vendedor'), name='products_active_conversation_uk'),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.CheckConstraint(condition=models.Q(('comprador', models.F('vendedor')), _negated=True), name='products_conversation_participants_ck'),
        ),
        migrations.AddConstraint(
            model_name='familiaproduto',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='products_family_category_slug_uk'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(fields=('setor', 'slug'), name='products_category_sector_slug_uk'),
        ),
        migrations.AddConstraint(
            model_name='tipoproduto',
            constraint=models.UniqueConstraint(fields=('familia', 'slug'), name='products_type_family_slug_uk'),
        ),
        migrations.AddConstraint(
            model_name='valoratributoproduto',
            constraint=models.UniqueConstraint(fields=('produto', 'atributo'), name='products_value_product_attribute_uk'),
        ),
    ]
