# Generated by Django 6.0.5 on 2026-07-30 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_seed_integration_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('url', models.URLField(max_length=500)),
                ('youtube_id', models.CharField(max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.produto')),
            ],
            options={
                'ordering': ['ordem', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'youtube_id'), name='products_video_product_youtube_uk')],
            },
        ),
    ]
