# Generated by Django 6.0.5 on 2026-07-30 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_produtovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProdutoSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'segmento__nome'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='categoriaproduto',
            name='products_category_sector_slug_uk',
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='icone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familiaproduto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familiaproduto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familiaproduto',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentoproduto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='segmentoproduto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segmentoproduto',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='exige_segmento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='permite_segmento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='products.setorproduto'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('slug',), name='products_category_active_slug_uk'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('nome',), name='products_category_active_name_uk'),
        ),
        migrations.AddField(
            model_name='tipoprodutosegmento',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_relacionados', to='products.segmentoproduto'),
        ),
        migrations.AddField(
            model_name='tipoprodutosegmento',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_relacionados', to='products.tipoproduto'),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='segmentos',
            field=models.ManyToManyField(related_name='tipos', through='products.TipoProdutoSegmento', to='products.segmentoproduto'),
        ),
        migrations.AddConstraint(
            model_name='tipoprodutosegmento',
            constraint=models.UniqueConstraint(fields=('tipo_produto', 'segmento'), name='products_type_segment_uk'),
        ),
    ]
