# Generated by Django 6.0.5 on 2026-07-30 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('products', '0008_seed_balanced_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_interno', ''), _negated=True), fields=('codigo_interno',), name='products_internal_code_uk'),
        ),
    ]
