# Generated by Django 6.0.5 on 2026-07-17 16:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def preencher_qr_tokens(apps, schema_editor):
    Servico = apps.get_model('services', 'Servico')
    for servico in Servico.objects.filter(qr_token__isnull=True).iterator():
        servico.qr_token = uuid.uuid4()
        servico.save(update_fields=['qr_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='qr_ativo',
            field=models.BooleanField(db_column='services_servico_qr_ativo', default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='qr_atualizado_em',
            field=models.DateTimeField(db_column='services_servico_qr_atualizado_em', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servico',
            name='qr_token',
            field=models.UUIDField(db_column='services_servico_qr_token', editable=False, null=True),
        ),
        migrations.RunPython(preencher_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servico',
            name='qr_token',
            field=models.UUIDField(db_column='services_servico_qr_token', default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ServicoLink',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_link_id', primary_key=True, serialize=False)),
                ('tipo_link', models.CharField(choices=[('SITE', 'Site'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TIKTOK', 'TikTok'), ('X', 'X'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('YOUTUBE', 'YouTube'), ('OUTRO', 'Outro')], db_column='services_servico_link_tipo', max_length=20)),
                ('titulo', models.CharField(blank=True, db_column='services_servico_link_titulo', max_length=120)),
                ('url', models.URLField(db_column='services_servico_link_url', max_length=500)),
                ('identificador_externo', models.CharField(blank=True, db_column='services_servico_link_identificador_externo', max_length=120, null=True)),
                ('ordem', models.PositiveSmallIntegerField(db_column='services_servico_link_ordem', default=0)),
                ('destaque', models.BooleanField(db_column='services_servico_link_destaque', default=False)),
                ('ativo', models.BooleanField(db_column='services_servico_link_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_link_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_link_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='services_servico_link_excluido_em', null=True)),
                ('servico', models.ForeignKey(db_column='services_servico_link_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='services.servico')),
            ],
            options={
                'db_table': '"services"."services_servico_link_tb"',
                'ordering': ['-destaque', 'ordem', 'id'],
                'indexes': [models.Index(fields=['servico', 'ativo', 'ordem'], name='services_serv_link_s_a_o_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('servico', 'url'), name='services_serv_link_url_ativa_uk')],
            },
        ),
    ]
