# Generated by Django 6.0.6 on 2026-07-10 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE SCHEMA IF NOT EXISTS api;',
                'CREATE SCHEMA IF NOT EXISTS core;',
                'CREATE SCHEMA IF NOT EXISTS platform;',
                'CREATE SCHEMA IF NOT EXISTS services;',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='core_configuracao_sistema_id', primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=120, unique=True, verbose_name='chave')),
                ('valor', models.TextField(blank=True, verbose_name='valor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'configuração do sistema',
                'verbose_name_plural': 'configurações do sistema',
                'db_table': '"core"."core_configuracao_sistema_tb"',
                'ordering': ['chave'],
                'indexes': [models.Index(fields=['chave'], name='core_config_sistema_chave_idx'), models.Index(fields=['ativo'], name='core_config_sistema_ativo_idx')],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='core_perfil_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': '"core"."core_perfil_tb"',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='core_perfil_nome_idx'), models.Index(fields=['ativo'], name='core_perfil_ativo_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='core_permissao_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'db_table': '"core"."core_permissao_tb"',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='core_permissao_codigo_idx'), models.Index(fields=['ativo'], name='core_permissao_ativo_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='core_perfil_permissao_id', primary_key=True, serialize=False)),
                ('perfil', models.ForeignKey(db_column='core_perfil_fk', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_permissoes', to='core.perfil', verbose_name='perfil')),
                ('permissao', models.ForeignKey(db_column='core_permissao_fk', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_permissoes', to='core.permissao', verbose_name='permissão')),
            ],
            options={
                'verbose_name': 'permissão do perfil',
                'verbose_name_plural': 'permissões dos perfis',
                'db_table': '"core"."core_perfil_permissao_tb"',
                'ordering': ['perfil__nome', 'permissao__codigo'],
                'indexes': [models.Index(fields=['perfil', 'permissao'], name='core_perfil_permissao_idx'), models.Index(fields=['ativo'], name='core_perfil_perm_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'permissao'), name='core_perfil_permissao_uk')],
            },
        ),
    ]
