# Generated by Django 6.0.6 on 2026-07-10 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoInstitucional',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_contato_institucional_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('X', 'X'), ('OUTRO', 'Outro')], db_column='core_contato_institucional_tipo', max_length=20, verbose_name='tipo')),
                ('nome', models.CharField(db_column='core_contato_institucional_nome', max_length=120, verbose_name='nome')),
                ('valor', models.CharField(db_column='core_contato_institucional_valor', max_length=180, verbose_name='valor')),
                ('url', models.URLField(blank=True, db_column='core_contato_institucional_url', verbose_name='URL')),
                ('icone', models.CharField(blank=True, db_column='core_contato_institucional_icone', max_length=80, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(db_column='core_contato_institucional_ordem', default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(db_column='core_contato_institucional_ativo', db_index=True, default=True, verbose_name='ativo')),
                ('exibir_topbar', models.BooleanField(db_column='core_contato_institucional_exibir_topbar', default=True, verbose_name='exibir na topbar')),
                ('exibir_rodape', models.BooleanField(db_column='core_contato_institucional_exibir_rodape', default=True, verbose_name='exibir no rodapé')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_contato_institucional_criado_em', verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_contato_institucional_atualizado_em', verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'contato institucional',
                'verbose_name_plural': 'contatos institucionais',
                'db_table': '"core"."core_contato_institucional_tb"',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['tipo'], name='core_contato_tipo_idx'), models.Index(fields=['ativo'], name='core_contato_ativo_idx'), models.Index(fields=['ordem'], name='core_contato_ordem_idx')],
            },
        ),
    ]
