# Generated by Django 6.0.5 on 2026-07-11 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contatoinstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeBrasil',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_cidade_id', primary_key=True, serialize=False)),
                ('codigo_ibge', models.CharField(blank=True, db_column='core_cidade_codigo_ibge', max_length=7)),
                ('nome', models.CharField(db_column='core_cidade_nome', max_length=120)),
                ('slug', models.SlugField(db_column='core_cidade_slug', max_length=180)),
                ('latitude', models.DecimalField(blank=True, db_column='core_cidade_latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='core_cidade_longitude', decimal_places=6, max_digits=9, null=True)),
                ('capital', models.BooleanField(db_column='core_cidade_capital', default=False)),
                ('ativo', models.BooleanField(db_column='core_cidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_cidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_cidade_atualizado_em')),
            ],
            options={
                'verbose_name': 'cidade brasileira',
                'verbose_name_plural': 'cidades brasileiras',
                'db_table': '"core"."core_cidade_tb"',
                'ordering': ['estado__sigla', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BairroCidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_bairro_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='core_bairro_nome', max_length=120)),
                ('slug', models.SlugField(db_column='core_bairro_slug', max_length=180)),
                ('codigo_oficial', models.CharField(blank=True, db_column='core_bairro_codigo_oficial', max_length=30)),
                ('ativo', models.BooleanField(db_column='core_bairro_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_bairro_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_bairro_atualizado_em')),
                ('cidade', models.ForeignKey(db_column='core_bairro_fk_cidade', on_delete=django.db.models.deletion.CASCADE, related_name='bairros_core', to='core.cidadebrasil')),
            ],
            options={
                'db_table': '"core"."core_bairro_tb"',
                'ordering': ['cidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstadoBrasil',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_estado_id', primary_key=True, serialize=False)),
                ('codigo_ibge', models.CharField(blank=True, db_column='core_estado_codigo_ibge', max_length=2)),
                ('nome', models.CharField(db_column='core_estado_nome', max_length=100)),
                ('sigla', models.CharField(db_column='core_estado_sigla', max_length=2, unique=True)),
                ('regiao_brasileira', models.CharField(choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('CENTRO_OESTE', 'Centro-Oeste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul')], db_column='core_estado_regiao_brasileira', max_length=20)),
                ('ativo', models.BooleanField(db_column='core_estado_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_estado_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_estado_atualizado_em')),
            ],
            options={
                'verbose_name': 'estado brasileiro',
                'verbose_name_plural': 'estados brasileiros',
                'db_table': '"core"."core_estado_tb"',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['sigla'], name='core_estado_idx_sigla'), models.Index(fields=['ativo'], name='core_estado_idx_ativo')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo_ibge', ''), _negated=True), fields=('codigo_ibge',), name='core_estado_codigo_ibge_uk')],
            },
        ),
        migrations.CreateModel(
            name='EnderecoCore',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_endereco_id', primary_key=True, serialize=False)),
                ('tipo_endereco', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('ENTREGA', 'Entrega'), ('COBRANCA', 'Cobrança'), ('ATENDIMENTO', 'Atendimento'), ('OUTRO', 'Outro')], db_column='core_endereco_tipo_endereco', default='OUTRO', max_length=20)),
                ('cep', models.CharField(blank=True, db_column='core_endereco_cep', max_length=8)),
                ('logradouro', models.CharField(db_column='core_endereco_logradouro', max_length=180)),
                ('numero', models.CharField(blank=True, db_column='core_endereco_numero', max_length=20)),
                ('complemento', models.CharField(blank=True, db_column='core_endereco_complemento', max_length=120)),
                ('bairro_texto', models.CharField(blank=True, db_column='core_endereco_bairro_texto', max_length=120)),
                ('referencia', models.CharField(blank=True, db_column='core_endereco_referencia', max_length=180)),
                ('latitude', models.DecimalField(blank=True, db_column='core_endereco_latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='core_endereco_longitude', decimal_places=6, max_digits=9, null=True)),
                ('principal', models.BooleanField(db_column='core_endereco_principal', default=False)),
                ('validado', models.BooleanField(db_column='core_endereco_validado', default=False)),
                ('origem_dados', models.CharField(blank=True, db_column='core_endereco_origem_dados', max_length=40)),
                ('ativo', models.BooleanField(db_column='core_endereco_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_endereco_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_endereco_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='core_endereco_excluido_em', null=True)),
                ('bairro', models.ForeignKey(blank=True, db_column='core_endereco_fk_bairro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='core.bairrocidade')),
                ('cidade', models.ForeignKey(db_column='core_endereco_fk_cidade', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos_core', to='core.cidadebrasil')),
                ('estado', models.ForeignKey(db_column='core_endereco_fk_estado', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos_core', to='core.estadobrasil')),
            ],
            options={
                'db_table': '"core"."core_endereco_tb"',
                'ordering': ['cidade__nome', 'logradouro', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='cidadebrasil',
            name='estado',
            field=models.ForeignKey(db_column='core_cidade_fk_estado', on_delete=django.db.models.deletion.PROTECT, related_name='cidades_core', to='core.estadobrasil'),
        ),
        migrations.CreateModel(
            name='PessoaDocumento',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_pessoa_documento_id', primary_key=True, serialize=False)),
                ('numero_normalizado', models.CharField(blank=True, db_column='core_pessoa_documento_numero_normalizado', max_length=40)),
                ('nome_documento', models.CharField(blank=True, db_column='core_pessoa_documento_nome_documento', max_length=120)),
                ('orgao_emissor', models.CharField(blank=True, db_column='core_pessoa_documento_orgao_emissor', max_length=40)),
                ('uf_emissao', models.CharField(blank=True, db_column='core_pessoa_documento_uf_emissao', max_length=2)),
                ('data_emissao', models.DateField(blank=True, db_column='core_pessoa_documento_data_emissao', null=True)),
                ('data_validade', models.DateField(blank=True, db_column='core_pessoa_documento_data_validade', null=True)),
                ('arquivo_frente', models.FileField(blank=True, db_column='core_pessoa_documento_arquivo_frente', upload_to='documentos/pessoas/frente/%Y/%m/')),
                ('arquivo_verso', models.FileField(blank=True, db_column='core_pessoa_documento_arquivo_verso', upload_to='documentos/pessoas/verso/%Y/%m/')),
                ('arquivo_unico', models.FileField(blank=True, db_column='core_pessoa_documento_arquivo_unico', upload_to='documentos/pessoas/unico/%Y/%m/')),
                ('status_validacao', models.CharField(choices=[('NAO_ENVIADO', 'Não enviado'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EXPIRADO', 'Expirado')], db_column='core_pessoa_documento_status_validacao', default='NAO_ENVIADO', max_length=20)),
                ('validado_em', models.DateTimeField(blank=True, db_column='core_pessoa_documento_validado_em', null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, db_column='core_pessoa_documento_motivo_rejeicao')),
                ('principal', models.BooleanField(db_column='core_pessoa_documento_principal', default=False)),
                ('ativo', models.BooleanField(db_column='core_pessoa_documento_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_pessoa_documento_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_pessoa_documento_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='core_pessoa_documento_excluido_em', null=True)),
                ('usuario', models.ForeignKey(db_column='core_pessoa_documento_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_pessoais', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, db_column='core_pessoa_documento_fk_validado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."core_pessoa_documento_tb"',
                'ordering': ['usuario', 'tipo_documento__nome'],
            },
        ),
        migrations.CreateModel(
            name='CNHDetalhe',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_cnh_detalhe_id', primary_key=True, serialize=False)),
                ('numero_registro', models.CharField(db_column='core_cnh_detalhe_numero_registro', max_length=30)),
                ('categoria', models.CharField(db_column='core_cnh_detalhe_categoria', max_length=5)),
                ('possui_ear', models.BooleanField(db_column='core_cnh_detalhe_possui_ear', default=False)),
                ('primeira_habilitacao', models.DateField(blank=True, db_column='core_cnh_detalhe_primeira_habilitacao', null=True)),
                ('validade', models.DateField(blank=True, db_column='core_cnh_detalhe_validade', null=True)),
                ('ativo', models.BooleanField(db_column='core_cnh_detalhe_ativo', default=True)),
                ('documento', models.OneToOneField(db_column='core_cnh_detalhe_fk_documento', on_delete=django.db.models.deletion.CASCADE, related_name='cnh_detalhe', to='core.pessoadocumento')),
            ],
            options={
                'db_table': '"core"."core_cnh_detalhe_tb"',
            },
        ),
        migrations.CreateModel(
            name='RegiaoCidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_regiao_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='core_regiao_nome', max_length=120)),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('COMERCIAL', 'Comercial'), ('OPERACIONAL', 'Operacional'), ('TURISTICA', 'Turística'), ('MOBILIDADE', 'Mobilidade'), ('ATENDIMENTO', 'Atendimento')], db_column='core_regiao_tipo', max_length=20)),
                ('descricao', models.TextField(blank=True, db_column='core_regiao_descricao')),
                ('ativo', models.BooleanField(db_column='core_regiao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_regiao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_regiao_atualizado_em')),
                ('cidade', models.ForeignKey(db_column='core_regiao_fk_cidade', on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='core.cidadebrasil')),
            ],
            options={
                'db_table': '"core"."core_regiao_tb"',
                'ordering': ['cidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_tipo_documento_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='core_tipo_documento_codigo', max_length=40, unique=True)),
                ('nome', models.CharField(db_column='core_tipo_documento_nome', max_length=120)),
                ('descricao', models.TextField(blank=True, db_column='core_tipo_documento_descricao')),
                ('pessoa_fisica', models.BooleanField(db_column='core_tipo_documento_pessoa_fisica', default=True)),
                ('pessoa_juridica', models.BooleanField(db_column='core_tipo_documento_pessoa_juridica', default=False)),
                ('possui_validade', models.BooleanField(db_column='core_tipo_documento_possui_validade', default=False)),
                ('exige_frente', models.BooleanField(db_column='core_tipo_documento_exige_frente', default=False)),
                ('exige_verso', models.BooleanField(db_column='core_tipo_documento_exige_verso', default=False)),
                ('permite_arquivo_unico', models.BooleanField(db_column='core_tipo_documento_permite_arquivo_unico', default=True)),
                ('sensivel', models.BooleanField(db_column='core_tipo_documento_sensivel', default=True)),
                ('ativo', models.BooleanField(db_column='core_tipo_documento_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_tipo_documento_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_tipo_documento_atualizado_em')),
            ],
            options={
                'db_table': '"core"."core_tipo_documento_tb"',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='core_tipo_doc_idx_codigo')],
            },
        ),
        migrations.AddField(
            model_name='pessoadocumento',
            name='tipo_documento',
            field=models.ForeignKey(db_column='core_pessoa_documento_fk_tipo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.tipodocumento'),
        ),
        migrations.CreateModel(
            name='DocumentoRequisito',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_documento_requisito_id', primary_key=True, serialize=False)),
                ('contexto', models.CharField(choices=[('CADASTRO_PF', 'Cadastro PF'), ('VENDA_PRODUTO', 'Venda de produto'), ('PRESTACAO_SERVICO', 'Prestação de serviço'), ('PROPRIETARIO_EMPRESA', 'Proprietário de empresa'), ('VENDEDOR', 'Vendedor'), ('MOTORISTA', 'Motorista'), ('EMISSAO_FISCAL', 'Emissão fiscal')], db_column='core_documento_requisito_contexto', max_length=40)),
                ('modulo', models.CharField(db_column='core_documento_requisito_modulo', max_length=60)),
                ('obrigatorio', models.BooleanField(db_column='core_documento_requisito_obrigatorio', default=False)),
                ('condicional', models.BooleanField(db_column='core_documento_requisito_condicional', default=False)),
                ('regra_json', models.JSONField(blank=True, db_column='core_documento_requisito_regra_json', default=dict)),
                ('ativo', models.BooleanField(db_column='core_documento_requisito_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_documento_requisito_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_documento_requisito_atualizado_em')),
                ('tipo_documento', models.ForeignKey(db_column='core_documento_requisito_fk_tipo', on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='core.tipodocumento')),
            ],
            options={
                'db_table': '"core"."core_documento_requisito_tb"',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEndereco',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_usuario_endereco_id', primary_key=True, serialize=False)),
                ('principal', models.BooleanField(db_column='core_usuario_endereco_principal', default=False)),
                ('ativo', models.BooleanField(db_column='core_usuario_endereco_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_usuario_endereco_criado_em')),
                ('endereco', models.ForeignKey(db_column='core_usuario_endereco_fk_endereco', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='core.enderecocore')),
                ('usuario', models.ForeignKey(db_column='core_usuario_endereco_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."core_usuario_endereco_tb"',
            },
        ),
        migrations.CreateModel(
            name='ZonaCidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_zona_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='core_zona_nome', max_length=120)),
                ('descricao', models.TextField(blank=True, db_column='core_zona_descricao')),
                ('ativo', models.BooleanField(db_column='core_zona_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_zona_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_zona_atualizado_em')),
                ('cidade', models.ForeignKey(db_column='core_zona_fk_cidade', on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='core.cidadebrasil')),
            ],
            options={
                'db_table': '"core"."core_zona_tb"',
                'ordering': ['cidade__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='bairrocidade',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='core_bairro_fk_zona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bairros', to='core.zonacidade'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_auditoria_id', primary_key=True, serialize=False)),
                ('acao', models.CharField(db_column='core_auditoria_acao', max_length=80)),
                ('entidade', models.CharField(db_column='core_auditoria_entidade', max_length=120)),
                ('registro_id', models.CharField(blank=True, db_column='core_auditoria_registro_id', max_length=60)),
                ('dados_antes_json', models.JSONField(blank=True, db_column='core_auditoria_dados_antes_json', default=dict)),
                ('dados_depois_json', models.JSONField(blank=True, db_column='core_auditoria_dados_depois_json', default=dict)),
                ('motivo', models.TextField(blank=True, db_column='core_auditoria_motivo')),
                ('ip', models.GenericIPAddressField(blank=True, db_column='core_auditoria_ip', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='core_auditoria_user_agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_auditoria_criado_em')),
                ('usuario', models.ForeignKey(blank=True, db_column='core_auditoria_fk_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."core_auditoria_tb"',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acao'], name='core_auditoria_idx_acao'), models.Index(fields=['entidade', 'registro_id'], name='core_auditoria_idx_registro')],
            },
        ),
        migrations.AddIndex(
            model_name='enderecocore',
            index=models.Index(fields=['cep'], name='core_endereco_idx_cep'),
        ),
        migrations.AddIndex(
            model_name='enderecocore',
            index=models.Index(fields=['cidade'], name='core_endereco_idx_cidade'),
        ),
        migrations.AddIndex(
            model_name='enderecocore',
            index=models.Index(fields=['ativo'], name='core_endereco_idx_ativo'),
        ),
        migrations.AddIndex(
            model_name='cidadebrasil',
            index=models.Index(fields=['estado', 'nome'], name='core_cidade_idx_nome'),
        ),
        migrations.AddIndex(
            model_name='cidadebrasil',
            index=models.Index(fields=['slug'], name='core_cidade_idx_slug'),
        ),
        migrations.AddIndex(
            model_name='cidadebrasil',
            index=models.Index(fields=['ativo'], name='core_cidade_idx_ativo'),
        ),
        migrations.AddConstraint(
            model_name='cidadebrasil',
            constraint=models.UniqueConstraint(fields=('estado', 'nome'), name='core_cidade_estado_nome_uk'),
        ),
        migrations.AddConstraint(
            model_name='cidadebrasil',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_ibge', ''), _negated=True), fields=('codigo_ibge',), name='core_cidade_codigo_ibge_uk'),
        ),
        migrations.AddIndex(
            model_name='regiaocidade',
            index=models.Index(fields=['cidade', 'tipo'], name='core_regiao_idx_tipo'),
        ),
        migrations.AddConstraint(
            model_name='regiaocidade',
            constraint=models.UniqueConstraint(fields=('cidade', 'nome'), name='core_regiao_cidade_nome_uk'),
        ),
        migrations.AddConstraint(
            model_name='pessoadocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_normalizado', ''), _negated=True), fields=('tipo_documento', 'numero_normalizado'), name='core_pessoa_doc_tipo_numero_uk'),
        ),
        migrations.AddConstraint(
            model_name='documentorequisito',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'contexto', 'modulo'), name='core_doc_req_tipo_contexto_uk'),
        ),
        migrations.AddConstraint(
            model_name='usuarioendereco',
            constraint=models.UniqueConstraint(fields=('usuario', 'endereco'), name='core_usuario_endereco_uk'),
        ),
        migrations.AddConstraint(
            model_name='zonacidade',
            constraint=models.UniqueConstraint(fields=('cidade', 'nome'), name='core_zona_cidade_nome_uk'),
        ),
        migrations.AddIndex(
            model_name='bairrocidade',
            index=models.Index(fields=['cidade', 'slug'], name='core_bairro_idx_slug'),
        ),
        migrations.AddConstraint(
            model_name='bairrocidade',
            constraint=models.UniqueConstraint(fields=('cidade', 'nome'), name='core_bairro_cidade_nome_uk'),
        ),
    ]
