# Generated by Django 6.0.5 on 2026-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditoria_fundacao_autorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissao',
            name='criticidade',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Básica'), (20, 'Operacional'), (30, 'Moderação'), (40, 'Administrativa'), (50, 'Protegida')], default=10, verbose_name='criticidade'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='grupo',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='módulo'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='protegida',
            field=models.BooleanField(default=False, verbose_name='protegida'),
        ),
    ]
