# Generated by Django 6.0.5 on 2026-08-15 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_news_comment_permissions'),
        ('recruitment', '0004_vagas_contratantes_e_auditoria'),
        ('services', '0008_alter_servico_tipo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoAdicional',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='core_atributo_adicional_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CNH', 'CNH'), ('EXPERIENCIA', 'Experiência'), ('ESCOLARIDADE', 'Escolaridade'), ('CURSO', 'Curso'), ('CERTIFICACAO', 'Certificação'), ('DISPONIBILIDADE', 'Disponibilidade'), ('VEICULO', 'Veículo'), ('IDIOMA', 'Idioma'), ('HABILIDADE', 'Habilidade'), ('CONHECIMENTO', 'Conhecimento técnico'), ('ATENDIMENTO', 'Atendimento'), ('ESPECIALIDADE', 'Especialidade'), ('AREA_ATUACAO', 'Área de atuação'), ('EQUIPAMENTO', 'Equipamento'), ('PRAZO', 'Prazo'), ('LOCAL_ATENDIMENTO', 'Local de atendimento'), ('OUTRO', 'Outro')], db_column='core_atributo_tipo', max_length=32)),
                ('nome_personalizado', models.CharField(blank=True, db_column='core_atributo_nome', max_length=100)),
                ('valor', models.CharField(db_column='core_atributo_valor', max_length=240)),
                ('classificacao', models.CharField(choices=[('OBRIGATORIO', 'Obrigatório'), ('DESEJAVEL', 'Desejável'), ('CARACTERISTICA', 'Característica'), ('DIFERENCIAL', 'Diferencial'), ('CONDICAO', 'Condição'), ('INFORMATIVO', 'Informativo')], db_column='core_atributo_classificacao', default='INFORMATIVO', max_length=24)),
                ('observacao', models.CharField(blank=True, db_column='core_atributo_observacao', max_length=300)),
                ('ordem', models.PositiveSmallIntegerField(db_column='core_atributo_ordem', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='core_atributo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='core_atributo_atualizado_em')),
                ('servico', models.ForeignKey(blank=True, db_column='core_atributo_fk_servico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_adicionais', to='services.servico')),
                ('vaga', models.ForeignKey(blank=True, db_column='core_atributo_fk_vaga', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_adicionais', to='recruitment.vaga')),
            ],
            options={
                'db_table': '"core"."core_atributo_adicional_tb"',
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['vaga', 'tipo'], name='core_atributo_vaga_tipo_idx'), models.Index(fields=['servico', 'tipo'], name='core_atributo_serv_tipo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('servico__isnull', True), ('vaga__isnull', False)), models.Q(('servico__isnull', False), ('vaga__isnull', True)), _connector='OR'), name='core_atributo_objeto_xor_ck')],
            },
        ),
    ]
