from django.urls import path

from . import views

app_name = 'social'

urlpatterns = [
    path('social/', views.social_home, name='home'),
    path('social/explorar/', views.explore, name='explore'),
    path('social/pessoas/', views.people_directory, name='people'),
    path('social/empresas/', views.official_content_list, {'kind': 'empresas'}, name='companies'),
    path('social/empresas/<str:identifier>/', views.official_content_detail, {'kind': 'empresas'}, name='company_detail'),
    path('social/eventos/', views.official_content_list, {'kind': 'eventos'}, name='events'),
    path('social/eventos/<str:identifier>/', views.official_content_detail, {'kind': 'eventos'}, name='event_detail'),
    path('social/vagas/', views.official_content_list, {'kind': 'vagas'}, name='jobs'),
    path('social/vagas/<str:identifier>/', views.official_content_detail, {'kind': 'vagas'}, name='job_detail'),
    path('social/servicos/', views.official_content_list, {'kind': 'servicos'}, name='services'),
    path('social/servicos/<str:identifier>/', views.official_content_detail, {'kind': 'servicos'}, name='service_detail'),
    path('social/produtos/', views.official_content_list, {'kind': 'produtos'}, name='products'),
    path('social/produtos/<str:identifier>/', views.official_content_detail, {'kind': 'produtos'}, name='product_detail'),
    path('social/noticias/', views.official_content_list, {'kind': 'noticias'}, name='news'),
    path('social/noticias/<str:identifier>/', views.official_content_detail, {'kind': 'noticias'}, name='news_detail'),
    path('social/turismo/', views.official_content_list, {'kind': 'turismo'}, name='tourism'),
    path('social/esportes/', views.official_content_list, {'kind': 'esportes'}, name='sports'),
    path('social/yubotuka/', views.official_content_list, {'kind': 'yubotuka'}, name='yubotuka'),
    path('social/seguindo/', views.following, name='following'),
    path('social/solicitacoes/', views.follow_requests, name='follow_requests'),
    path('social/@<slug:slug>/', views.profile_public, name='profile'),
    path('social/perfil/editar/', views.profile_edit, name='profile_edit'),
    path('social/publicar/', views.post_create, name='post_create'),
    path('social/story/criar/', views.story_create, name='story_create'),
    path('social/story/<uuid:uuid>/', views.story_detail, name='story_detail'),
    path('social/story/<uuid:uuid>/excluir/', views.story_delete, name='story_delete'),
    path('social/post/<uuid:uuid>/', views.post_detail, name='post_detail'),
    path('social/post/<uuid:uuid>/excluir/', views.post_delete, name='post_delete'),
    path('social/post/<uuid:uuid>/curtir/', views.post_like, name='post_like'),
    path('social/post/<uuid:uuid>/descurtir/', views.post_unlike, name='post_unlike'),
    path('social/post/<uuid:uuid>/comentar/', views.post_comment, name='post_comment'),
    path('social/post/<uuid:uuid>/salvar/', views.post_save, name='post_save'),
    path('social/post/<uuid:uuid>/remover-salvo/', views.post_unsave, name='post_unsave'),
    path('social/salvos/', views.saved_posts, name='saved_posts'),
    path('social/solicitacoes/<uuid:uuid>/<str:decision>/', views.follow_request_decide, name='follow_request_decide'),
    path('social/perfis/<uuid:uuid>/bloquear/', views.profile_block, name='profile_block'),
    path('social/perfis/<uuid:uuid>/desbloquear/', views.profile_unblock, name='profile_unblock'),
    path('social/compartilhar/<str:app_label>/<str:model_name>/<uuid:uuid>/', views.share_platform_content, name='share_platform_content'),
    path('social/perfis/<uuid:uuid>/seguir/', views.follow_profile, name='follow_profile'),
    path('social/perfis/<uuid:uuid>/deixar-de-seguir/', views.unfollow_profile, name='unfollow_profile'),
    path('social/empresas/<uuid:uuid>/seguir/', views.follow_company, name='follow_company'),
    path('social/empresas/<uuid:uuid>/deixar-de-seguir/', views.unfollow_company, name='unfollow_company'),
    path('social/mensagens/', views.messages_inbox, name='messages'),
    path('social/mensagens/solicitar/', views.conversation_request_send, name='conversation_request_send'),
    path('social/mensagens/solicitacoes/<uuid:uuid>/<str:decision>/', views.conversation_request_decide, name='conversation_request_decide'),
    path('social/mensagens/<uuid:uuid>/', views.conversation_detail, name='conversation_detail'),
    path('social/conteudos/<str:kind>/', views.official_content_list, name='official_list'),
    path('social/conteudos/<str:kind>/<str:identifier>/', views.official_content_detail, name='official_detail'),
]
