# Generated by Django 6.0.5 on 2026-09-12 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0023_subcategoriacnae'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE SCHEMA IF NOT EXISTS advertising;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Criativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('HTML', 'HTML seguro'), ('TEXTO', 'Texto')], max_length=12)),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='advertising/criativos/')),
                ('url_destino', models.URLField()),
                ('ativo', models.BooleanField(default=True)),
                ('aprovado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': '"advertising"."advertising_criativo_tb"',
            },
        ),
        migrations.CreateModel(
            name='EntregaPublicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitante_hash', models.CharField(db_index=True, max_length=64)),
                ('contexto', models.CharField(max_length=80)),
                ('entregue_em', models.DateTimeField(auto_now_add=True)),
                ('clicado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"advertising"."advertising_entrega_tb"',
            },
        ),
        migrations.CreateModel(
            name='PlanoPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(0, 'Nível 0 - contextual'), (1, 'Nível 1 - categoria'), (2, 'Nível 2 - subcategoria'), (3, 'Nível 3 - CNAE/termos'), (4, 'Nível 4 - takeover')])),
                ('preco_diario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('exclusivo', models.BooleanField(default=False)),
                ('limite_anunciantes', models.PositiveIntegerField(default=0, help_text='Zero significa sem limite.')),
                ('impressoes_por_usuario_dia', models.PositiveIntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"advertising"."advertising_plano_tb"',
            },
        ),
        migrations.CreateModel(
            name='Posicionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('contexto', models.CharField(db_index=True, max_length=80)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('aceita_takeover', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"advertising"."advertising_posicionamento_tb"',
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', editable=False, max_length=24)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('aprovada_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_publicitarias', to='organizations.empresa')),
            ],
            options={
                'db_table': '"advertising"."advertising_campanha_tb"',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPublicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=48)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='advertising.campanha')),
            ],
            options={
                'db_table': '"advertising"."advertising_auditoria_tb"',
            },
        ),
        migrations.CreateModel(
            name='CampanhaSegmentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termos', models.JSONField(blank=True, default=list)),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segmentacao', to='advertising.campanha')),
                ('categorias', models.ManyToManyField(blank=True, related_name='campanhas_segmentadas', to='taxonomy.categoria')),
                ('cnaes', models.ManyToManyField(blank=True, related_name='campanhas_segmentadas', to='organizations.cnae')),
                ('subcategorias', models.ManyToManyField(blank=True, related_name='campanhas_segmentadas', to='taxonomy.subcategoria')),
            ],
            options={
                'db_table': '"advertising"."advertising_segmentacao_tb"',
            },
        ),
        migrations.CreateModel(
            name='ContratacaoPublicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_dias', models.PositiveIntegerField(editable=False)),
                ('valor_diario', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratacao', to='advertising.campanha')),
            ],
            options={
                'db_table': '"advertising"."advertising_contratacao_tb"',
            },
        ),
    ]
