# Generated by Django 6.0.5 on 2026-09-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacaopublicidade',
            name='cobranca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratacao_publicidade', to='payments.cobranca'),
        ),
        migrations.AddField(
            model_name='criativo',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criativos', to='advertising.campanha'),
        ),
        migrations.AddField(
            model_name='entregapublicidade',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='advertising.campanha'),
        ),
        migrations.AddField(
            model_name='entregapublicidade',
            name='criativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='advertising.criativo'),
        ),
        migrations.AddConstraint(
            model_name='planopublicitario',
            constraint=models.CheckConstraint(condition=models.Q(('preco_diario__gte', 0)), name='adv_plano_preco_ck'),
        ),
        migrations.AddConstraint(
            model_name='planopublicitario',
            constraint=models.CheckConstraint(condition=models.Q(('impressoes_por_usuario_dia__gte', 1)), name='adv_plano_freq_ck'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='advertising.planopublicitario'),
        ),
        migrations.AddField(
            model_name='entregapublicidade',
            name='posicionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='advertising.posicionamento'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='posicionamentos',
            field=models.ManyToManyField(related_name='campanhas', to='advertising.posicionamento'),
        ),
        migrations.AddConstraint(
            model_name='contratacaopublicidade',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_dias__gte', 1)), name='adv_contratacao_dias_ck'),
        ),
        migrations.AddConstraint(
            model_name='contratacaopublicidade',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='adv_contratacao_total_ck'),
        ),
        migrations.AddIndex(
            model_name='entregapublicidade',
            index=models.Index(fields=['visitante_hash', 'entregue_em'], name='adv_entrega_visit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['status', 'inicio', 'fim'], name='adv_camp_status_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='campanha',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='adv_camp_periodo_ck'),
        ),
    ]
