# Generated by Django 6.0.5 on 2026-09-13 02:37

from django.db import migrations, models


def separar_estados_e_desativar_html(apps, schema_editor):
    Campanha = apps.get_model('advertising', 'Campanha')
    Criativo = apps.get_model('advertising', 'Criativo')
    Campanha.objects.filter(status='AGUARDANDO_PAGAMENTO').update(
        status='AGUARDANDO_APROVACAO',
    )
    Criativo.objects.filter(tipo='HTML').update(tipo='TEXTO', ativo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='criativo',
            name='video',
            field=models.FileField(blank=True, upload_to='advertising/criativos/videos/'),
        ),
        migrations.RunPython(separar_estados_e_desativar_html, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADA', 'Aprovada'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', editable=False, max_length=24),
        ),
        migrations.AlterField(
            model_name='criativo',
            name='tipo',
            field=models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('TEXTO', 'Texto')], max_length=12),
        ),
    ]
