# Generated by Django 6.0.5 on 2026-07-30 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('titulo', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('resumo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('imagem_principal', models.ImageField(blank=True, upload_to='eventos/capas/')),
                ('imagem_alt', models.CharField(blank=True, max_length=220)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(max_length=220)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('publico', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('organizador', models.CharField(blank=True, max_length=180)),
                ('realizador', models.CharField(blank=True, max_length=180)),
                ('permitir_interesse', models.BooleanField(default=True)),
                ('mensagem_interesse', models.CharField(blank=True, max_length=240)),
                ('aceita_inscricoes_futuras', models.BooleanField(default=False)),
                ('modalidade_participacao_futura', models.CharField(choices=[('NAO_DEFINIDA', 'Não definida'), ('EXTERNA', 'Inscrição externa'), ('GRATUITA', 'Ingresso gratuito futuro'), ('PAGA', 'Ingresso pago futuro')], default='NAO_DEFINIDA', max_length=20)),
                ('limite_estimado_publico', models.PositiveIntegerField(blank=True, null=True)),
                ('url_inscricao_externa', models.URLField(blank=True, max_length=500)),
                ('observacao_ingresso', models.CharField(blank=True, max_length=300)),
                ('criador_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa_promotora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_promovidos', to='organizations.empresa')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_proprios', to=settings.AUTH_USER_MODEL)),
                ('responsavel_edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('ALTERADO', 'Alterado'), ('STATUS', 'Status alterado'), ('INTERESSE', 'Interesse marcado'), ('INTERESSE_REMOVIDO', 'Interesse removido')], max_length=24)),
                ('origem', models.CharField(default='WEB', max_length=20)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='events.evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InteresseEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('origem', models.CharField(choices=[('WEB', 'Página web'), ('PAINEL', 'Painel')], default='WEB', max_length=16)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interesses', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interesses_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status', 'publico', 'inicio'], name='events_public_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['proprietario', 'status'], name='events_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['empresa_promotora', 'status'], name='events_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseevento',
            index=models.Index(fields=['evento', 'ativo', 'criado_em'], name='events_interest_metric_idx'),
        ),
        migrations.AddConstraint(
            model_name='interesseevento',
            constraint=models.UniqueConstraint(fields=('evento', 'usuario'), name='events_interesse_usuario_uk'),
        ),
    ]
