# Generated by Django 6.0.5 on 2026-07-20 10:22

import apps.core.domain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='foto',
            field=models.ImageField(blank=True, db_column='sports_atleta_foto', upload_to='sports/atletas/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='imagem',
            field=models.ImageField(blank=True, db_column='sports_campeonato_imagem', upload_to='sports/campeonatos/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='regulamento',
            field=models.FileField(blank=True, db_column='sports_campeonato_regulamento', upload_to='sports/regulamentos/', validators=[apps.core.domain.validar_documento_publico]),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='escudo',
            field=models.ImageField(blank=True, db_column='sports_equipe_escudo', upload_to='sports/equipes/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='imagem',
            field=models.ImageField(blank=True, db_column='sports_modalidade_imagem', upload_to='sports/modalidades/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='organizacaoesportiva',
            name='logotipo',
            field=models.ImageField(blank=True, db_column='sports_organizacao_logotipo', upload_to='sports/organizacoes/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AddConstraint(
            model_name='classificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('campeonato', 'posicao'), name='sports_classificacao_pos_uk'),
        ),
    ]
