# Generated by Django 6.0.5 on 2026-07-11 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_cidadebrasil_bairrocidade_estadobrasil_enderecocore_and_more'),
        ('organizations', '0006_cnae_empresafuncao_empresa_aceita_leads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaCobranca',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_forma_cobranca_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='services_forma_cobranca_nome', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, db_column='services_forma_cobranca_slug', max_length=160, unique=True)),
                ('ativo', models.BooleanField(db_column='services_forma_cobranca_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_forma_cobranca_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_forma_cobranca_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_forma_cobranca_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_profissao_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='services_profissao_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='services_profissao_slug', max_length=180)),
                ('descricao', models.TextField(blank=True, db_column='services_profissao_descricao')),
                ('exige_registro_profissional', models.BooleanField(db_column='services_profissao_exige_registro_profissional', default=False)),
                ('tipo_registro', models.CharField(blank=True, db_column='services_profissao_tipo_registro', max_length=60)),
                ('ativo', models.BooleanField(db_column='services_profissao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_profissao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_profissao_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_profissao_tb"',
                'ordering': ['setor__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_tipo_servico_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='services_tipo_servico_nome', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, db_column='services_tipo_servico_slug', max_length=160, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='services_tipo_servico_descricao')),
                ('ativo', models.BooleanField(db_column='services_tipo_servico_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_tipo_servico_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_tipo_servico_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_tipo_servico_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_id', primary_key=True, serialize=False)),
                ('prestador_tipo', models.CharField(choices=[('PESSOA_FISICA', 'Pessoa física'), ('EMPRESA', 'Empresa')], db_column='services_servico_prestador_tipo', max_length=20)),
                ('titulo', models.CharField(db_column='services_servico_titulo', max_length=160)),
                ('slug', models.SlugField(blank=True, db_column='services_servico_slug', max_length=220, unique=True)),
                ('descricao_curta', models.CharField(blank=True, db_column='services_servico_descricao_curta', max_length=220)),
                ('descricao_completa', models.TextField(blank=True, db_column='services_servico_descricao_completa')),
                ('experiencia', models.TextField(blank=True, db_column='services_servico_experiencia')),
                ('preco_inicial', models.DecimalField(blank=True, db_column='services_servico_preco_inicial', decimal_places=2, max_digits=10, null=True)),
                ('preco_final', models.DecimalField(blank=True, db_column='services_servico_preco_final', decimal_places=2, max_digits=10, null=True)),
                ('preco_sob_consulta', models.BooleanField(db_column='services_servico_preco_sob_consulta', default=False)),
                ('unidade_preco', models.CharField(blank=True, db_column='services_servico_unidade_preco', max_length=60)),
                ('atendimento_remoto', models.BooleanField(db_column='services_servico_atendimento_remoto', default=False)),
                ('atendimento_presencial', models.BooleanField(db_column='services_servico_atendimento_presencial', default=True)),
                ('atendimento_emergencial', models.BooleanField(db_column='services_servico_atendimento_emergencial', default=False)),
                ('prazo_medio', models.CharField(blank=True, db_column='services_servico_prazo_medio', max_length=120)),
                ('telefone_publico', models.CharField(blank=True, db_column='services_servico_telefone_publico', max_length=20)),
                ('whatsapp_publico', models.CharField(blank=True, db_column='services_servico_whatsapp_publico', max_length=20)),
                ('email_publico', models.EmailField(blank=True, db_column='services_servico_email_publico', max_length=254)),
                ('destaque', models.BooleanField(db_column='services_servico_destaque', default=False)),
                ('verificado', models.BooleanField(db_column='services_servico_verificado', default=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('PUBLICADO', 'Publicado'), ('PAUSADO', 'Pausado'), ('REJEITADO', 'Rejeitado'), ('BLOQUEADO', 'Bloqueado')], db_column='services_servico_status', default='RASCUNHO', max_length=20)),
                ('ativo', models.BooleanField(db_column='services_servico_ativo', default=True)),
                ('publicado_em', models.DateTimeField(blank=True, db_column='services_servico_publicado_em', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='services_servico_excluido_em', null=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='services_servico_fk_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='organizations.empresa')),
                ('forma_cobranca', models.ForeignKey(db_column='services_servico_fk_forma_cobranca', on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.formacobranca')),
                ('profissao', models.ForeignKey(db_column='services_servico_fk_profissao', on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.profissao')),
                ('usuario_responsavel', models.ForeignKey(db_column='services_servico_fk_usuario_responsavel', on_delete=django.db.models.deletion.PROTECT, related_name='servicos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"services"."services_servico_tb"',
                'ordering': ['-criado_em'],
                'permissions': [('aprovar_servico', 'Pode aprovar serviço'), ('bloquear_servico', 'Pode bloquear serviço')],
            },
        ),
        migrations.CreateModel(
            name='ServicoAvaliacao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_avaliacao_id', primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(db_column='services_servico_avaliacao_nota')),
                ('titulo', models.CharField(blank=True, db_column='services_servico_avaliacao_titulo', max_length=120)),
                ('comentario', models.TextField(blank=True, db_column='services_servico_avaliacao_comentario')),
                ('resposta_prestador', models.TextField(blank=True, db_column='services_servico_avaliacao_resposta_prestador')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PUBLICADA', 'Publicada'), ('REJEITADA', 'Rejeitada'), ('DENUNCIADA', 'Denunciada')], db_column='services_servico_avaliacao_status', default='PENDENTE', max_length=20)),
                ('verificada', models.BooleanField(db_column='services_servico_avaliacao_verificada', default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_avaliacao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_avaliacao_atualizado_em')),
                ('respondido_em', models.DateTimeField(blank=True, db_column='services_servico_avaliacao_respondido_em', null=True)),
                ('excluido_em', models.DateTimeField(blank=True, db_column='services_servico_avaliacao_excluido_em', null=True)),
                ('servico', models.ForeignKey(db_column='services_servico_avaliacao_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='services.servico')),
                ('usuario_avaliador', models.ForeignKey(db_column='services_servico_avaliacao_fk_usuario_avaliador', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_servicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"services"."services_servico_avaliacao_tb"',
            },
        ),
        migrations.CreateModel(
            name='ServicoCaracteristica',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_caracteristica_id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='services_servico_caracteristica_titulo', max_length=120)),
                ('descricao', models.TextField(blank=True, db_column='services_servico_caracteristica_descricao')),
                ('icone', models.CharField(blank=True, db_column='services_servico_caracteristica_icone', max_length=80)),
                ('ordem', models.PositiveIntegerField(db_column='services_servico_caracteristica_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='services_servico_caracteristica_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_caracteristica_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_caracteristica_atualizado_em')),
                ('servico', models.ForeignKey(db_column='services_servico_caracteristica_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='services.servico')),
            ],
            options={
                'db_table': '"services"."services_servico_caracteristica_tb"',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_setor_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='services_setor_nome', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, db_column='services_setor_slug', max_length=160, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='services_setor_descricao')),
                ('icone', models.CharField(blank=True, db_column='services_setor_icone', max_length=80)),
                ('ordem', models.PositiveIntegerField(db_column='services_setor_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='services_setor_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_setor_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_setor_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_setor_tb"',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['slug'], name='services_setor_idx_slug')],
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='setor',
            field=models.ForeignKey(db_column='services_servico_fk_setor', on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.setor'),
        ),
        migrations.AddField(
            model_name='profissao',
            name='setor',
            field=models.ForeignKey(db_column='services_profissao_fk_setor', on_delete=django.db.models.deletion.PROTECT, related_name='profissoes', to='services.setor'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(db_column='services_servico_fk_tipo_servico', on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.tiposervico'),
        ),
        migrations.CreateModel(
            name='ServicoArea',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_area_id', primary_key=True, serialize=False)),
                ('tipo_area', models.CharField(choices=[('ENDERECO', 'Endereço'), ('BAIRRO', 'Bairro'), ('CIDADE', 'Cidade'), ('REGIAO', 'Região'), ('ESTADO', 'Estado'), ('NACIONAL', 'Nacional'), ('REMOTO', 'Remoto')], db_column='services_servico_area_tipo_area', max_length=20)),
                ('raio_km', models.PositiveIntegerField(blank=True, db_column='services_servico_area_raio_km', null=True)),
                ('remoto', models.BooleanField(db_column='services_servico_area_remoto', default=False)),
                ('nacional', models.BooleanField(db_column='services_servico_area_nacional', default=False)),
                ('ativo', models.BooleanField(db_column='services_servico_area_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_area_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_area_atualizado_em')),
                ('bairro', models.ForeignKey(blank=True, db_column='services_servico_area_fk_bairro', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bairrocidade')),
                ('cidade', models.ForeignKey(blank=True, db_column='services_servico_area_fk_cidade', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cidadebrasil')),
                ('estado', models.ForeignKey(blank=True, db_column='services_servico_area_fk_estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estadobrasil')),
                ('regiao', models.ForeignKey(blank=True, db_column='services_servico_area_fk_regiao', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.regiaocidade')),
                ('servico', models.ForeignKey(db_column='services_servico_area_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='services.servico')),
            ],
            options={
                'db_table': '"services"."services_servico_area_tb"',
                'constraints': [models.UniqueConstraint(fields=('servico', 'tipo_area', 'cidade', 'regiao', 'bairro', 'estado'), name='services_servico_area_uk')],
            },
        ),
        migrations.CreateModel(
            name='ServicoFavorito',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_favorito_id', primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_favorito_criado_em')),
                ('servico', models.ForeignKey(db_column='services_servico_favorito_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='services.servico')),
                ('usuario', models.ForeignKey(db_column='services_servico_favorito_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='servicos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"services"."services_servico_favorito_tb"',
                'constraints': [models.UniqueConstraint(fields=('servico', 'usuario'), name='services_servico_favorito_uk')],
            },
        ),
        migrations.CreateModel(
            name='ServicoImagem',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_servico_imagem_id', primary_key=True, serialize=False)),
                ('imagem', models.ImageField(db_column='services_servico_imagem_imagem', upload_to='servicos/imagens/%Y/%m/')),
                ('legenda', models.CharField(blank=True, db_column='services_servico_imagem_legenda', max_length=160)),
                ('principal', models.BooleanField(db_column='services_servico_imagem_principal', default=False)),
                ('ordem', models.PositiveIntegerField(db_column='services_servico_imagem_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='services_servico_imagem_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_servico_imagem_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_servico_imagem_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='services_servico_imagem_excluido_em', null=True)),
                ('servico', models.ForeignKey(db_column='services_servico_imagem_fk_servico', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='services.servico')),
            ],
            options={
                'db_table': '"services"."services_servico_imagem_tb"',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('servico',), name='services_servico_img_principal_uk')],
            },
        ),
        migrations.AddIndex(
            model_name='profissao',
            index=models.Index(fields=['setor', 'slug'], name='services_profissao_idx_slug'),
        ),
        migrations.AddConstraint(
            model_name='profissao',
            constraint=models.UniqueConstraint(fields=('setor', 'nome'), name='services_profissao_setor_nome_uk'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['slug'], name='services_servico_idx_slug'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['status'], name='services_servico_idx_status'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['usuario_responsavel'], name='services_servico_idx_usuario'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['empresa'], name='services_servico_idx_empresa'),
        ),
    ]
