# Generated by Django 6.0.6 on 2026-07-10 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_organizacao_id', primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=180, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(max_length=180, verbose_name='nome fantasia')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ sem formatação obrigatória.', max_length=20, verbose_name='documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('categoria', models.ForeignKey(db_column='platform_categoria_fk', on_delete=django.db.models.deletion.PROTECT, related_name='organizacoes', to='taxonomy.categoria', verbose_name='categoria')),
                ('proprietario', models.ForeignKey(db_column='platform_proprietario_fk', on_delete=django.db.models.deletion.PROTECT, related_name='organizacoes_proprietario', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'db_table': '"platform"."platform_organizacao_tb"',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoUsuario',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_organizacao_usuario_id', primary_key=True, serialize=False)),
                ('organizacao', models.ForeignKey(db_column='platform_organizacao_fk', on_delete=django.db.models.deletion.CASCADE, related_name='organizacao_usuarios', to='organizations.organizacao', verbose_name='organização')),
                ('usuario', models.ForeignKey(db_column='platform_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='organizacao_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'usuário da organização',
                'verbose_name_plural': 'usuários das organizações',
                'db_table': '"platform"."platform_organizacao_usuario_tb"',
                'ordering': ['organizacao__nome_fantasia', 'usuario__username'],
            },
        ),
        migrations.AddField(
            model_name='organizacao',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='organizacoes', through='organizations.OrganizacaoUsuario', to=settings.AUTH_USER_MODEL, verbose_name='usuários'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_unidade_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('categoria', models.ForeignKey(db_column='platform_categoria_fk', on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='taxonomy.categoria', verbose_name='categoria')),
                ('organizacao', models.ForeignKey(db_column='platform_organizacao_fk', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='organizations.organizacao', verbose_name='organização')),
                ('responsavel', models.ForeignKey(blank=True, db_column='platform_responsavel_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'db_table': '"platform"."platform_unidade_tb"',
                'ordering': ['organizacao__nome_fantasia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_endereco_id', primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=180, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('cep', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('bairro', models.ForeignKey(blank=True, db_column='platform_bairro_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='locations.bairro', verbose_name='bairro')),
                ('cidade', models.ForeignKey(db_column='platform_cidade_fk', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='locations.cidade', verbose_name='cidade')),
                ('unidade', models.OneToOneField(db_column='platform_unidade_fk', on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='organizations.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': '"platform"."platform_endereco_tb"',
                'ordering': ['cidade__nome', 'logradouro', 'numero'],
            },
        ),
        migrations.AddIndex(
            model_name='organizacaousuario',
            index=models.Index(fields=['organizacao', 'usuario'], name='platform_org_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacaousuario',
            index=models.Index(fields=['ativo'], name='platform_org_user_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizacaousuario',
            constraint=models.UniqueConstraint(fields=('organizacao', 'usuario'), name='platform_org_usuario_uk'),
        ),
        migrations.AddIndex(
            model_name='organizacao',
            index=models.Index(fields=['slug'], name='platform_organizacao_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacao',
            index=models.Index(fields=['nome_fantasia'], name='platform_organizacao_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacao',
            index=models.Index(fields=['categoria'], name='platform_organizacao_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacao',
            index=models.Index(fields=['proprietario'], name='platform_organizacao_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='organizacao',
            index=models.Index(fields=['ativo'], name='platform_organizacao_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizacao',
            constraint=models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('documento',), name='platform_organizacao_doc_uk'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['organizacao', 'nome'], name='platform_unidade_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['categoria'], name='platform_unidade_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['responsavel'], name='platform_unidade_resp_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['principal'], name='platform_unidade_princ_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['ativo'], name='platform_unidade_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(fields=('organizacao', 'nome'), name='platform_unidade_nome_uk'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('organizacao',), name='platform_unidade_principal_uk'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['cidade'], name='platform_endereco_cidade_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['bairro'], name='platform_endereco_bairro_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['cep'], name='platform_endereco_cep_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['ativo'], name='platform_endereco_ativo_idx'),
        ),
    ]
