# Generated by Django 6.0.5 on 2026-07-10 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_id', primary_key=True, serialize=False)),
                ('tipo_cadastro', models.CharField(choices=[('AUTONOMO', 'Autônomo'), ('INFORMAL', 'Informal'), ('MEI', 'MEI'), ('EMPRESA', 'Empresa')], db_column='platform_empresa_tipo_cadastro', default='INFORMAL', max_length=20, verbose_name='tipo de cadastro')),
                ('razao_social', models.CharField(blank=True, db_column='platform_empresa_razao_social', max_length=180, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(db_column='platform_empresa_nome_fantasia', max_length=180, verbose_name='nome fantasia')),
                ('slug', models.SlugField(blank=True, db_column='platform_empresa_slug', max_length=220, unique=True, verbose_name='slug')),
                ('cpf_cnpj', models.CharField(blank=True, db_column='platform_empresa_cpf_cnpj', help_text='Documento armazenado somente com números.', max_length=14, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, db_column='platform_empresa_inscricao_estadual', max_length=30, verbose_name='inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, db_column='platform_empresa_inscricao_municipal', max_length=30, verbose_name='inscrição municipal')),
                ('descricao_curta', models.CharField(blank=True, db_column='platform_empresa_descricao_curta', max_length=220, verbose_name='descrição curta')),
                ('descricao_completa', models.TextField(blank=True, db_column='platform_empresa_descricao_completa', verbose_name='descrição completa')),
                ('telefone', models.CharField(blank=True, db_column='platform_empresa_telefone', max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, db_column='platform_empresa_whatsapp', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, db_column='platform_empresa_email', max_length=254, verbose_name='e-mail')),
                ('site', models.URLField(blank=True, db_column='platform_empresa_site', verbose_name='site')),
                ('logo', models.ImageField(blank=True, db_column='platform_empresa_logo', upload_to='empresas/logos/', verbose_name='logo')),
                ('imagem_capa', models.ImageField(blank=True, db_column='platform_empresa_imagem_capa', upload_to='empresas/capas/', verbose_name='imagem de capa')),
                ('cep', models.CharField(blank=True, db_column='platform_empresa_cep', max_length=8, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, db_column='platform_empresa_endereco', max_length=180, verbose_name='endereço')),
                ('numero', models.CharField(blank=True, db_column='platform_empresa_numero', max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, db_column='platform_empresa_complemento', max_length=120, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, db_column='platform_empresa_bairro', max_length=120, verbose_name='bairro')),
                ('latitude', models.DecimalField(blank=True, db_column='platform_empresa_latitude', decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, db_column='platform_empresa_longitude', decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('atende_online', models.BooleanField(db_column='platform_empresa_atende_online', default=False, verbose_name='atende online')),
                ('atende_local', models.BooleanField(db_column='platform_empresa_atende_local', default=True, verbose_name='atende no local')),
                ('horario_atendimento', models.TextField(blank=True, db_column='platform_empresa_horario_atendimento', verbose_name='horário de atendimento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('BLOQUEADA', 'Bloqueada')], db_column='platform_empresa_status', default='RASCUNHO', max_length=20, verbose_name='status')),
                ('verificada', models.BooleanField(db_column='platform_empresa_verificada', default=False, verbose_name='verificada')),
                ('perfil_publico', models.BooleanField(db_column='platform_empresa_perfil_publico', default=False, verbose_name='perfil público')),
                ('ativo', models.BooleanField(db_column='platform_empresa_ativo', default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_criado_em', verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_atualizado_em', verbose_name='atualizado em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='platform_empresa_excluido_em', null=True, verbose_name='excluído em')),
                ('categoria_empresa', models.ForeignKey(blank=True, db_column='platform_empresa_categoria_empresa_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='taxonomy.categoria', verbose_name='categoria da empresa')),
                ('cidade', models.ForeignKey(db_column='platform_empresa_cidade_fk', on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='locations.cidade', verbose_name='cidade')),
                ('estado', models.ForeignKey(db_column='platform_empresa_estado_fk', on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='locations.estado', verbose_name='estado')),
                ('usuario_proprietario', models.ForeignKey(db_column='platform_empresa_usuario_proprietario_fk', on_delete=django.db.models.deletion.PROTECT, related_name='empresas_proprietario_platform', to=settings.AUTH_USER_MODEL, verbose_name='usuário proprietário')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': '"platform"."platform_empresa_tb"',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
