# Generated by Django 6.0.5 on 2026-07-10 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_usuario_id', primary_key=True, serialize=False)),
                ('funcao', models.CharField(choices=[('PROPRIETARIO', 'Proprietário'), ('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('COLABORADOR', 'Colaborador'), ('ATENDENTE', 'Atendente')], db_column='platform_empresa_usuario_funcao', default='COLABORADOR', max_length=20, verbose_name='função')),
                ('proprietario', models.BooleanField(db_column='platform_empresa_usuario_proprietario', default=False, verbose_name='proprietário')),
                ('administrador', models.BooleanField(db_column='platform_empresa_usuario_administrador', default=False, verbose_name='administrador')),
                ('pode_editar', models.BooleanField(db_column='platform_empresa_usuario_pode_editar', default=False, verbose_name='pode editar')),
                ('pode_publicar_servico', models.BooleanField(db_column='platform_empresa_usuario_pode_publicar_servico', default=False, verbose_name='pode publicar serviço')),
                ('pode_gerenciar_equipe', models.BooleanField(db_column='platform_empresa_usuario_pode_gerenciar_equipe', default=False, verbose_name='pode gerenciar equipe')),
                ('ativo', models.BooleanField(db_column='platform_empresa_usuario_ativo', default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_usuario_criado_em', verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_usuario_atualizado_em', verbose_name='atualizado em')),
                ('empresa', models.ForeignKey(db_column='platform_empresa_usuario_empresa_fk', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='organizations.empresa', verbose_name='empresa')),
                ('usuario', models.ForeignKey(db_column='platform_empresa_usuario_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'usuário da empresa',
                'verbose_name_plural': 'usuários das empresas',
                'db_table': '"platform"."platform_empresa_usuario_tb"',
                'ordering': ['empresa__nome_fantasia', 'usuario__username'],
            },
        ),
    ]
