# Generated by Django 6.0.5 on 2026-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_empresa_usuario'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cpf_cnpj'], name='platform_empresa_cpf_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['slug'], name='platform_empresa_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome_fantasia'], name='platform_empresa_nmfant_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['status'], name='platform_empresa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cidade'], name='platform_empresa_cidade_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['estado'], name='platform_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['usuario_proprietario'], name='platform_empresa_usu_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativo'], name='platform_empresa_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['empresa', 'usuario'], name='platform_empresa_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['usuario'], name='platform_empresa_usu_usr_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['funcao'], name='platform_empresa_usu_func_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['ativo'], name='platform_empresa_usu_ativo_idx'),
        ),
    ]
