# Generated by Django 6.0.5 on 2026-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_empresa_indices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(
                condition=models.Q(('cpf_cnpj', ''), _negated=True),
                fields=('cpf_cnpj',),
                name='platform_empresa_cpf_cnpj_uk',
            ),
        ),
        migrations.AddConstraint(
            model_name='empresausuario',
            constraint=models.UniqueConstraint(
                fields=('empresa', 'usuario'),
                name='platform_empresa_usuario_uk',
            ),
        ),
    ]
