# Generated by Django 6.0.5 on 2026-07-11 14:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cidadebrasil_bairrocidade_estadobrasil_enderecocore_and_more'),
        ('organizations', '0005_empresa_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_cnae_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='platform_cnae_codigo', max_length=20, unique=True)),
                ('descricao', models.TextField(db_column='platform_cnae_descricao')),
                ('secao', models.CharField(blank=True, db_column='platform_cnae_secao', max_length=5)),
                ('divisao', models.CharField(blank=True, db_column='platform_cnae_divisao', max_length=5)),
                ('grupo', models.CharField(blank=True, db_column='platform_cnae_grupo', max_length=5)),
                ('classe', models.CharField(blank=True, db_column='platform_cnae_classe', max_length=10)),
                ('subclasse', models.CharField(blank=True, db_column='platform_cnae_subclasse', max_length=20)),
                ('ativo', models.BooleanField(db_column='platform_cnae_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_cnae_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_cnae_atualizado_em')),
            ],
            options={
                'db_table': '"platform"."platform_cnae_tb"',
            },
        ),
        migrations.CreateModel(
            name='EmpresaFuncao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_funcao_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='platform_empresa_funcao_codigo', max_length=40, unique=True)),
                ('nome', models.CharField(db_column='platform_empresa_funcao_nome', max_length=100)),
                ('descricao', models.TextField(blank=True, db_column='platform_empresa_funcao_descricao')),
                ('ativo', models.BooleanField(db_column='platform_empresa_funcao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_funcao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_funcao_atualizado_em')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_funcao_tb"',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='aceita_leads',
            field=models.BooleanField(db_column='platform_empresa_aceita_leads', default=True, verbose_name='aceita leads'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='canal_preferencial_lead',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('PAINEL', 'Painel')], db_column='platform_empresa_canal_preferencial_lead', default='PAINEL', max_length=20, verbose_name='canal preferencial de lead'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_abertura',
            field=models.DateField(blank=True, db_column='platform_empresa_data_abertura', null=True, verbose_name='data de abertura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='distribuicao_lead',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], db_column='platform_empresa_distribuicao_lead', default='MANUAL', max_length=20, verbose_name='distribuição de lead'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='natureza_juridica',
            field=models.CharField(blank=True, db_column='platform_empresa_natureza_juridica', max_length=120, verbose_name='natureza jurídica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='porte',
            field=models.CharField(blank=True, db_column='platform_empresa_porte', max_length=40, verbose_name='porte'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='situacao_cadastral',
            field=models.CharField(blank=True, db_column='platform_empresa_situacao_cadastral', max_length=60, verbose_name='situação cadastral'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('ATIVA', 'Ativa'), ('REJEITADA', 'Rejeitada'), ('SUSPENSA', 'Suspensa'), ('BLOQUEADA', 'Bloqueada')], db_column='platform_empresa_status', default='RASCUNHO', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_cadastro',
            field=models.CharField(choices=[('AUTONOMO', 'Autônomo'), ('INFORMAL', 'Informal'), ('MEI', 'MEI'), ('EMPRESA', 'Empresa'), ('ORGANIZACAO', 'Organização')], db_column='platform_empresa_tipo_cadastro', default='INFORMAL', max_length=20, verbose_name='tipo de cadastro'),
        ),
        migrations.CreateModel(
            name='Capacidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_capacidade_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='platform_capacidade_codigo', max_length=60, unique=True)),
                ('nome', models.CharField(db_column='platform_capacidade_nome', max_length=120)),
                ('descricao', models.TextField(blank=True, db_column='platform_capacidade_descricao')),
                ('exige_aprovacao', models.BooleanField(db_column='platform_capacidade_exige_aprovacao', default=True)),
                ('ativo', models.BooleanField(db_column='platform_capacidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_capacidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_capacidade_atualizado_em')),
            ],
            options={
                'db_table': '"platform"."platform_capacidade_tb"',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='platform_capacidade_idx_codigo')],
            },
        ),
        migrations.CreateModel(
            name='CNPJConsulta',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_cnpj_consulta_id', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='platform_cnpj_consulta_cnpj', max_length=14)),
                ('provider', models.CharField(db_column='platform_cnpj_consulta_provider', max_length=60)),
                ('sucesso', models.BooleanField(db_column='platform_cnpj_consulta_sucesso', default=False)),
                ('codigo_resposta', models.CharField(blank=True, db_column='platform_cnpj_consulta_codigo_resposta', max_length=30)),
                ('resposta_json', models.JSONField(blank=True, db_column='platform_cnpj_consulta_resposta_json', default=dict)),
                ('consultado_em', models.DateTimeField(db_column='platform_cnpj_consulta_consultado_em', default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, db_column='platform_cnpj_consulta_expira_em', null=True)),
                ('erro_resumido', models.CharField(blank=True, db_column='platform_cnpj_consulta_erro_resumido', max_length=240)),
                ('solicitado_por', models.ForeignKey(blank=True, db_column='platform_cnpj_consulta_fk_solicitado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_cnpj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"platform"."platform_cnpj_consulta_tb"',
                'indexes': [models.Index(fields=['cnpj', 'provider'], name='plat_cnpj_cnpj_provider_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCapacidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_capacidade_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('SUSPENSA', 'Suspensa')], db_column='platform_empresa_capacidade_status', default='PENDENTE', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, db_column='platform_empresa_capacidade_aprovado_em', null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, db_column='platform_empresa_capacidade_motivo_rejeicao')),
                ('ativo', models.BooleanField(db_column='platform_empresa_capacidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_capacidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_capacidade_atualizado_em')),
                ('aprovado_por', models.ForeignKey(blank=True, db_column='platform_empresa_capacidade_fk_aprovado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacidades_empresa_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('capacidade', models.ForeignKey(db_column='platform_empresa_capacidade_fk_capacidade', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_capacidade', to='organizations.capacidade')),
                ('empresa', models.ForeignKey(db_column='platform_empresa_capacidade_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='capacidades_empresa', to='organizations.empresa')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_capacidade_tb"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'capacidade'), name='platform_empresa_capacidade_uk')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCNAE',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_cnae_id', primary_key=True, serialize=False)),
                ('principal', models.BooleanField(db_column='platform_empresa_cnae_principal', default=False)),
                ('origem', models.CharField(choices=[('RECEITA', 'Receita'), ('MANUAL', 'Manual'), ('ADMINISTRATIVO', 'Administrativo')], db_column='platform_empresa_cnae_origem', default='MANUAL', max_length=20)),
                ('ativo', models.BooleanField(db_column='platform_empresa_cnae_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_cnae_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_cnae_atualizado_em')),
                ('cnae', models.ForeignKey(db_column='platform_empresa_cnae_fk_cnae', on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='organizations.cnae')),
                ('empresa', models.ForeignKey(db_column='platform_empresa_cnae_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='cnaes', to='organizations.empresa')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_cnae_tb"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cnae'), name='platform_empresa_cnae_uk'), models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('empresa',), name='platform_empresa_cnae_princ_uk')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaEndereco',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_endereco_id', primary_key=True, serialize=False)),
                ('principal', models.BooleanField(db_column='platform_empresa_endereco_principal', default=False)),
                ('publico', models.BooleanField(db_column='platform_empresa_endereco_publico', default=True)),
                ('ativo', models.BooleanField(db_column='platform_empresa_endereco_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_endereco_criado_em')),
                ('empresa', models.ForeignKey(db_column='platform_empresa_endereco_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_empresa', to='organizations.empresa')),
                ('endereco', models.ForeignKey(db_column='platform_empresa_endereco_fk_endereco', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to='core.enderecocore')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_endereco_tb"',
                'indexes': [models.Index(fields=['empresa', 'principal'], name='platform_empresa_end_idx_princ')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'endereco'), name='platform_empresa_endereco_uk')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPropriedade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_propriedade_id', primary_key=True, serialize=False)),
                ('inicio_em', models.DateTimeField(db_column='platform_empresa_propriedade_inicio_em', default=django.utils.timezone.now)),
                ('fim_em', models.DateTimeField(blank=True, db_column='platform_empresa_propriedade_fim_em', null=True)),
                ('atual', models.BooleanField(db_column='platform_empresa_propriedade_atual', default=True)),
                ('origem', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('REIVINDICACAO', 'Reivindicação'), ('TRANSFERENCIA', 'Transferência'), ('ADMINISTRATIVO', 'Administrativo'), ('MIGRACAO', 'Migração')], db_column='platform_empresa_propriedade_origem', default='CADASTRO', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, db_column='platform_empresa_propriedade_aprovado_em', null=True)),
                ('observacao', models.TextField(blank=True, db_column='platform_empresa_propriedade_observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_propriedade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_propriedade_atualizado_em')),
                ('aprovado_por', models.ForeignKey(blank=True, db_column='platform_empresa_propriedade_fk_aprovado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_column='platform_empresa_propriedade_fk_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='organizations.empresa')),
                ('usuario', models.ForeignKey(db_column='platform_empresa_propriedade_fk_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='propriedades_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"platform"."platform_empresa_propriedade_tb"',
                'constraints': [models.UniqueConstraint(condition=models.Q(('atual', True), ('fim_em__isnull', True)), fields=('empresa',), name='platform_empresa_prop_atual_uk')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaSolicitacao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_solicitacao_id', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, db_column='platform_empresa_solicitacao_cnpj', max_length=14)),
                ('tipo_solicitacao', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('REIVINDICACAO', 'Reivindicação'), ('VINCULO', 'Vínculo'), ('PROPRIEDADE', 'Propriedade'), ('ALTERACAO_CADASTRAL', 'Alteração cadastral'), ('NOVA_CAPACIDADE', 'Nova capacidade')], db_column='platform_empresa_solicitacao_tipo', max_length=30)),
                ('funcao_pretendida', models.CharField(blank=True, db_column='platform_empresa_solicitacao_funcao_pretendida', max_length=60)),
                ('relacao_empresa', models.CharField(blank=True, db_column='platform_empresa_solicitacao_relacao_empresa', max_length=120)),
                ('justificativa', models.TextField(blank=True, db_column='platform_empresa_solicitacao_justificativa')),
                ('documento_comprovacao', models.FileField(blank=True, db_column='platform_empresa_solicitacao_documento_comprovacao', upload_to='empresas/solicitacoes/%Y/%m/')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CORRECAO_SOLICITADA', 'Correção solicitada'), ('CANCELADA', 'Cancelada')], db_column='platform_empresa_solicitacao_status', default='RASCUNHO', max_length=30)),
                ('analisado_em', models.DateTimeField(blank=True, db_column='platform_empresa_solicitacao_analisado_em', null=True)),
                ('motivo_decisao', models.TextField(blank=True, db_column='platform_empresa_solicitacao_motivo_decisao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_solicitacao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_solicitacao_atualizado_em')),
                ('analisado_por', models.ForeignKey(blank=True, db_column='platform_empresa_solicitacao_fk_analisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_empresa_analisadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_column='platform_empresa_solicitacao_fk_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='organizations.empresa')),
                ('usuario_solicitante', models.ForeignKey(db_column='platform_empresa_solicitacao_fk_usuario_solicitante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"platform"."platform_empresa_solicitacao_tb"',
                'indexes': [models.Index(fields=['status'], name='platform_emp_solic_idx_status')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuarioFuncao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_usuario_funcao_id', primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(db_column='platform_empresa_usuario_funcao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_usuario_funcao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_usuario_funcao_atualizado_em')),
                ('empresa_usuario', models.ForeignKey(db_column='platform_empresa_usuario_funcao_fk_empresa_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_vinculadas', to='organizations.empresausuario')),
                ('funcao', models.ForeignKey(db_column='platform_empresa_usuario_funcao_fk_funcao', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='organizations.empresafuncao')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_usuario_funcao_tb"',
                'constraints': [models.UniqueConstraint(fields=('empresa_usuario', 'funcao'), name='platform_emp_usu_funcao_uk')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuarioPermissao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_empresa_usuario_permissao_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='platform_empresa_usuario_permissao_codigo', max_length=60)),
                ('permitido', models.BooleanField(db_column='platform_empresa_usuario_permissao_permitido', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_usuario_permissao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_usuario_permissao_atualizado_em')),
                ('empresa_usuario', models.ForeignKey(db_column='platform_empresa_usuario_permissao_fk_empresa_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_granulares', to='organizations.empresausuario')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_usuario_permissao_tb"',
                'constraints': [models.UniqueConstraint(fields=('empresa_usuario', 'codigo'), name='platform_emp_usu_perm_uk')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCapacidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_usuario_capacidade_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('SUSPENSA', 'Suspensa')], db_column='platform_usuario_capacidade_status', default='PENDENTE', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, db_column='platform_usuario_capacidade_aprovado_em', null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, db_column='platform_usuario_capacidade_motivo_rejeicao')),
                ('ativo', models.BooleanField(db_column='platform_usuario_capacidade_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_usuario_capacidade_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_usuario_capacidade_atualizado_em')),
                ('aprovado_por', models.ForeignKey(blank=True, db_column='platform_usuario_capacidade_fk_aprovado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacidades_usuario_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('capacidade', models.ForeignKey(db_column='platform_usuario_capacidade_fk_capacidade', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_capacidade', to='organizations.capacidade')),
                ('usuario', models.ForeignKey(db_column='platform_usuario_capacidade_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='capacidades_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"platform"."platform_usuario_capacidade_tb"',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'capacidade'), name='platform_usuario_capacidade_uk')],
            },
        ),
    ]
