# Generated by Django 6.0.5 on 2026-07-20 18:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_plano_assinatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratacaoEmpresaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDENTE', max_length=20)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes_empresas_adicionais', to='organizations.assinatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_contratacao_empresa_adicional_tb',
            },
        ),
        migrations.AddField(
            model_name='assinatura',
            name='empresa_contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_contratantes', to='organizations.empresa'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='periodicidade',
            field=models.CharField(choices=[('MENSAL', 'Mensal')], default='MENSAL', max_length=20),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='tipo_contratante',
            field=models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PF', max_length=2),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='valor_mensal_contratado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='codigo',
            field=models.CharField(blank=True, choices=[('GRATUITO', 'Gratuito'), ('BRONZE', 'Bronze'), ('PRATA', 'Prata'), ('OURO', 'Ouro'), ('PREMIUM', 'Premium'), ('EMPRESARIAL', 'Empresarial'), ('CORPORATIVO', 'Corporativo'), ('PERSONALIZADO', 'Personalizado')], max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='empresas_inclusas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plano',
            name='ilimitado_empresas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='ilimitado_servicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_servicos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_empresa_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_mensal_pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_mensal_pj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_empresas',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='assinatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa_contratante__isnull', True), ('tipo_contratante', 'PF')), models.Q(('empresa_contratante__isnull', False), ('tipo_contratante', 'PJ')), _connector='OR'), name='platform_assinatura_tipo_empresa_ck'),
        ),
        migrations.AddIndex(
            model_name='contratacaoempresaadicional',
            index=models.Index(fields=['assinatura', 'status', 'fim'], name='plat_cont_emp_add_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratacaoempresaadicional',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='platform_cont_emp_add_qtd_ck'),
        ),
        migrations.AddConstraint(
            model_name='contratacaoempresaadicional',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario', Decimal('50.00'))), name='platform_cont_emp_add_valor_ck'),
        ),
    ]
