# Generated by Django 6.0.5 on 2026-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_seed_planos_comerciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='limite_servicos_contratado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
