# Generated by Django 6.0.5 on 2026-08-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_usuariolimitepersonalizado'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modalidade_comercial',
            field=models.CharField(blank=True, choices=[('VAREJO', 'Varejo'), ('ATACADO', 'Atacado'), ('AMBOS', 'Varejo e atacado')], db_column='platform_empresa_modalidade_comercial', help_text='Aplicável quando a empresa comercializa produtos.', max_length=10, verbose_name='modalidade comercial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subcategoria_empresa',
            field=models.ForeignKey(blank=True, db_column='platform_empresa_subcategoria_empresa_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='taxonomy.subcategoria', verbose_name='subcategoria da empresa'),
        ),
    ]
