# Generated by Django 6.0.5 on 2026-08-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_empresa_modalidade_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='atuacao',
            field=models.CharField(blank=True, choices=[('COMERCIO', 'Comércio'), ('SERVICOS', 'Serviços'), ('COMERCIO_E_SERVICOS', 'Comércio e serviços')], db_column='platform_empresa_atuacao', help_text='Classificação do negócio; não concede capacidades operacionais.', max_length=20, null=True, verbose_name='atuação'),
        ),
    ]
