# Generated by Django 6.0.5 on 2026-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_empresa_origem_e_importacao_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem_social',
            field=models.ImageField(blank=True, db_column='platform_empresa_imagem_social', help_text='Recomendado: 1200 x 630 px. JPG, PNG ou WEBP.', upload_to='empresas/social/', verbose_name='imagem para compartilhamento'),
        ),
    ]
