# Generated by Django 6.0.5 on 2026-09-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_empresa_imagem_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='atividades',
            field=models.JSONField(blank=True, db_column='platform_cnae_atividades', default=list),
        ),
        migrations.AddField(
            model_name='cnae',
            name='classe_descricao',
            field=models.TextField(blank=True, db_column='platform_cnae_classe_descricao'),
        ),
        migrations.AddField(
            model_name='cnae',
            name='classe_observacoes',
            field=models.JSONField(blank=True, db_column='platform_cnae_classe_observacoes', default=list),
        ),
        migrations.AddField(
            model_name='cnae',
            name='divisao_descricao',
            field=models.CharField(blank=True, db_column='platform_cnae_divisao_descricao', max_length=255),
        ),
        migrations.AddField(
            model_name='cnae',
            name='fonte',
            field=models.CharField(blank=True, db_column='platform_cnae_fonte', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cnae',
            name='grupo_descricao',
            field=models.CharField(blank=True, db_column='platform_cnae_grupo_descricao', max_length=500),
        ),
        migrations.AddField(
            model_name='cnae',
            name='observacoes',
            field=models.JSONField(blank=True, db_column='platform_cnae_observacoes', default=list),
        ),
        migrations.AddField(
            model_name='cnae',
            name='secao_descricao',
            field=models.CharField(blank=True, db_column='platform_cnae_secao_descricao', max_length=255),
        ),
        migrations.AddField(
            model_name='cnae',
            name='versao',
            field=models.CharField(blank=True, db_column='platform_cnae_versao', default='', max_length=30),
        ),
    ]
