# Generated by Django 6.0.5 on 2026-09-11 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_cnae_atividades_cnae_classe_descricao_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaCNAE',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='platform_subcategoria_cnae_id', primary_key=True, serialize=False)),
                ('relevancia', models.PositiveSmallIntegerField(db_column='platform_subcategoria_cnae_relevancia', default=100)),
                ('principal', models.BooleanField(db_column='platform_subcategoria_cnae_principal', default=False)),
                ('revisado', models.BooleanField(db_column='platform_subcategoria_cnae_revisado', default=False)),
                ('ativo', models.BooleanField(db_column='platform_subcategoria_cnae_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_subcategoria_cnae_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_subcategoria_cnae_atualizado_em')),
                ('cnae', models.ForeignKey(db_column='platform_subcategoria_cnae_fk_cnae', on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias_mapeadas', to='organizations.cnae', verbose_name='CNAE')),
                ('subcategoria', models.ForeignKey(db_column='platform_subcategoria_cnae_fk_subcategoria', on_delete=django.db.models.deletion.CASCADE, related_name='cnaes_mapeados', to='taxonomy.subcategoria', verbose_name='tipo de estabelecimento')),
            ],
            options={
                'db_table': '"platform"."platform_subcategoria_cnae_tb"',
                'ordering': ['subcategoria__categoria__nome', 'subcategoria__nome', '-relevancia', 'cnae__codigo'],
                'indexes': [models.Index(fields=['subcategoria', 'ativo'], name='platform_subcat_cnae_sub_idx'), models.Index(fields=['cnae', 'ativo'], name='platform_subcat_cnae_cnae_idx'), models.Index(fields=['cnae', 'relevancia'], name='platform_subcat_cnae_rel_idx')],
                'constraints': [models.UniqueConstraint(fields=('subcategoria', 'cnae'), name='platform_subcategoria_cnae_uk')],
            },
        ),
    ]
