# Generated by Django 6.0.5 on 2026-09-14 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_subcategoriacnae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaLead',
            fields=[
                ('id', models.BigAutoField(db_column='platform_empresa_lead_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='platform_empresa_lead_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='platform_empresa_lead_nome', max_length=160, verbose_name='nome')),
                ('email', models.EmailField(blank=True, db_column='platform_empresa_lead_email', max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, db_column='platform_empresa_lead_telefone', max_length=20, verbose_name='telefone')),
                ('assunto', models.CharField(db_column='platform_empresa_lead_assunto', max_length=180, verbose_name='assunto')),
                ('mensagem', models.TextField(db_column='platform_empresa_lead_mensagem', verbose_name='mensagem')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('FORMULARIO', 'Formulário'), ('PAINEL', 'Painel')], db_column='platform_empresa_lead_canal', default='WHATSAPP', max_length=20, verbose_name='canal')),
                ('origem', models.CharField(choices=[('EMPRESA', 'Página da empresa'), ('SERVICO', 'Serviço'), ('PRODUTO', 'Produto'), ('PUBLICIDADE', 'Publicidade'), ('BUSCA', 'Busca'), ('AGENDA', 'Agenda'), ('OUTRO', 'Outro')], db_column='platform_empresa_lead_origem', default='EMPRESA', max_length=20, verbose_name='origem')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('VISUALIZADO', 'Visualizado'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido'), ('SPAM', 'Spam')], db_column='platform_empresa_lead_status', default='NOVO', max_length=24, verbose_name='status')),
                ('pagina_origem', models.CharField(blank=True, db_column='platform_empresa_lead_pagina_origem', max_length=300, verbose_name='página de origem')),
                ('url_origem', models.URLField(blank=True, db_column='platform_empresa_lead_url_origem', max_length=500, verbose_name='URL de origem')),
                ('referrer', models.URLField(blank=True, db_column='platform_empresa_lead_referrer', max_length=500, verbose_name='referência')),
                ('utm_source', models.CharField(blank=True, db_column='platform_empresa_lead_utm_source', max_length=120)),
                ('utm_medium', models.CharField(blank=True, db_column='platform_empresa_lead_utm_medium', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, db_column='platform_empresa_lead_utm_campaign', max_length=180)),
                ('utm_content', models.CharField(blank=True, db_column='platform_empresa_lead_utm_content', max_length=180)),
                ('utm_term', models.CharField(blank=True, db_column='platform_empresa_lead_utm_term', max_length=180)),
                ('session_id', models.CharField(blank=True, db_column='platform_empresa_lead_session_id', max_length=120)),
                ('ga_client_id', models.CharField(blank=True, db_column='platform_empresa_lead_ga_client_id', max_length=120)),
                ('ga_session_id', models.CharField(blank=True, db_column='platform_empresa_lead_ga_session_id', max_length=120)),
                ('ip_hash', models.CharField(blank=True, db_column='platform_empresa_lead_ip_hash', max_length=64)),
                ('user_agent', models.CharField(blank=True, db_column='platform_empresa_lead_user_agent', max_length=500)),
                ('whatsapp_destino', models.CharField(blank=True, db_column='platform_empresa_lead_whatsapp_destino', max_length=20)),
                ('mensagem_whatsapp', models.TextField(blank=True, db_column='platform_empresa_lead_mensagem_whatsapp')),
                ('whatsapp_aberto_em', models.DateTimeField(blank=True, db_column='platform_empresa_lead_whatsapp_aberto_em', null=True)),
                ('visualizado_em', models.DateTimeField(blank=True, db_column='platform_empresa_lead_visualizado_em', null=True)),
                ('atendimento_em', models.DateTimeField(blank=True, db_column='platform_empresa_lead_atendimento_em', null=True)),
                ('convertido_em', models.DateTimeField(blank=True, db_column='platform_empresa_lead_convertido_em', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='platform_empresa_lead_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='platform_empresa_lead_atualizado_em')),
                ('empresa', models.ForeignKey(db_column='platform_empresa_lead_empresa_fk', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.empresa', verbose_name='empresa')),
                ('responsavel', models.ForeignKey(blank=True, db_column='platform_empresa_lead_responsavel_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_empresa_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('usuario', models.ForeignKey(blank=True, db_column='platform_empresa_lead_usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_empresa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'db_table': '"platform"."platform_empresa_lead_tb"',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['empresa', 'status', 'criado_em'], name='platform_lead_emp_status_idx'), models.Index(fields=['empresa', 'canal', 'criado_em'], name='platform_lead_emp_canal_idx'), models.Index(fields=['responsavel', 'status'], name='platform_lead_resp_status_idx'), models.Index(fields=['utm_campaign'], name='platform_lead_campaign_idx')],
            },
        ),
    ]
