# Generated by Django 6.0.5 on 2026-07-20 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_contratacaoempresaadicional_and_more'),
        ('services', '0002_servico_qr_ativo_servico_qr_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('prestador_tipo', 'PESSOA_FISICA')), models.Q(('empresa__isnull', False), ('prestador_tipo', 'EMPRESA')), _connector='OR'), name='services_servico_prestador_empresa_ck'),
        ),
    ]
