# Generated by Django 6.0.5 on 2026-07-22 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servico_services_servico_prestador_empresa_ck'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProfissional',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_area_profissional_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='services_area_profissional_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='services_area_profissional_slug', max_length=180)),
                ('descricao', models.TextField(blank=True, db_column='services_area_profissional_descricao')),
                ('ordem', models.PositiveIntegerField(db_column='services_area_profissional_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='services_area_profissional_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_area_profissional_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_area_profissional_atualizado_em')),
                ('setor', models.ForeignKey(db_column='services_area_profissional_fk_setor', on_delete=django.db.models.deletion.PROTECT, related_name='areas_profissionais', to='services.setor')),
            ],
            options={
                'db_table': '"services"."services_area_profissional_tb"',
                'ordering': ['setor__nome', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='profissao',
            name='area',
            field=models.ForeignKey(blank=True, db_column='services_profissao_fk_area', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissoes', to='services.areaprofissional'),
        ),
        migrations.AddIndex(
            model_name='areaprofissional',
            index=models.Index(fields=['setor', 'slug'], name='services_area_prof_idx_slug'),
        ),
        migrations.AddConstraint(
            model_name='areaprofissional',
            constraint=models.UniqueConstraint(fields=('setor', 'nome'), name='services_area_profissional_setor_nome_uk'),
        ),
    ]
