# Generated by Django 6.0.5 on 2026-07-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_areaprofissional_profissao_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='area',
            field=models.ForeignKey(blank=True, db_column='services_servico_fk_area', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.areaprofissional'),
        ),
    ]
