# Generated by Django 6.0.5 on 2026-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servico_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoimagem',
            name='credito',
            field=models.CharField(blank=True, db_column='services_servico_imagem_credito', max_length=160),
        ),
        migrations.AddField(
            model_name='servicoimagem',
            name='texto_alternativo',
            field=models.CharField(blank=True, db_column='services_servico_imagem_alt', max_length=220),
        ),
    ]
