# Generated by Django 6.0.5 on 2026-08-03 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preservar_vinculos_existentes(apps, schema_editor):
    Servico = apps.get_model('services', 'Servico')
    Vinculo = apps.get_model('services', 'ProfissaoTipoServico')
    pares = Servico._base_manager.values_list(
        'profissao_id', 'tipo_servico_id',
    ).distinct()
    Vinculo.objects.bulk_create([
        Vinculo(profissao_id=profissao_id, tipo_servico_id=tipo_id)
        for profissao_id, tipo_id in pares
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicoimagem_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissaoTipoServico',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_profissao_tipo_servico_id', primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(db_column='services_profissao_tipo_servico_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='services_profissao_tipo_servico_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_profissao_tipo_servico_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_profissao_tipo_servico_atualizado_em')),
                ('profissao', models.ForeignKey(db_column='services_profissao_tipo_servico_fk_profissao', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_tipos_servico', to='services.profissao')),
                ('tipo_servico', models.ForeignKey(db_column='services_profissao_tipo_servico_fk_tipo_servico', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_profissoes', to='services.tiposervico')),
            ],
            options={
                'db_table': '"services"."services_profissao_tipo_servico_tb"',
                'ordering': ['ordem', 'tipo_servico__nome'],
            },
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='profissoes',
            field=models.ManyToManyField(blank=True, related_name='tipos_servico', through='services.ProfissaoTipoServico', to='services.profissao'),
        ),
        migrations.AddIndex(
            model_name='profissaotiposervico',
            index=models.Index(fields=['profissao', 'ativo'], name='services_prof_tipo_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='profissaotiposervico',
            constraint=models.UniqueConstraint(fields=('profissao', 'tipo_servico'), name='services_profissao_tipo_servico_uk'),
        ),
        migrations.RunPython(preservar_vinculos_existentes, migrations.RunPython.noop),
    ]
