# Generated by Django 6.0.5 on 2026-08-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_profissao_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, db_column='services_servico_fk_tipo_servico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.tiposervico'),
        ),
    ]
