# Generated by Django 6.0.5 on 2026-08-28 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servico_tipo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBOFamilia',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_familia_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='services_cbo_familia_codigo', max_length=4, unique=True)),
                ('titulo', models.CharField(db_column='services_cbo_familia_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_familia_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_familia_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_familia_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_cbo_familia_tb"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CBOGrandeGrupo',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_grande_grupo_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='services_cbo_grande_grupo_codigo', max_length=2, unique=True)),
                ('titulo', models.CharField(db_column='services_cbo_grande_grupo_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_grande_grupo_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_grande_grupo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_grande_grupo_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_cbo_grande_grupo_tb"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CBOSubgrupo',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_subgrupo_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='services_cbo_subgrupo_codigo', max_length=3, unique=True)),
                ('titulo', models.CharField(db_column='services_cbo_subgrupo_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_subgrupo_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_subgrupo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_subgrupo_atualizado_em')),
            ],
            options={
                'db_table': '"services"."services_cbo_subgrupo_tb"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CBOOcupacao',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_ocupacao_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='services_cbo_ocupacao_codigo', max_length=6, unique=True)),
                ('titulo', models.CharField(db_column='services_cbo_ocupacao_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_ocupacao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_ocupacao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_ocupacao_atualizado_em')),
                ('familia', models.ForeignKey(db_column='services_cbo_ocupacao_fk_familia', on_delete=django.db.models.deletion.PROTECT, related_name='ocupacoes', to='services.cbofamilia')),
            ],
            options={
                'db_table': '"services"."services_cbo_ocupacao_tb"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CBOSinonimo',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_sinonimo_id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='services_cbo_sinonimo_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_sinonimo_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_sinonimo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_sinonimo_atualizado_em')),
                ('ocupacao', models.ForeignKey(db_column='services_cbo_sinonimo_fk_ocupacao', on_delete=django.db.models.deletion.CASCADE, related_name='sinonimos', to='services.cboocupacao')),
            ],
            options={
                'db_table': '"services"."services_cbo_sinonimo_tb"',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='cbofamilia',
            name='subgrupo',
            field=models.ForeignKey(db_column='services_cbo_familia_fk_subgrupo', on_delete=django.db.models.deletion.PROTECT, related_name='familias', to='services.cbosubgrupo'),
        ),
        migrations.CreateModel(
            name='CBOSubgrupoPrincipal',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_cbo_subgrupo_principal_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='services_cbo_subgrupo_principal_codigo', max_length=2, unique=True)),
                ('titulo', models.CharField(db_column='services_cbo_subgrupo_principal_titulo', max_length=255)),
                ('ativo', models.BooleanField(db_column='services_cbo_subgrupo_principal_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_cbo_subgrupo_principal_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_cbo_subgrupo_principal_atualizado_em')),
                ('grande_grupo', models.ForeignKey(db_column='services_cbo_subgrupo_principal_fk_grande_grupo', on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos_principais', to='services.cbograndegrupo')),
            ],
            options={
                'db_table': '"services"."services_cbo_subgrupo_principal_tb"',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cbosubgrupo',
            name='subgrupo_principal',
            field=models.ForeignKey(db_column='services_cbo_subgrupo_fk_subgrupo_principal', on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='services.cbosubgrupoprincipal'),
        ),
        migrations.CreateModel(
            name='ProfissaoCBO',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(db_column='services_profissao_cbo_id', primary_key=True, serialize=False)),
                ('principal', models.BooleanField(db_column='services_profissao_cbo_principal', default=False)),
                ('confianca', models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], db_column='services_profissao_cbo_confianca', max_length=8)),
                ('origem', models.CharField(blank=True, db_column='services_profissao_cbo_origem', max_length=80)),
                ('observacao', models.TextField(blank=True, db_column='services_profissao_cbo_observacao')),
                ('ativo', models.BooleanField(db_column='services_profissao_cbo_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='services_profissao_cbo_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='services_profissao_cbo_atualizado_em')),
                ('ocupacao', models.ForeignKey(db_column='services_profissao_cbo_fk_ocupacao', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_profissoes', to='services.cboocupacao')),
                ('profissao', models.ForeignKey(db_column='services_profissao_cbo_fk_profissao', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_cbo', to='services.profissao')),
            ],
            options={
                'db_table': '"services"."services_profissao_cbo_tb"',
                'ordering': ['profissao__nome', '-principal', 'ocupacao__codigo'],
            },
        ),
        migrations.AddField(
            model_name='profissao',
            name='ocupacoes_cbo',
            field=models.ManyToManyField(blank=True, related_name='profissoes', through='services.ProfissaoCBO', to='services.cboocupacao'),
        ),
        migrations.AddIndex(
            model_name='cboocupacao',
            index=models.Index(fields=['familia', 'codigo'], name='services_cbo_oc_fam_cod_idx'),
        ),
        migrations.AddIndex(
            model_name='cbosinonimo',
            index=models.Index(fields=['ocupacao', 'ativo'], name='services_cbo_sin_oc_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbosinonimo',
            constraint=models.UniqueConstraint(fields=('ocupacao', 'titulo'), name='services_cbo_sinonimo_ocup_titulo_uk'),
        ),
        migrations.AddIndex(
            model_name='cbofamilia',
            index=models.Index(fields=['subgrupo', 'codigo'], name='services_cbo_fam_sg_cod_idx'),
        ),
        migrations.AddIndex(
            model_name='cbosubgrupoprincipal',
            index=models.Index(fields=['grande_grupo', 'codigo'], name='services_cbo_sgp_gg_cod_idx'),
        ),
        migrations.AddIndex(
            model_name='cbosubgrupo',
            index=models.Index(fields=['subgrupo_principal', 'codigo'], name='services_cbo_sg_sgp_cod_idx'),
        ),
        migrations.AddIndex(
            model_name='profissaocbo',
            index=models.Index(fields=['profissao', 'ativo'], name='services_prof_cbo_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='profissaocbo',
            index=models.Index(fields=['ocupacao', 'ativo'], name='services_cbo_prof_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='profissaocbo',
            constraint=models.UniqueConstraint(fields=('profissao', 'ocupacao'), name='services_profissao_cbo_prof_ocup_uk'),
        ),
        migrations.AddConstraint(
            model_name='profissaocbo',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('profissao',), name='services_profissao_cbo_principal_uk'),
        ),
    ]
