# Generated by Django 6.0.5 on 2026-08-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_cbofamilia_cbograndegrupo_cbosubgrupo_cboocupacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='forma_cobranca',
            field=models.ForeignKey(blank=True, db_column='services_servico_fk_forma_cobranca', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.formacobranca'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='profissao',
            field=models.ForeignKey(blank=True, db_column='services_servico_fk_profissao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.profissao'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='setor',
            field=models.ForeignKey(blank=True, db_column='services_servico_fk_setor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='services.setor'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(blank=True, db_column='services_servico_titulo', max_length=160),
        ),
    ]
