# Generated by Django 6.0.6 on 2026-07-10 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_estado_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('sigla', models.CharField(max_length=2, verbose_name='sigla')),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, verbose_name='código IBGE')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': '"platform"."platform_estado_tb"',
                'ordering': ['pais__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_cidade_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, verbose_name='código IBGE')),
                ('estado', models.ForeignKey(db_column='platform_estado_fk', on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='locations.estado', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'db_table': '"platform"."platform_cidade_tb"',
                'ordering': ['estado__sigla', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_pais_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('nome_oficial', models.CharField(blank=True, max_length=160, verbose_name='nome oficial')),
                ('codigo_iso_2', models.CharField(max_length=2, unique=True, verbose_name='código ISO 2')),
                ('codigo_iso_3', models.CharField(max_length=3, unique=True, verbose_name='código ISO 3')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'db_table': '"platform"."platform_pais_tb"',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='platform_pais_nome_idx'), models.Index(fields=['codigo_iso_2'], name='platform_pais_iso2_idx'), models.Index(fields=['ativo'], name='platform_pais_ativo_idx')],
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(db_column='platform_pais_fk', on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='locations.pais', verbose_name='país'),
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('removido_em', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('id', models.BigAutoField(db_column='platform_bairro_id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('cidade', models.ForeignKey(db_column='platform_cidade_fk', on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='locations.cidade', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
                'db_table': '"platform"."platform_bairro_tb"',
                'ordering': ['cidade__nome', 'nome'],
                'indexes': [models.Index(fields=['cidade', 'nome'], name='platform_bairro_nome_idx'), models.Index(fields=['ativo'], name='platform_bairro_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('cidade', 'nome'), name='platform_bairro_cidade_nome_uk')],
            },
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['estado', 'nome'], name='platform_cidade_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['codigo_ibge'], name='platform_cidade_ibge_idx'),
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['ativo'], name='platform_cidade_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('estado', 'nome'), name='platform_cidade_estado_nome_uk'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['pais', 'nome'], name='platform_estado_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['pais', 'sigla'], name='platform_estado_sigla_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['ativo'], name='platform_estado_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('pais', 'sigla'), name='platform_estado_pais_sigla_uk'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('pais', 'nome'), name='platform_estado_pais_nome_uk'),
        ),
    ]
