# Generated by Django 6.0.5 on 2026-07-19 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('government', '0001_initial'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS media;', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(db_column='media_canal_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_canal_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_canal_nome', max_length=150)),
                ('slug', models.SlugField(blank=True, db_column='media_canal_slug', max_length=180, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='media_canal_descricao')),
                ('plataforma', models.CharField(db_column='media_canal_plataforma', default='YOUTUBE', max_length=40)),
                ('identificador_externo', models.CharField(blank=True, db_column='media_canal_identificador_externo', max_length=150)),
                ('url', models.URLField(blank=True, db_column='media_canal_url')),
                ('logotipo', models.ImageField(blank=True, db_column='media_canal_logotipo', upload_to='media/canais/logos/')),
                ('capa', models.ImageField(blank=True, db_column='media_canal_capa', upload_to='media/canais/capas/')),
                ('oficial', models.BooleanField(db_column='media_canal_oficial', default=False)),
                ('ativo', models.BooleanField(db_column='media_canal_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_canal_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_canal_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_canal_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_canal_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(db_column='media_programa_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_programa_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_programa_nome', max_length=160)),
                ('slug', models.SlugField(blank=True, db_column='media_programa_slug', max_length=190, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='media_programa_descricao')),
                ('categoria', models.CharField(blank=True, db_column='media_programa_categoria', max_length=80)),
                ('imagem', models.ImageField(blank=True, db_column='media_programa_imagem', upload_to='media/programas/')),
                ('frequencia', models.CharField(blank=True, db_column='media_programa_frequencia', max_length=80)),
                ('duracao_media', models.DurationField(blank=True, db_column='media_programa_duracao_media', null=True)),
                ('ativo', models.BooleanField(db_column='media_programa_ativo', default=True)),
                ('apresentador', models.ForeignKey(blank=True, db_column='media_programa_fk_apresentador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_apresentados', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(db_column='media_programa_fk_canal', on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='media.canal')),
                ('produtor', models.ForeignKey(blank=True, db_column='media_programa_fk_produtor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_produzidos', to=settings.AUTH_USER_MODEL)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_programa_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_programa_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_programa_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_programa_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(db_column='media_pauta_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_pauta_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='media_pauta_titulo', max_length=200)),
                ('descricao', models.TextField(blank=True, db_column='media_pauta_descricao')),
                ('convidados', models.TextField(blank=True, db_column='media_pauta_convidados')),
                ('roteiro', models.TextField(blank=True, db_column='media_pauta_roteiro')),
                ('data_prevista', models.DateTimeField(blank=True, db_column='media_pauta_data_prevista', null=True)),
                ('status', models.CharField(choices=[('IDEIA', 'Ideia'), ('APROVADA', 'Aprovada'), ('PRODUCAO', 'Produção'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_column='media_pauta_status', default='IDEIA', max_length=20)),
                ('observacoes', models.TextField(blank=True, db_column='media_pauta_observacoes')),
                ('ativo', models.BooleanField(db_column='media_pauta_ativo', default=True)),
                ('responsavel', models.ForeignKey(db_column='media_pauta_fk_responsavel', on_delete=django.db.models.deletion.PROTECT, related_name='pautas_media', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(db_column='media_pauta_fk_programa', on_delete=django.db.models.deletion.PROTECT, related_name='pautas', to='media.programa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_pauta_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_pauta_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_pauta_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_pauta_tb"',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(db_column='media_temporada_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_temporada_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveIntegerField(db_column='media_temporada_numero')),
                ('titulo', models.CharField(blank=True, db_column='media_temporada_titulo', max_length=160)),
                ('descricao', models.TextField(blank=True, db_column='media_temporada_descricao')),
                ('data_inicial', models.DateField(blank=True, db_column='media_temporada_data_inicial', null=True)),
                ('data_final', models.DateField(blank=True, db_column='media_temporada_data_final', null=True)),
                ('ativo', models.BooleanField(db_column='media_temporada_ativo', default=True)),
                ('programa', models.ForeignKey(db_column='media_temporada_fk_programa', on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='media.programa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_temporada_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_temporada_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_temporada_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_temporada_tb"',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(db_column='media_episodio_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_episodio_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='media_episodio_titulo', max_length=200)),
                ('slug', models.SlugField(blank=True, db_column='media_episodio_slug', max_length=230, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='media_episodio_descricao')),
                ('numero', models.PositiveIntegerField(blank=True, db_column='media_episodio_numero', null=True)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('PODCAST', 'Podcast'), ('ENTREVISTA', 'Entrevista'), ('TRANSMISSAO', 'Transmissão'), ('SHORT', 'Short'), ('ESPECIAL', 'Especial')], db_column='media_episodio_tipo', default='VIDEO', max_length=20)),
                ('youtube_url', models.URLField(blank=True, db_column='media_episodio_youtube_url', max_length=500)),
                ('video_id', models.CharField(blank=True, db_column='media_episodio_video_id', max_length=20)),
                ('thumbnail', models.URLField(blank=True, db_column='media_episodio_thumbnail', max_length=500)),
                ('duracao', models.DurationField(blank=True, db_column='media_episodio_duracao', null=True)),
                ('data_gravacao', models.DateTimeField(blank=True, db_column='media_episodio_data_gravacao', null=True)),
                ('data_programada', models.DateTimeField(blank=True, db_column='media_episodio_data_programada', null=True)),
                ('publicado_em', models.DateTimeField(blank=True, db_column='media_episodio_publicado_em', null=True)),
                ('status', models.CharField(choices=[('PAUTA', 'Pauta'), ('PRODUCAO', 'Produção'), ('GRAVADO', 'Gravado'), ('EDITANDO', 'Editando'), ('AGENDADO', 'Agendado'), ('AO_VIVO', 'Ao vivo'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'Cancelado')], db_column='media_episodio_status', default='PAUTA', max_length=20)),
                ('destaque', models.BooleanField(db_column='media_episodio_destaque', default=False)),
                ('ativo', models.BooleanField(db_column='media_episodio_ativo', default=True)),
                ('programa', models.ForeignKey(db_column='media_episodio_fk_programa', on_delete=django.db.models.deletion.PROTECT, related_name='episodios', to='media.programa')),
                ('temporada', models.ForeignKey(blank=True, db_column='media_episodio_fk_temporada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios', to='media.temporada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_episodio_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_episodio_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_episodio_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_episodio_tb"',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transmissao',
            fields=[
                ('id', models.BigAutoField(db_column='media_transmissao_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_transmissao_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('data_prevista', models.DateTimeField(blank=True, db_column='media_transmissao_data_prevista', null=True)),
                ('inicio', models.DateTimeField(blank=True, db_column='media_transmissao_inicio', null=True)),
                ('fim', models.DateTimeField(blank=True, db_column='media_transmissao_fim', null=True)),
                ('url_ao_vivo', models.URLField(blank=True, db_column='media_transmissao_url', max_length=500)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('AO_VIVO', 'Ao vivo'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], db_column='media_transmissao_status', default='AGENDADA', max_length=20)),
                ('ativo', models.BooleanField(db_column='media_transmissao_ativo', default=True)),
                ('acao_publica', models.ForeignKey(blank=True, db_column='media_transmissao_fk_acao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes', to='government.acaopublica')),
                ('disputa', models.ForeignKey(blank=True, db_column='media_transmissao_fk_disputa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes', to='sports.disputa')),
                ('episodio', models.OneToOneField(db_column='media_transmissao_fk_episodio', on_delete=django.db.models.deletion.CASCADE, related_name='transmissao', to='media.episodio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_transmissao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_transmissao_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_transmissao_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_transmissao_tb"',
            },
        ),
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('programa', 'numero'), name='media_temporada_programa_num_uk'),
        ),
        migrations.AddIndex(
            model_name='episodio',
            index=models.Index(fields=['status', 'ativo'], name='media_episodio_status_idx'),
        ),
    ]
