# Generated by Django 6.0.5 on 2026-07-20 10:22

import apps.core.domain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='capa',
            field=models.ImageField(blank=True, db_column='media_canal_capa', upload_to='media/canais/capas/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='canal',
            name='logotipo',
            field=models.ImageField(blank=True, db_column='media_canal_logotipo', upload_to='media/canais/logos/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AlterField(
            model_name='programa',
            name='imagem',
            field=models.ImageField(blank=True, db_column='media_programa_imagem', upload_to='media/programas/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
    ]
