# Generated by Django 6.0.5 on 2026-07-26 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_canal_capa_alter_canal_logotipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRejeicao',
            fields=[
                ('id', models.BigAutoField(db_column='media_motivo_rejeicao_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_motivo_rejeicao_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_motivo_rejeicao_nome', max_length=140)),
                ('descricao', models.TextField(blank=True, db_column='media_motivo_rejeicao_descricao')),
                ('exige_complemento', models.BooleanField(db_column='media_motivo_rejeicao_exige_complemento', default=False)),
                ('ativo', models.BooleanField(db_column='media_motivo_rejeicao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_motivo_rejeicao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_motivo_rejeicao_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_motivo_rejeicao_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_motivo_rejeicao_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaYuBotuka',
            fields=[
                ('id', models.BigAutoField(db_column='media_categoria_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_categoria_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_categoria_nome', max_length=120)),
                ('slug', models.SlugField(blank=True, db_column='media_categoria_slug', editable=False, max_length=150, unique=True)),
                ('icone', models.CharField(blank=True, db_column='media_categoria_icone', max_length=60)),
                ('cor', models.CharField(blank=True, db_column='media_categoria_cor', max_length=20)),
                ('ordem', models.PositiveIntegerField(db_column='media_categoria_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='media_categoria_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_categoria_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_categoria_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_categoria_excluido_em', null=True)),
                ('categoria_pai', models.ForeignKey(blank=True, db_column='media_categoria_fk_pai', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='media.categoriayubotuka')),
            ],
            options={
                'db_table': '"media"."media_categoria_tb"',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(db_column='media_playlist_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_playlist_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_playlist_nome', max_length=160)),
                ('slug', models.SlugField(blank=True, db_column='media_playlist_slug', editable=False, max_length=190, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='media_playlist_descricao')),
                ('thumbnail', models.URLField(blank=True, db_column='media_playlist_thumbnail', max_length=500)),
                ('ordem', models.PositiveIntegerField(db_column='media_playlist_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='media_playlist_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_playlist_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_playlist_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_playlist_excluido_em', null=True)),
                ('canal', models.ForeignKey(db_column='media_playlist_fk_canal', on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to='media.canal')),
                ('categoria', models.ForeignKey(blank=True, db_column='media_playlist_fk_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to='media.categoriayubotuka')),
                ('playlist_pai', models.ForeignKey(blank=True, db_column='media_playlist_fk_pai', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subplaylists', to='media.playlist')),
                ('proprietario', models.ForeignKey(db_column='media_playlist_fk_proprietario', on_delete=django.db.models.deletion.PROTECT, related_name='playlists_yubotuka', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"media"."media_playlist_tb"',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(db_column='media_video_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_video_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='media_video_titulo', max_length=200)),
                ('slug', models.SlugField(blank=True, db_column='media_video_slug', editable=False, max_length=230, unique=True)),
                ('descricao_curta', models.CharField(blank=True, db_column='media_video_descricao_curta', max_length=300)),
                ('descricao', models.TextField(blank=True, db_column='media_video_descricao')),
                ('youtube_url', models.URLField(db_column='media_video_youtube_url', max_length=500)),
                ('video_id', models.CharField(blank=True, db_column='media_video_youtube_id', max_length=20)),
                ('thumbnail', models.URLField(blank=True, db_column='media_video_thumbnail', max_length=500)),
                ('duracao', models.DurationField(blank=True, db_column='media_video_duracao', null=True)),
                ('data_gravacao', models.DateTimeField(blank=True, db_column='media_video_data_gravacao', null=True)),
                ('data_agendamento', models.DateTimeField(blank=True, db_column='media_video_data_agendamento', null=True)),
                ('publicado_em', models.DateTimeField(blank=True, db_column='media_video_publicado_em', null=True)),
                ('destaque', models.BooleanField(db_column='media_video_destaque', default=False)),
                ('publicar_na_home', models.BooleanField(db_column='media_video_publicar_home', default=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CORRECAO', 'Em correção'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], db_column='media_video_status', default='RASCUNHO', max_length=20)),
                ('observacao_rejeicao', models.TextField(blank=True, db_column='media_video_observacao_rejeicao')),
                ('ativo', models.BooleanField(db_column='media_video_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_video_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_video_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_video_excluido_em', null=True)),
                ('autor', models.ForeignKey(blank=True, db_column='media_video_fk_autor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_yubotuka', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(db_column='media_video_fk_canal', on_delete=django.db.models.deletion.PROTECT, related_name='videos_editoriais', to='media.canal')),
                ('categoria', models.ForeignKey(blank=True, db_column='media_video_fk_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='media.categoriayubotuka')),
                ('moderado_por', models.ForeignKey(blank=True, db_column='media_video_fk_moderador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_yubotuka_moderados', to=settings.AUTH_USER_MODEL)),
                ('motivo_rejeicao', models.ForeignKey(blank=True, db_column='media_video_fk_motivo_rejeicao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='media.motivorejeicao')),
                ('programa', models.ForeignKey(blank=True, db_column='media_video_fk_programa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_editoriais', to='media.programa')),
            ],
            options={
                'db_table': '"media"."media_video_tb"',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(db_column='media_playlist_video_id', primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(db_column='media_playlist_video_ordem', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_playlist_video_criado_em')),
                ('adicionado_por', models.ForeignKey(db_column='media_playlist_video_fk_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='videos_adicionados_a_playlist', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(db_column='media_playlist_video_fk_playlist', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='media.playlist')),
                ('video', models.ForeignKey(db_column='media_playlist_video_fk_video', on_delete=django.db.models.deletion.CASCADE, related_name='itens_playlist', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_playlist_video_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEditorial',
            fields=[
                ('id', models.BigAutoField(db_column='media_historico_editorial_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_historico_editorial_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('EDITADO', 'Editado'), ('ENVIADO_ANALISE', 'Enviado para análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('DEVOLVIDO', 'Devolvido para correção'), ('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], db_column='media_historico_editorial_acao', max_length=30)),
                ('status_anterior', models.CharField(blank=True, db_column='media_historico_editorial_status_anterior', max_length=20)),
                ('status_novo', models.CharField(blank=True, db_column='media_historico_editorial_status_novo', max_length=20)),
                ('descricao', models.TextField(blank=True, db_column='media_historico_editorial_descricao')),
                ('ip', models.GenericIPAddressField(blank=True, db_column='media_historico_editorial_ip', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_historico_editorial_criado_em')),
                ('usuario', models.ForeignKey(blank=True, db_column='media_historico_editorial_fk_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historico_editorial_yubotuka', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(db_column='media_historico_editorial_fk_video', on_delete=django.db.models.deletion.CASCADE, related_name='historico_editorial', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_historico_editorial_tb"',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='episodio',
            name='video_editorial',
            field=models.OneToOneField(blank=True, db_column='media_episodio_fk_video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodio_legado', to='media.video'),
        ),
        migrations.AddConstraint(
            model_name='categoriayubotuka',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('categoria_pai', 'nome'), name='media_categoria_pai_nome_uk'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('canal', 'playlist_pai', 'nome'), name='media_playlist_hierarquia_uk'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'ativo'], name='media_video_status_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['autor', 'status'], name='media_video_autor_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.UniqueConstraint(fields=('playlist', 'video'), name='media_playlist_video_uk'),
        ),
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.UniqueConstraint(fields=('playlist', 'ordem'), name='media_playlist_ordem_uk'),
        ),
    ]
