# Generated by Django 6.0.5 on 2026-07-26 18:32

from django.conf import settings
from django.db import migrations


def criar_motivos_iniciais(apps, schema_editor):
    MotivoRejeicao = apps.get_model('media', 'MotivoRejeicao')
    motivos = (
        ('Metadados incompletos', False),
        ('URL ou vídeo indisponível', False),
        ('Conteúdo fora das diretrizes', True),
        ('Direitos autorais ou autorização', True),
        ('Correções editoriais necessárias', True),
        ('Outro motivo', True),
    )
    for nome, exige_complemento in motivos:
        MotivoRejeicao.objects.get_or_create(
            nome=nome,
            defaults={'exige_complemento': exige_complemento, 'ativo': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_migrar_episodios_e_permissoes_yubotuka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(criar_motivos_iniciais, migrations.RunPython.noop),
    ]
