# Generated by Django 6.0.5 on 2026-07-26 18:47

import apps.core.domain
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_seed_motivos_rejeicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentador',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('foto', models.ImageField(blank=True, upload_to='media/pessoas/', validators=[apps.core.domain.validar_imagem_publica])),
                ('biografia', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('site_url', models.URLField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='media_apresentador_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"media"."media_apresentador_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BannerYuBotuka',
            fields=[
                ('id', models.BigAutoField(db_column='media_banner_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=160)),
                ('imagem', models.ImageField(upload_to='media/banners/', validators=[apps.core.domain.validar_imagem_publica])),
                ('link', models.URLField(blank=True, max_length=500)),
                ('posicao', models.CharField(choices=[('HOME', 'Home do BOTUKA'), ('YUBOTUKA', 'Página YuBotuka')], default='YUBOTUKA', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"media"."media_banner_tb"',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('foto', models.ImageField(blank=True, upload_to='media/pessoas/', validators=[apps.core.domain.validar_imagem_publica])),
                ('biografia', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('site_url', models.URLField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='media_convidado_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"media"."media_convidado_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(db_column='media_patrocinador_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('logotipo', models.ImageField(blank=True, upload_to='media/patrocinadores/', validators=[apps.core.domain.validar_imagem_publica])),
                ('descricao', models.TextField(blank=True)),
                ('site_url', models.URLField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"media"."media_patrocinador_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TagYuBotuka',
            fields=[
                ('id', models.BigAutoField(db_column='media_tag_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='media_tag_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='media_tag_nome', max_length=80)),
                ('slug', models.SlugField(blank=True, db_column='media_tag_slug', editable=False, max_length=100, unique=True)),
                ('ativo', models.BooleanField(db_column='media_tag_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='media_tag_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='media_tag_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='media_tag_excluido_em', null=True)),
            ],
            options={
                'db_table': '"media"."media_tag_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='destaque',
            field=models.BooleanField(db_column='media_canal_destaque', default=False),
        ),
        migrations.AddField(
            model_name='canal',
            name='facebook_url',
            field=models.URLField(blank=True, db_column='media_canal_facebook_url', max_length=500),
        ),
        migrations.AddField(
            model_name='canal',
            name='instagram_url',
            field=models.URLField(blank=True, db_column='media_canal_instagram_url', max_length=500),
        ),
        migrations.AddField(
            model_name='canal',
            name='ordem',
            field=models.PositiveIntegerField(db_column='media_canal_ordem', default=0),
        ),
        migrations.AddField(
            model_name='canal',
            name='proprietario',
            field=models.ForeignKey(blank=True, db_column='media_canal_fk_proprietario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canais_yubotuka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canal',
            name='site_url',
            field=models.URLField(blank=True, db_column='media_canal_site_url', max_length=500),
        ),
        migrations.AddField(
            model_name='canal',
            name='tiktok_url',
            field=models.URLField(blank=True, db_column='media_canal_tiktok_url', max_length=500),
        ),
        migrations.AddField(
            model_name='canal',
            name='youtube_url',
            field=models.URLField(blank=True, db_column='media_canal_youtube_url', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='arquivado_por',
            field=models.ForeignKey(blank=True, db_column='media_video_fk_arquivador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_yubotuka_arquivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='classificacao',
            field=models.CharField(choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], db_column='media_video_classificacao', default='L', max_length=3),
        ),
        migrations.AddField(
            model_name='video',
            name='conteudo_infantil',
            field=models.BooleanField(db_column='media_video_conteudo_infantil', default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='descricao_seo',
            field=models.CharField(blank=True, db_column='media_video_descricao_seo', max_length=160),
        ),
        migrations.AddField(
            model_name='video',
            name='formato',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical'), ('QUADRADO', 'Quadrado')], db_column='media_video_formato', default='HORIZONTAL', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='idioma',
            field=models.CharField(choices=[('PT_BR', 'Português (Brasil)'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('LIBRAS', 'Libras'), ('OUTRO', 'Outro')], db_column='media_video_idioma', default='PT_BR', max_length=12),
        ),
        migrations.AddField(
            model_name='video',
            name='imagem_compartilhamento',
            field=models.URLField(blank=True, db_column='media_video_imagem_compartilhamento', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='motivo_arquivamento',
            field=models.TextField(blank=True, db_column='media_video_motivo_arquivamento'),
        ),
        migrations.AddField(
            model_name='video',
            name='numero_episodio',
            field=models.PositiveIntegerField(blank=True, db_column='media_video_numero_episodio', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='origem',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube')], db_column='media_video_origem', default='YOUTUBE', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='permitir_comentarios',
            field=models.BooleanField(db_column='media_video_permitir_comentarios', default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='publico',
            field=models.BooleanField(db_column='media_video_publico', default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status_antes_arquivamento',
            field=models.CharField(blank=True, db_column='media_video_status_antes_arquivamento', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='temporada',
            field=models.ForeignKey(blank=True, db_column='media_video_fk_temporada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_editoriais', to='media.temporada'),
        ),
        migrations.AddField(
            model_name='video',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Vídeo'), ('SHORT', 'Short'), ('LIVE', 'Live'), ('PODCAST', 'Podcast'), ('ENTREVISTA', 'Entrevista'), ('ESPECIAL', 'Especial')], db_column='media_video_tipo', default='VIDEO', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo_seo',
            field=models.CharField(blank=True, db_column='media_video_titulo_seo', max_length=70),
        ),
        migrations.AlterField(
            model_name='historicoeditorial',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Criado'), ('EDITADO', 'Editado'), ('ENVIADO_ANALISE', 'Enviado para análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('DEVOLVIDO', 'Devolvido para correção'), ('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado'), ('RESTAURADO', 'Restaurado'), ('PLAYLISTS_ALTERADAS', 'Playlists alteradas'), ('ORDEM_ALTERADA', 'Ordem alterada'), ('DESTAQUE_ALTERADO', 'Destaque alterado')], db_column='media_historico_editorial_acao', max_length=30),
        ),
        migrations.CreateModel(
            name='ConfiguracaoYuBotuka',
            fields=[
                ('id', models.BigAutoField(db_column='media_configuracao_id', primary_key=True, serialize=False)),
                ('titulo_publico', models.CharField(default='YuBotuka', max_length=120)),
                ('descricao_publica', models.CharField(blank=True, max_length=240)),
                ('quantidade_home', models.PositiveSmallIntegerField(default=6)),
                ('quantidade_pagina', models.PositiveSmallIntegerField(default=12)),
                ('exibir_categorias', models.BooleanField(default=True)),
                ('exibir_playlists', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_yubotuka', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"media"."media_configuracao_tb"',
            },
        ),
        migrations.CreateModel(
            name='DestaqueEditorial',
            fields=[
                ('id', models.BigAutoField(db_column='media_destaque_id', primary_key=True, serialize=False)),
                ('posicao', models.CharField(choices=[('HOME', 'Home principal'), ('YUBOTUKA', 'Página YuBotuka'), ('CANAL', 'Canal'), ('CATEGORIA', 'Categoria'), ('PROGRAMA', 'Programa'), ('PLAYLIST', 'Playlist')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques_editoriais', to='media.canal')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques_editoriais', to='media.categoriayubotuka')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques_editoriais', to='media.playlist')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques_editoriais', to='media.programa')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_destaque', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_destaque_tb"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoApresentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('apresentador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apresentadores_videos', to='media.apresentador')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_apresentadores', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_video_apresentador_tb"',
                'constraints': [models.UniqueConstraint(fields=('video', 'apresentador'), name='media_video_apresentador_uk')],
            },
        ),
        migrations.CreateModel(
            name='VideoConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convidados_videos', to='media.convidado')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_convidados', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_video_convidado_tb"',
                'constraints': [models.UniqueConstraint(fields=('video', 'convidado'), name='media_video_convidado_uk')],
            },
        ),
        migrations.CreateModel(
            name='VideoPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrocinadores_videos', to='media.patrocinador')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_patrocinadores', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_video_patrocinador_tb"',
                'constraints': [models.UniqueConstraint(fields=('video', 'patrocinador'), name='media_video_patrocinador_uk')],
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags_videos', to='media.tagyubotuka')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_tags', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_video_tag_tb"',
                'constraints': [models.UniqueConstraint(fields=('video', 'tag'), name='media_video_tag_uk')],
            },
        ),
    ]
