# Generated by Django 6.0.5 on 2026-07-26 19:19

import apps.core.domain
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_uuid_destaque_editorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='categoria_editorial',
            field=models.ForeignKey(blank=True, db_column='media_programa_fk_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_editoriais', to='media.categoriayubotuka'),
        ),
        migrations.AddField(
            model_name='programa',
            name='ordem',
            field=models.PositiveIntegerField(db_column='media_programa_ordem', default=0),
        ),
        migrations.AddField(
            model_name='temporada',
            name='capa',
            field=models.ImageField(blank=True, db_column='media_temporada_capa', upload_to='media/temporadas/', validators=[apps.core.domain.validar_imagem_publica]),
        ),
        migrations.AddField(
            model_name='temporada',
            name='encerrada',
            field=models.BooleanField(db_column='media_temporada_encerrada', default=False),
        ),
        migrations.AddField(
            model_name='temporada',
            name='ordem',
            field=models.PositiveIntegerField(db_column='media_temporada_ordem', default=0),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='autor',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_autor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_yubotuka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='canal',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_canal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_yubotuka', to='media.canal'),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_yubotuka', to='media.categoriayubotuka'),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='descricao',
            field=models.TextField(blank=True, db_column='media_transmissao_descricao'),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='destaque',
            field=models.BooleanField(db_column='media_transmissao_destaque', default=False),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='exibir_na_home',
            field=models.BooleanField(db_column='media_transmissao_exibir_home', default=False),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='local',
            field=models.CharField(blank=True, db_column='media_transmissao_local', max_length=180),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='moderado_por',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_moderador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_yubotuka_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='programa',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_programa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes_yubotuka', to='media.programa'),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='slug',
            field=models.SlugField(blank=True, db_column='media_transmissao_slug', editable=False, max_length=230, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='thumbnail',
            field=models.URLField(blank=True, db_column='media_transmissao_thumbnail', max_length=500),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='titulo',
            field=models.CharField(blank=True, db_column='media_transmissao_titulo', max_length=200),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='video_id',
            field=models.CharField(blank=True, db_column='media_transmissao_video_id', max_length=20),
        ),
        migrations.AddField(
            model_name='transmissao',
            name='video_resultante',
            field=models.ForeignKey(blank=True, db_column='media_transmissao_fk_video_resultante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes_origem', to='media.video'),
        ),
        migrations.AlterField(
            model_name='transmissao',
            name='episodio',
            field=models.OneToOneField(blank=True, db_column='media_transmissao_fk_episodio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissao', to='media.episodio'),
        ),
        migrations.AlterField(
            model_name='transmissao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('AGENDADA', 'Agendada'), ('AO_VIVO', 'Ao vivo'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada'), ('PUBLICADA', 'Publicada'), ('ARQUIVADA', 'Arquivada')], db_column='media_transmissao_status', default='RASCUNHO', max_length=20),
        ),
        migrations.CreateModel(
            name='HomologacaoVideoMigrado',
            fields=[
                ('id', models.BigAutoField(db_column='media_homologacao_video_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('homologado', models.BooleanField(default=False)),
                ('homologado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('divergencias', models.JSONField(blank=True, default=dict)),
                ('valores_confirmados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('episodio_legado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='homologacao_video', to='media.episodio')),
                ('homologado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_migrados_homologados', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homologacao_migracao', to='media.video')),
            ],
            options={
                'db_table': '"media"."media_homologacao_video_tb"',
                'ordering': ['homologado', 'video__titulo'],
            },
        ),
        migrations.CreateModel(
            name='CanalUsuario',
            fields=[
                ('id', models.BigAutoField(db_column='media_canal_usuario_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pode_editar', models.BooleanField(default=True)),
                ('pode_moderar', models.BooleanField(default=False)),
                ('motivo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_autorizados', to='media.canal')),
                ('concedido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_canal_concedidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_canais_yubotuka', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"media"."media_canal_usuario_tb"',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('revogado_em__isnull', True)), fields=('canal', 'usuario'), name='media_canal_usuario_ativo_uk')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaApresentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('apresentador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apresentadores_programas', to='media.apresentador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_apresentadores', to='media.programa')),
            ],
            options={
                'db_table': '"media"."media_programa_apresentador_tb"',
                'constraints': [models.UniqueConstraint(fields=('programa', 'apresentador'), name='media_programa_apresentador_uk')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrocinadores_programas', to='media.patrocinador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_patrocinadores', to='media.programa')),
            ],
            options={
                'db_table': '"media"."media_programa_patrocinador_tb"',
                'constraints': [models.UniqueConstraint(fields=('programa', 'patrocinador'), name='media_programa_patrocinador_uk')],
            },
        ),
        migrations.CreateModel(
            name='TransmissaoApresentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('apresentador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apresentadores_transmissoes', to='media.apresentador')),
                ('transmissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissoes_apresentadores', to='media.transmissao')),
            ],
            options={
                'db_table': '"media"."media_transmissao_apresentador_tb"',
                'constraints': [models.UniqueConstraint(fields=('transmissao', 'apresentador'), name='media_transmissao_apresentador_uk')],
            },
        ),
        migrations.CreateModel(
            name='TransmissaoConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convidados_transmissoes', to='media.convidado')),
                ('transmissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissoes_convidados', to='media.transmissao')),
            ],
            options={
                'db_table': '"media"."media_transmissao_convidado_tb"',
                'constraints': [models.UniqueConstraint(fields=('transmissao', 'convidado'), name='media_transmissao_convidado_uk')],
            },
        ),
        migrations.CreateModel(
            name='TransmissaoPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrocinadores_transmissoes', to='media.patrocinador')),
                ('transmissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissoes_patrocinadores', to='media.transmissao')),
            ],
            options={
                'db_table': '"media"."media_transmissao_patrocinador_tb"',
                'constraints': [models.UniqueConstraint(fields=('transmissao', 'patrocinador'), name='media_transmissao_patrocinador_uk')],
            },
        ),
    ]
