# Generated by Django 6.0.5 on 2026-07-19 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS government;', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='OrgaoPublico',
            fields=[
                ('id', models.BigAutoField(db_column='government_orgao_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_orgao_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('PREFEITURA', 'Prefeitura'), ('SECRETARIA', 'Secretaria'), ('AUTARQUIA', 'Autarquia'), ('CONSELHO', 'Conselho'), ('OUTRO', 'Outro')], db_column='government_orgao_tipo', max_length=20)),
                ('nome', models.CharField(db_column='government_orgao_nome', max_length=180)),
                ('sigla', models.CharField(blank=True, db_column='government_orgao_sigla', max_length=30)),
                ('slug', models.SlugField(blank=True, db_column='government_orgao_slug', max_length=210, unique=True)),
                ('descricao', models.TextField(blank=True, db_column='government_orgao_descricao')),
                ('logotipo', models.ImageField(blank=True, db_column='government_orgao_logotipo', upload_to='government/orgaos/')),
                ('site_oficial', models.URLField(blank=True, db_column='government_orgao_site')),
                ('telefone', models.CharField(blank=True, db_column='government_orgao_telefone', max_length=30)),
                ('email', models.EmailField(blank=True, db_column='government_orgao_email', max_length=254)),
                ('verificado', models.BooleanField(db_column='government_orgao_verificado', default=False)),
                ('ativo', models.BooleanField(db_column='government_orgao_ativo', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_orgao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_orgao_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_orgao_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_orgao_tb"',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AcaoPublica',
            fields=[
                ('id', models.BigAutoField(db_column='government_acao_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_acao_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra'), ('PROJETO', 'Projeto'), ('PROGRAMA', 'Programa'), ('CAMPANHA', 'Campanha'), ('AUDIENCIA_PUBLICA', 'Audiência pública'), ('EVENTO', 'Evento'), ('SERVICO', 'Serviço'), ('COMUNICADO', 'Comunicado'), ('CONSULTA_PUBLICA', 'Consulta pública')], db_column='government_acao_tipo', max_length=30)),
                ('titulo', models.CharField(db_column='government_acao_titulo', max_length=220)),
                ('slug', models.SlugField(blank=True, db_column='government_acao_slug', max_length=250, unique=True)),
                ('resumo', models.TextField(blank=True, db_column='government_acao_resumo')),
                ('descricao', models.TextField(db_column='government_acao_descricao')),
                ('objetivo', models.TextField(blank=True, db_column='government_acao_objetivo')),
                ('publico_alvo', models.CharField(blank=True, db_column='government_acao_publico_alvo', max_length=220)),
                ('local', models.CharField(blank=True, db_column='government_acao_local', max_length=220)),
                ('bairro', models.CharField(blank=True, db_column='government_acao_bairro', max_length=120)),
                ('cidade', models.CharField(db_column='government_acao_cidade', max_length=120)),
                ('inicio_previsto', models.DateField(blank=True, db_column='government_acao_inicio_previsto', null=True)),
                ('conclusao_prevista', models.DateField(blank=True, db_column='government_acao_conclusao_prevista', null=True)),
                ('situacao', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('LICITACAO', 'Licitação'), ('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('ADIADA', 'Adiada'), ('CANCELADA', 'Cancelada')], db_column='government_acao_situacao', default='PLANEJADA', max_length=20)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado'), ('PAUSADO', 'Pausado'), ('REJEITADO', 'Rejeitado')], db_column='government_acao_status', default='RASCUNHO', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, db_column='government_acao_motivo_rejeicao')),
                ('imagem', models.ImageField(blank=True, db_column='government_acao_imagem', upload_to='government/acoes/')),
                ('destaque', models.BooleanField(db_column='government_acao_destaque', default=False)),
                ('revisado_em', models.DateTimeField(blank=True, db_column='government_acao_revisado_em', null=True)),
                ('publicado_em', models.DateTimeField(blank=True, db_column='government_acao_publicado_em', null=True)),
                ('ativo', models.BooleanField(db_column='government_acao_ativo', default=True)),
                ('autor', models.ForeignKey(db_column='government_acao_fk_autor', on_delete=django.db.models.deletion.PROTECT, related_name='acoes_publicas', to=settings.AUTH_USER_MODEL)),
                ('publicador', models.ForeignKey(blank=True, db_column='government_acao_fk_publicador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_publicadas', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(blank=True, db_column='government_acao_fk_revisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('orgao', models.ForeignKey(db_column='government_acao_fk_orgao', on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='government.orgaopublico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_acao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_acao_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_acao_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_acao_tb"',
            },
        ),
        migrations.CreateModel(
            name='AcaoLink',
            fields=[
                ('id', models.BigAutoField(db_column='government_link_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_link_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='government_link_titulo', max_length=180)),
                ('url', models.URLField(db_column='government_link_url', max_length=500)),
                ('tipo', models.CharField(blank=True, db_column='government_link_tipo', max_length=30)),
                ('ordem', models.PositiveIntegerField(db_column='government_link_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='government_link_ativo', default=True)),
                ('acao', models.ForeignKey(db_column='government_link_fk_acao', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='government.acaopublica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_link_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_link_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_link_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_acao_link_tb"',
            },
        ),
        migrations.CreateModel(
            name='AcaoDocumento',
            fields=[
                ('id', models.BigAutoField(db_column='government_documento_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_documento_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='government_documento_titulo', max_length=180)),
                ('tipo', models.CharField(db_column='government_documento_tipo', max_length=30)),
                ('arquivo', models.FileField(db_column='government_documento_arquivo', upload_to='government/documentos/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(db_column='government_documento_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='government_documento_ativo', default=True)),
                ('acao', models.ForeignKey(db_column='government_documento_fk_acao', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='government.acaopublica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_documento_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_documento_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_documento_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_acao_documento_tb"',
            },
        ),
        migrations.CreateModel(
            name='AcaoAtualizacao',
            fields=[
                ('id', models.BigAutoField(db_column='government_atualizacao_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_atualizacao_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(db_column='government_atualizacao_titulo', max_length=180)),
                ('descricao', models.TextField(db_column='government_atualizacao_descricao')),
                ('percentual', models.PositiveSmallIntegerField(blank=True, db_column='government_atualizacao_percentual', null=True)),
                ('data', models.DateField(db_column='government_atualizacao_data')),
                ('imagem', models.ImageField(blank=True, db_column='government_atualizacao_imagem', upload_to='government/atualizacoes/')),
                ('ordem', models.PositiveIntegerField(db_column='government_atualizacao_ordem', default=0)),
                ('ativo', models.BooleanField(db_column='government_atualizacao_ativo', default=True)),
                ('autor', models.ForeignKey(db_column='government_atualizacao_fk_autor', on_delete=django.db.models.deletion.PROTECT, related_name='atualizacoes_publicas', to=settings.AUTH_USER_MODEL)),
                ('acao', models.ForeignKey(db_column='government_atualizacao_fk_acao', on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='government.acaopublica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_atualizacao_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_atualizacao_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_atualizacao_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_acao_atualizacao_tb"',
                'ordering': ['data', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OrgaoUsuario',
            fields=[
                ('id', models.BigAutoField(db_column='government_orgao_usuario_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='government_orgao_usuario_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('funcao', models.CharField(choices=[('GESTOR', 'Gestor'), ('EDITOR', 'Editor'), ('REVISOR', 'Revisor')], db_column='government_orgao_usuario_funcao', max_length=20)),
                ('gestor', models.BooleanField(db_column='government_orgao_usuario_gestor', default=False)),
                ('editor', models.BooleanField(db_column='government_orgao_usuario_editor', default=False)),
                ('revisor', models.BooleanField(db_column='government_orgao_usuario_revisor', default=False)),
                ('pode_publicar', models.BooleanField(db_column='government_orgao_usuario_publicar', default=False)),
                ('ativo', models.BooleanField(db_column='government_orgao_usuario_ativo', default=True)),
                ('orgao', models.ForeignKey(db_column='government_orgao_usuario_fk_orgao', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='government.orgaopublico')),
                ('usuario', models.ForeignKey(db_column='government_orgao_usuario_fk_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_publicos', to=settings.AUTH_USER_MODEL)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='government_orgao_usuario_criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='government_orgao_usuario_atualizado_em')),
                ('excluido_em', models.DateTimeField(blank=True, db_column='government_orgao_usuario_excluido_em', null=True)),
            ],
            options={
                'db_table': '"government"."government_orgao_usuario_tb"',
            },
        ),
        migrations.AddIndex(
            model_name='acaopublica',
            index=models.Index(fields=['status', 'publicado_em'], name='government_acao_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgaousuario',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('orgao', 'usuario'), name='government_orgao_usuario_uk'),
        ),
    ]
